from __future__ import annotations

from typing import Any

PATH_MATRIX: list[dict[str, Any]] = [
    {
        "PATH_ID": "P01",
        "SOURCE": "app_session_builder_mixin.start_custom_session/get_session_builder_pool",
        "ENFORCEMENT_LOCATION": "filter_training_questions + get_session_builder_pool",
        "EARLY_FILTER": "YES",
        "LATE_REVALIDATION": "YES",
        "TEST_ID": "G3-001",
        "STATUS": "ENFORCED",
    },
    {
        "PATH_ID": "P02",
        "SOURCE": "build_smart_practice_pool / smart_practice_core.build_smart_practice_selection",
        "ENFORCEMENT_LOCATION": "filter_training_questions before Smart Practice selection",
        "EARLY_FILTER": "YES",
        "LATE_REVALIDATION": "YES",
        "TEST_ID": "G3-002",
        "STATUS": "ENFORCED",
    },
    {
        "PATH_ID": "P03",
        "SOURCE": "_build_smart_practice_signal_payload",
        "ENFORCEMENT_LOCATION": "derived_training_questions(stage=SMART_PRACTICE_SIGNAL)",
        "EARLY_FILTER": "YES",
        "LATE_REVALIDATION": "N/A",
        "TEST_ID": "G3-003",
        "STATUS": "ENFORCED",
    },
    {
        "PATH_ID": "P04",
        "SOURCE": "schedule_smart_practice_prewarm / SmartPracticePrewarmService",
        "ENFORCEMENT_LOCATION": "snapshot TRAIN filter + partition_cache_identity",
        "EARLY_FILTER": "YES",
        "LATE_REVALIDATION": "YES",
        "TEST_ID": "G3-005",
        "STATUS": "ENFORCED",
    },
    {
        "PATH_ID": "P05",
        "SOURCE": "smart_practice_worker.build_detached_signal_payload",
        "ENFORCEMENT_LOCATION": "_smart_practice_worker_snapshot TRAIN-only pools",
        "EARLY_FILTER": "YES",
        "LATE_REVALIDATION": "YES",
        "TEST_ID": "G3-004",
        "STATUS": "ENFORCED",
    },
    {
        "PATH_ID": "P06",
        "SOURCE": "build_due_review_pool / select_due_review_questions",
        "ENFORCEMENT_LOCATION": "TRAIN filter before due-review selection",
        "EARLY_FILTER": "YES",
        "LATE_REVALIDATION": "YES",
        "TEST_ID": "G3-006",
        "STATUS": "ENFORCED",
    },
    {
        "PATH_ID": "P07",
        "SOURCE": "build_weak_retest_pool",
        "ENFORCEMENT_LOCATION": "TRAIN filter before weak-retest selection",
        "EARLY_FILTER": "YES",
        "LATE_REVALIDATION": "YES",
        "TEST_ID": "G3-007",
        "STATUS": "ENFORCED",
    },
    {
        "PATH_ID": "P08",
        "SOURCE": "restore_full_bank / restore_progress_manual",
        "ENFORCEMENT_LOCATION": "restore_experimental_session revalidation",
        "EARLY_FILTER": "YES",
        "LATE_REVALIDATION": "YES",
        "TEST_ID": "G3-035",
        "STATUS": "ENFORCED",
    },
    {
        "PATH_ID": "P09",
        "SOURCE": "start_session_from_pool",
        "ENFORCEMENT_LOCATION": "late revalidate pool before session start",
        "EARLY_FILTER": "YES",
        "LATE_REVALIDATION": "YES",
        "TEST_ID": "G3-001",
        "STATUS": "ENFORCED",
    },
    {
        "PATH_ID": "P10",
        "SOURCE": "find_question_twins / maybe_queue_question_twins",
        "ENFORCEMENT_LOCATION": "training_source_questions + insert revalidation",
        "EARLY_FILTER": "YES",
        "LATE_REVALIDATION": "YES",
        "TEST_ID": "G3-009",
        "STATUS": "ENFORCED",
    },
    {
        "PATH_ID": "P11",
        "SOURCE": "maybe_queue_delayed_recall_probe",
        "ENFORCEMENT_LOCATION": "TRAIN filter / revalidate_training_question(DELAYED_RECALL)",
        "EARLY_FILTER": "YES",
        "LATE_REVALIDATION": "YES",
        "TEST_ID": "G3-010",
        "STATUS": "ENFORCED",
    },
    {
        "PATH_ID": "P12",
        "SOURCE": "find_memory_ramp_candidates / maybe_queue_memory_ramp",
        "ENFORCEMENT_LOCATION": "TRAIN filter / revalidate_training_question(MEMORY_RAMP)",
        "EARLY_FILTER": "YES",
        "LATE_REVALIDATION": "YES",
        "TEST_ID": "G3-011",
        "STATUS": "ENFORCED",
    },
    {
        "PATH_ID": "P13",
        "SOURCE": "find_wrong_answer_memory_candidates",
        "ENFORCEMENT_LOCATION": "TRAIN filter / revalidate_training_question(WRONG_ANSWER_MEMORY)",
        "EARLY_FILTER": "YES",
        "LATE_REVALIDATION": "YES",
        "TEST_ID": "G3-012",
        "STATUS": "ENFORCED",
    },
    {
        "PATH_ID": "P14",
        "SOURCE": "find_confusion_pair_candidates",
        "ENFORCEMENT_LOCATION": "TRAIN filter / revalidate_training_question(CONFUSION_PAIR)",
        "EARLY_FILTER": "YES",
        "LATE_REVALIDATION": "YES",
        "TEST_ID": "G3-013",
        "STATUS": "ENFORCED",
    },
    {
        "PATH_ID": "P15",
        "SOURCE": "maybe_trigger_streak_rescue",
        "ENFORCEMENT_LOCATION": "TRAIN filter / revalidate_training_question(STREAK_RESCUE)",
        "EARLY_FILTER": "YES",
        "LATE_REVALIDATION": "YES",
        "TEST_ID": "G3-014",
        "STATUS": "ENFORCED",
    },
    {
        "PATH_ID": "P16",
        "SOURCE": "plan_misconception_repair",
        "ENFORCEMENT_LOCATION": "TRAIN filter / revalidate_training_question(MISCONCEPTION_REPAIR)",
        "EARLY_FILTER": "YES",
        "LATE_REVALIDATION": "YES",
        "TEST_ID": "G3-015",
        "STATUS": "ENFORCED",
    },
    {
        "PATH_ID": "P17",
        "SOURCE": "_rebuild_followup_candidate_index",
        "ENFORCEMENT_LOCATION": "index built from TRAIN-only source",
        "EARLY_FILTER": "YES",
        "LATE_REVALIDATION": "YES",
        "TEST_ID": "G3-018",
        "STATUS": "ENFORCED",
    },
    {
        "PATH_ID": "P18",
        "SOURCE": "app_game_mixin.maybe_trigger_boss_round",
        "ENFORCEMENT_LOCATION": "TRAIN source + insert revalidation",
        "EARLY_FILTER": "YES",
        "LATE_REVALIDATION": "YES",
        "TEST_ID": "G3-016",
        "STATUS": "ENFORCED",
    },
    {
        "PATH_ID": "P19",
        "SOURCE": "maybe_trigger_stealth_checkpoint",
        "ENFORCEMENT_LOCATION": "TRAIN source + insert revalidation",
        "EARLY_FILTER": "YES",
        "LATE_REVALIDATION": "YES",
        "TEST_ID": "G3-017",
        "STATUS": "ENFORCED",
    },
    {
        "PATH_ID": "P20",
        "SOURCE": "refresh_question_list / jump_to_question / on_listbox_select",
        "ENFORCEMENT_LOCATION": "jump/list late revalidation against current session eligibility",
        "EARLY_FILTER": "N/A",
        "LATE_REVALIDATION": "YES",
        "TEST_ID": "G3-001",
        "STATUS": "ENFORCED",
    },
    {
        "PATH_ID": "P21",
        "SOURCE": "render_question / _render_choice_rows",
        "ENFORCEMENT_LOCATION": "revalidate_training_question before render",
        "EARLY_FILTER": "N/A",
        "LATE_REVALIDATION": "YES",
        "TEST_ID": "G3-001",
        "STATUS": "ENFORCED",
    },
    {
        "PATH_ID": "P22",
        "SOURCE": "_inline_explanation_for_question / complete_explanation_recall",
        "ENFORCEMENT_LOCATION": "PROBE explanation custody / contamination record",
        "EARLY_FILTER": "N/A",
        "LATE_REVALIDATION": "YES",
        "TEST_ID": "G3-030",
        "STATUS": "ENFORCED",
    },
    {
        "PATH_ID": "P23",
        "SOURCE": "format_choice_explanations",
        "ENFORCEMENT_LOCATION": "PROBE choice-explanation redaction during active experiment",
        "EARLY_FILTER": "N/A",
        "LATE_REVALIDATION": "YES",
        "TEST_ID": "G3-030",
        "STATUS": "ENFORCED",
    },
    {
        "PATH_ID": "P24",
        "SOURCE": "adaptive_explanation_text",
        "ENFORCEMENT_LOCATION": "PROBE adaptive-text custody",
        "EARLY_FILTER": "N/A",
        "LATE_REVALIDATION": "YES",
        "TEST_ID": "G3-030",
        "STATUS": "ENFORCED",
    },
    {
        "PATH_ID": "P25",
        "SOURCE": "append_answer_history / append_progress_history",
        "ENFORCEMENT_LOCATION": "sanitize_history_event; PROBE text not persisted",
        "EARLY_FILTER": "N/A",
        "LATE_REVALIDATION": "YES",
        "TEST_ID": "G3-030",
        "STATUS": "ENFORCED",
    },
    {
        "PATH_ID": "P26",
        "SOURCE": "save_progress / backup_progress_manual",
        "ENFORCEMENT_LOCATION": "persist authority metadata only; no trusted saved pool",
        "EARLY_FILTER": "N/A",
        "LATE_REVALIDATION": "YES",
        "TEST_ID": "G3-035",
        "STATUS": "ENFORCED",
    },
    {
        "PATH_ID": "P27",
        "SOURCE": "restore_progress_manual / load_progress_if_present",
        "ENFORCEMENT_LOCATION": "restore_experimental_session fail-closed",
        "EARLY_FILTER": "N/A",
        "LATE_REVALIDATION": "YES",
        "TEST_ID": "G3-035",
        "STATUS": "ENFORCED",
    },
    {
        "PATH_ID": "P28",
        "SOURCE": "load_session_if_present / build_session_snapshot",
        "ENFORCEMENT_LOCATION": "session snapshot cand01r3 metadata revalidation",
        "EARLY_FILTER": "N/A",
        "LATE_REVALIDATION": "YES",
        "TEST_ID": "G3-035",
        "STATUS": "ENFORCED",
    },
    {
        "PATH_ID": "P29",
        "SOURCE": "compute_analytics / open_analytics_window",
        "ENFORCEMENT_LOCATION": "sanitize_learner_export",
        "EARLY_FILTER": "YES",
        "LATE_REVALIDATION": "YES",
        "TEST_ID": "G3-030",
        "STATUS": "ENFORCED",
    },
    {
        "PATH_ID": "P30",
        "SOURCE": "_build_delayed_probe_rows",
        "ENFORCEMENT_LOCATION": "delayed-probe label is not MEASUREMENT eligibility",
        "EARLY_FILTER": "YES",
        "LATE_REVALIDATION": "YES",
        "TEST_ID": "G3-010",
        "STATUS": "ENFORCED",
    },
    {
        "PATH_ID": "P31",
        "SOURCE": "export_analytics_json",
        "ENFORCEMENT_LOCATION": "sanitize_learner_export before write",
        "EARLY_FILTER": "N/A",
        "LATE_REVALIDATION": "YES",
        "TEST_ID": "G3-030",
        "STATUS": "ENFORCED",
    },
    {
        "PATH_ID": "P32",
        "SOURCE": "generate_smart_practice_measurement_report",
        "ENFORCEMENT_LOCATION": "TRAIN-only champion instrumentation; not 7-day endpoint",
        "EARLY_FILTER": "YES",
        "LATE_REVALIDATION": "N/A",
        "TEST_ID": "G3-003",
        "STATUS": "ENFORCED",
    },
    {
        "PATH_ID": "P33",
        "SOURCE": "analytics_recommendations.build_analytics_recommendations",
        "ENFORCEMENT_LOCATION": "TRAIN-derived recommendations; PROBE families excluded",
        "EARLY_FILTER": "YES",
        "LATE_REVALIDATION": "YES",
        "TEST_ID": "G3-001",
        "STATUS": "ENFORCED",
    },
    {
        "PATH_ID": "P34",
        "SOURCE": "open_bank / reload_bank / load_from_path",
        "ENFORCEMENT_LOCATION": "unknown bank items NOT_ELIGIBLE while CAND-01R3 active; default bank unchanged",
        "EARLY_FILTER": "YES",
        "LATE_REVALIDATION": "YES",
        "TEST_ID": "G3-037",
        "STATUS": "ENFORCED",
    },
    {
        "PATH_ID": "P35",
        "SOURCE": "ingestion.importer.import_jsonl",
        "ENFORCEMENT_LOCATION": "imported items absent from frozen manifest are QUESTION_NOT_IN_MANIFEST/UNASSIGNED",
        "EARLY_FILTER": "YES",
        "LATE_REVALIDATION": "N/A",
        "TEST_ID": "G3-023",
        "STATUS": "ENFORCED",
    },
    {
        "PATH_ID": "P36",
        "SOURCE": "compile_question_bank",
        "ENFORCEMENT_LOCATION": "compiled candidate bank is not the launch bank; unknown compile items fail closed in experiment",
        "EARLY_FILTER": "N/A",
        "LATE_REVALIDATION": "YES",
        "TEST_ID": "G3-037",
        "STATUS": "ENFORCED",
    },
    {
        "PATH_ID": "P37",
        "SOURCE": "tools.build_sc900_phase3",
        "ENFORCEMENT_LOCATION": "design-time builder remains non-runtime; frozen hashes verified",
        "EARLY_FILTER": "N/A",
        "LATE_REVALIDATION": "N/A",
        "TEST_ID": "G3-019",
        "STATUS": "DESIGN_TIME_NOT_RUNTIME",
    },
    {
        "PATH_ID": "P38",
        "SOURCE": "extraction/pipeline.py",
        "ENFORCEMENT_LOCATION": "extracted rows stay unassigned until authorized partition revision",
        "EARLY_FILTER": "N/A",
        "LATE_REVALIDATION": "N/A",
        "TEST_ID": "G3-023",
        "STATUS": "ADMIN_AUTHORING_CONTAMINATION_RECORDED",
    },
    {
        "PATH_ID": "P39",
        "SOURCE": "open_screenshot_review_window",
        "ENFORCEMENT_LOCATION": "PROBE screenshot review during experiment records contamination",
        "EARLY_FILTER": "N/A",
        "LATE_REVALIDATION": "YES",
        "TEST_ID": "G3-030",
        "STATUS": "ADMIN_AUTHORING_CONTAMINATION_RECORDED",
    },
    {
        "PATH_ID": "P40",
        "SOURCE": "open_issue_review_window",
        "ENFORCEMENT_LOCATION": "PROBE issue review during experiment records contamination",
        "EARLY_FILTER": "N/A",
        "LATE_REVALIDATION": "YES",
        "TEST_ID": "G3-030",
        "STATUS": "ADMIN_AUTHORING_CONTAMINATION_RECORDED",
    },
    {
        "PATH_ID": "P41",
        "SOURCE": "redo_question",
        "ENFORCEMENT_LOCATION": "MeasurementLedger kind=REDO is not a new first attempt",
        "EARLY_FILTER": "N/A",
        "LATE_REVALIDATION": "YES",
        "TEST_ID": "G3-031",
        "STATUS": "ENFORCED",
    },
    {
        "PATH_ID": "P42",
        "SOURCE": "tests and fixtures",
        "ENFORCEMENT_LOCATION": "fixtures may construct ineligible items only to prove fail-closed behavior",
        "EARLY_FILTER": "N/A",
        "LATE_REVALIDATION": "N/A",
        "TEST_ID": "G3-024",
        "STATUS": "FIXTURE_FAIL_CLOSED",
    },
    {
        "PATH_ID": "P43",
        "SOURCE": "content/sc900/phase3/train_probe_manifest.json",
        "ENFORCEMENT_LOCATION": "frozen design-time manifest loaded by cand01r3_partition; not mutated",
        "EARLY_FILTER": "N/A",
        "LATE_REVALIDATION": "N/A",
        "TEST_ID": "G3-020",
        "STATUS": "DESIGN_TIME_NOT_RUNTIME",
    },
    {
        "PATH_ID": "P44",
        "SOURCE": "render_question exam_reveal",
        "ENFORCEMENT_LOCATION": "exam mode is not automatic MEASUREMENT; stem exposure contaminates unmeasured PROBE",
        "EARLY_FILTER": "N/A",
        "LATE_REVALIDATION": "YES",
        "TEST_ID": "G3-030",
        "STATUS": "ENFORCED",
    },
    {
        "PATH_ID": "P45",
        "SOURCE": "progress directory recovery",
        "ENFORCEMENT_LOCATION": "recovered history cannot mint a new primary PROBE observation",
        "EARLY_FILTER": "N/A",
        "LATE_REVALIDATION": "YES",
        "TEST_ID": "G3-033",
        "STATUS": "ENFORCED",
    },
    {
        "PATH_ID": "P46",
        "SOURCE": "tools/clean_bank.py lint/validate",
        "ENFORCEMENT_LOCATION": "operator QA is authoring, not learner training; outputs must not replace launch bank",
        "EARLY_FILTER": "N/A",
        "LATE_REVALIDATION": "N/A",
        "TEST_ID": "G3-037",
        "STATUS": "ADMIN_AUTHORING_CONTAMINATION_RECORDED",
    },
    {
        "PATH_ID": "P47",
        "SOURCE": "smart_practice_concept_graph.select_prerequisite_path",
        "ENFORCEMENT_LOCATION": "graph neighborhoods used for training built from TRAIN-only signal questions",
        "EARLY_FILTER": "YES",
        "LATE_REVALIDATION": "N/A",
        "TEST_ID": "G3-003",
        "STATUS": "ENFORCED",
    },
    {
        "PATH_ID": "P48",
        "SOURCE": "compile/analytics/progress JSON write surfaces",
        "ENFORCEMENT_LOCATION": "sanitize_learner_export; no dedicated question exporter",
        "EARLY_FILTER": "N/A",
        "LATE_REVALIDATION": "YES",
        "TEST_ID": "G3-030",
        "STATUS": "ENFORCED",
    },
]


def required_path_ids() -> list[str]:
    return [f"P{index:02d}" for index in range(1, 49)]
