FONT_FAMILY = 'Segoe UI'

TOPBAR_TITLE_FONT = (FONT_FAMILY, 11, 'bold')
QUESTION_META_FONT = (FONT_FAMILY, 10, 'bold')
QUESTION_META_STRIP_FONT = (FONT_FAMILY, 9, 'bold')
QUESTION_PROMPT_FONT = (FONT_FAMILY, 14)
QUESTION_EXPLANATION_FONT = (FONT_FAMILY, 12)
QUESTION_WRONG_EXPLANATION_FONT = (FONT_FAMILY, 13, 'bold')
QUESTION_STATUS_FONT = (FONT_FAMILY, 11, 'bold')

CHOICE_BADGE_FONT = (FONT_FAMILY, 12, 'bold')
CHOICE_TEXT_FONT = (FONT_FAMILY, 13)
CHOICE_MARK_FONT = (FONT_FAMILY, 13, 'bold')
CHOICE_DETAIL_FONT = (FONT_FAMILY, 12)

CHOICE_DENSE_BADGE_FONT = (FONT_FAMILY, 11, 'bold')
CHOICE_DENSE_TEXT_FONT = (FONT_FAMILY, 12)
CHOICE_DENSE_MARK_FONT = (FONT_FAMILY, 12, 'bold')
CHOICE_DENSE_DETAIL_FONT = (FONT_FAMILY, 11)
CHOICE_DENSE_WRONG_DETAIL_FONT = (FONT_FAMILY, 12, 'bold')
