from __future__ import annotations

from tools.sc900_microsoft_corpus_qemit import question_record


def batch_09() -> list[dict]:
    b = "mlc-batch-09"
    return [
        question_record(
            serial=201,
            leaf="zero_trust_model",
            difficulty="intermediate",
            stem_style="concept_distinction",
            stem="A Zero Trust program verifies every sign-in, yet many accounts still hold standing full-access roles. Which Zero Trust principle is missing?",
            choices=[
                ("a", "Use least-privilege access so identities receive only the permissions required for the task"),
                ("b", "Trust any later request that originates on the corporate LAN"),
                ("c", "Treat the first successful VPN connection as permanent authorization"),
                ("d", "Replace identity verification with a single inbound allow-all network rule"),
            ],
            correct="a",
            explanation="Zero Trust includes least privilege. Verifying sign-ins is incomplete if identities keep standing full access after authentication.",
            source_id="doc-zero-trust-overview",
            semantic_family_id="zero_trust_and_identity_perimeter",
            tested_decision="least_privilege_not_standing_full_access",
            misconception_target="verify_once_equals_zero_trust",
            batch=b,
        ),
        question_record(
            serial=202,
            leaf="zero_trust_model",
            difficulty="intermediate",
            stem_style="multi_select",
            stem="Which two principles are core to a Zero Trust architecture? (Choose two.)",
            choices=[
                ("a", "Verify explicitly"),
                ("b", "Use least-privilege access"),
                ("c", "Trust all internal network traffic by default"),
                ("d", "Disable continuous validation after the first successful sign-in"),
            ],
            correct=["a", "b"],
            explanation="Microsoft describes Zero Trust around verify explicitly, least privilege, and assume breach. Default internal trust and one-time validation contradict that model.",
            source_id="module-describe-security-concepts-methodologies",
            semantic_family_id="zero_trust_and_identity_perimeter",
            tested_decision="zt_verify_and_least_privilege_principles",
            misconception_target="internal_network_equals_trust",
            qtype="multi_select",
            batch=b,
        ),
        question_record(
            serial=203,
            leaf="authentication",
            difficulty="intermediate",
            stem_style="concept_distinction",
            stem="A user completes password and MFA challenges. Only afterward does the app decide whether that account may open a finance report. Which statement is accurate?",
            choices=[
                ("a", "Authentication proved who the user is; authorization then decided what the identity may do"),
                ("b", "Authorization happened first and made authentication unnecessary"),
                ("c", "Successful authentication automatically authorizes every Microsoft 365 action"),
                ("d", "The report permission check is a Conditional Access named-location signal, not authorization"),
            ],
            correct="a",
            explanation="Authentication verifies identity first. Authorization is the later permission decision and is not implied by a successful sign-in.",
            source_id="module-describe-identity-principles-concepts",
            semantic_family_id="authentication_vs_authorization",
            tested_decision="authn_precedes_authorization",
            misconception_target="signin_equals_all_permissions",
            batch=b,
        ),
        question_record(
            serial=204,
            leaf="authentication",
            difficulty="intermediate",
            stem_style="direct_concept",
            stem="Which grouping correctly describes common authentication factor categories?",
            choices=[
                ("a", "Something you know, something you have, and something you are"),
                ("b", "Retention, deletion, and record declaration"),
                ("c", "SIEM collection, SOAR automation, and hunting"),
                ("d", "Sensitivity labeling, DLP blocking, and eDiscovery hold"),
            ],
            correct="a",
            explanation="Authentication factors are commonly knowledge, possession, and inherence. The other groupings are compliance or SOC capabilities, not authentication factor types.",
            source_id="module-describe-identity-principles-concepts",
            semantic_family_id="authentication_vs_authorization",
            tested_decision="know_have_are_factor_categories",
            batch=b,
        ),
        question_record(
            serial=205,
            leaf="authorization",
            difficulty="intermediate",
            stem_style="misconception_correction",
            stem="A contractor signs in successfully with MFA but cannot open a payroll app. A colleague says the sign-in proves the contractor is allowed to use every company app. What is wrong with that claim?",
            choices=[
                (
                    "a",
                    "Authentication success does not grant every permission; authorization still evaluates roles and policies",
                ),
                ("b", "MFA replaces role-based access control, so the app should open automatically"),
                ("c", "Federation always grants Global Administrator rights after sign-in"),
                ("d", "Authorization applies only to guest users and never to contractors who can sign in"),
            ],
            correct="a",
            explanation="A completed sign-in proves identity. Apps and roles still authorize what that identity may access, so MFA success is not blanket permission.",
            source_id="module-describe-identity-principles-concepts",
            semantic_family_id="authentication_vs_authorization",
            tested_decision="signin_success_is_not_blanket_authorization",
            misconception_target="mfa_implies_full_app_access",
            batch=b,
        ),
        question_record(
            serial=206,
            leaf="identity_primary_security_perimeter",
            difficulty="intermediate",
            stem_style="short_scenario",
            stem="Users connect to Microsoft 365 from home networks, coffee shops, and mobile carriers. Security still treats a corporate firewall as the main control that makes those requests safe. Which shift does SC-900 emphasize?",
            choices=[
                (
                    "a",
                    "Treat identity and access context as a primary security perimeter rather than relying on a castle-and-moat network",
                ),
                ("b", "Assume any request from a coffee-shop Wi-Fi is trusted if it uses HTTPS"),
                ("c", "Replace identity verification with Azure Bastion for all SaaS apps"),
                ("d", "Move all access decisions into records management"),
            ],
            correct="a",
            explanation="Cloud access from many networks makes identity the primary perimeter. A corporate firewall alone cannot attest who is requesting SaaS access.",
            source_id="module-describe-identity-principles-concepts",
            semantic_family_id="zero_trust_and_identity_perimeter",
            tested_decision="identity_perimeter_replaces_castle_and_moat",
            misconception_target="firewall_still_primary_cloud_perimeter",
            batch=b,
        ),
        question_record(
            serial=207,
            leaf="identity_providers",
            difficulty="intermediate",
            stem_style="short_scenario",
            stem="A SaaS app is configured to trust Microsoft Entra ID and no longer stores user passwords itself. What is Entra ID acting as for that app?",
            choices=[
                ("a", "An identity provider that authenticates users and issues trusted tokens or claims"),
                ("b", "A data loss prevention engine that blocks outbound credit-card numbers"),
                ("c", "A SIEM that correlates firewall logs"),
                ("d", "A records-management service that declares contracts as records"),
            ],
            correct="a",
            explanation="An identity provider authenticates users and issues claims that apps trust, so the app does not need a local password store.",
            source_id="module-describe-identity-principles-concepts",
            semantic_family_id="federation_and_identity_providers",
            tested_decision="idp_issues_tokens_instead_of_app_passwords",
            batch=b,
        ),
        question_record(
            serial=208,
            leaf="federation",
            difficulty="intermediate",
            stem_style="concept_distinction",
            stem="A partner organization authenticates its own employees, then those users access your app through a trust relationship. Which concept is that, and why is it not multifactor authentication?",
            choices=[
                (
                    "a",
                    "Federation establishes identity trust and claim exchange between organizations; MFA is a factor-strength requirement during authentication",
                ),
                ("b", "Federation is Microsoft's name for requiring two authentication factors"),
                ("c", "Federation replaces authorization while MFA replaces authentication"),
                ("d", "Federation is a Purview audit log, and MFA is a retention label"),
            ],
            correct="a",
            explanation="Federation is an identity-trust relationship that can accept claims from a partner identity provider. MFA is about using more than one authentication factor, not about org-to-org trust.",
            source_id="module-describe-identity-principles-concepts",
            semantic_family_id="federation_and_identity_providers",
            tested_decision="federation_trust_is_not_mfa",
            misconception_target="federation_means_mfa",
            batch=b,
        ),
        question_record(
            serial=209,
            leaf="directory_services_active_directory",
            difficulty="intermediate",
            stem_style="misconception_correction",
            stem="A learner says Active Directory Domain Services is simply another name for Microsoft Entra ID in the cloud. Which correction is accurate?",
            choices=[
                (
                    "a",
                    "AD DS is the traditional on-premises directory service; Entra ID is Microsoft's cloud identity service and they are not the same thing",
                ),
                ("b", "AD DS is only a Conditional Access grant control"),
                ("c", "Entra ID exists only to host Azure Firewall policies"),
                ("d", "AD DS and Entra ID are both names for Microsoft Defender for Identity"),
            ],
            correct="a",
            explanation="AD DS remains the on-premises directory. Entra ID is the cloud identity platform. Hybrid identity can connect them, but the services are distinct.",
            source_id="module-describe-identity-principles-concepts",
            semantic_family_id="entra_hybrid_identity_and_ad",
            tested_decision="ad_ds_is_not_another_name_for_entra",
            misconception_target="ad_ds_equals_entra_id",
            batch=b,
        ),
        question_record(
            serial=210,
            leaf="encryption_and_hashing",
            difficulty="intermediate",
            stem_style="concept_distinction",
            stem="A team must protect customer records while they travel between a browser and a web app. Which cryptographic control is designed for that state of data?",
            choices=[
                ("a", "Encryption in transit, such as TLS, to protect data as it moves across the network"),
                ("b", "Hashing the records so authorized users can decrypt them later"),
                ("c", "A retention label that encrypts packets at the NSG"),
                ("d", "Privileged Identity Management, which encrypts HTTP bodies"),
            ],
            correct="a",
            explanation="Data in transit is protected with encryption such as TLS. Hashing is one-way and not a decryptable transport control, and PIM or retention labels are not packet encryption.",
            source_id="doc-encryption-azure",
            semantic_family_id="encryption_and_hashing",
            tested_decision="tls_encryption_in_transit",
            misconception_target="hashing_decrypts_in_transit",
            batch=b,
        ),
        question_record(
            serial=211,
            leaf="encryption_and_hashing",
            difficulty="intermediate",
            stem_style="distinction_comparison",
            stem="Which statement correctly contrasts encryption with hashing?",
            choices=[
                (
                    "a",
                    "Encryption is designed to be reversed with the correct key; hashing is a one-way fingerprint that should not be decrypted",
                ),
                ("b", "Hashing hides contents for later decryption, while encryption can never be reversed"),
                ("c", "Encryption and hashing are both names for Conditional Access grant controls"),
                ("d", "Hashing is only used to activate privileged roles in PIM"),
            ],
            correct="a",
            explanation="Encryption supports confidentiality and is reversible with authorized keys. Hashing produces a one-way digest used for integrity, not decryption.",
            source_id="module-describe-security-concepts-methodologies",
            semantic_family_id="encryption_and_hashing",
            tested_decision="encryption_reversible_hashing_one_way",
            misconception_target="hashing_is_decryptable",
            batch=b,
        ),
        question_record(
            serial=212,
            leaf="grc_concepts",
            difficulty="intermediate",
            stem_style="concept_distinction",
            stem="Leadership writes acceptable-use rules, a risk team estimates likely impact of a ransomware event, and auditors later check whether those rules were followed. Which mapping is accurate?",
            choices=[
                ("a", "Governance sets direction, risk assesses uncertainty, and compliance checks adherence"),
                (
                    "b",
                    "Governance is only Microsoft Defender for Endpoint, risk is only Azure WAF, and compliance is only NSGs",
                ),
                ("c", "Risk management replaces the need for any compliance evidence"),
                ("d", "Compliance is the product name for Microsoft Sentinel playbooks"),
            ],
            correct="a",
            explanation="GRC separates oversight and policy (governance), uncertainty analysis (risk), and demonstrated adherence (compliance). They are not individual Microsoft security products.",
            source_id="module-describe-security-concepts-methodologies",
            semantic_family_id="grc_concepts",
            tested_decision="grc_governance_risk_compliance_roles",
            batch=b,
        ),
        question_record(
            serial=213,
            leaf="defense_in_depth",
            difficulty="intermediate",
            stem_style="short_scenario",
            stem="An attacker bypasses a network control but is still stopped by identity MFA and by encryption on the data store. Which security model does that outcome illustrate?",
            choices=[
                ("a", "Defense-in-depth, because remaining independent layers still contained the failure"),
                ("b", "A single-perimeter design that depends only on the network control"),
                ("c", "Federation, because MFA is a partner identity-trust relationship"),
                ("d", "Records management, because encryption declares a file as a record"),
            ],
            correct="a",
            explanation="Defense-in-depth expects layers such as identity and data protection to continue working when one layer fails. A single network control would not have stopped the attacker.",
            source_id="module-describe-security-concepts-methodologies",
            semantic_family_id="defense_in_depth",
            tested_decision="failed_layer_contained_by_remaining_layers",
            misconception_target="one_failed_control_means_total_compromise",
            batch=b,
        ),
        question_record(
            serial=214,
            leaf="shared_responsibility_model",
            difficulty="intermediate",
            stem_style="multi_select",
            stem="In Microsoft's shared responsibility model, which two duties remain with the customer across IaaS, PaaS, and SaaS? (Choose two.)",
            choices=[
                ("a", "Protecting customer data"),
                ("b", "Managing identities and access to that data"),
                ("c", "Physically securing Microsoft datacenter buildings"),
                ("d", "Operating the underlying public-cloud host hardware"),
            ],
            correct=["a", "b"],
            explanation="Customers retain data, identities, and access responsibilities in every cloud model. Physical datacenters and host hardware in the public cloud remain Microsoft's.",
            source_id="doc-shared-responsibility",
            semantic_family_id="shared_responsibility_model",
            tested_decision="customer_always_owns_data_and_identities",
            misconception_target="saas_transfers_data_ownership",
            qtype="multi_select",
            batch=b,
        ),
        question_record(
            serial=215,
            leaf="shared_responsibility_model",
            difficulty="intermediate",
            stem_style="responsibility_governance",
            stem="An organization uses Azure virtual machines in Microsoft's public cloud. Who is typically responsible for physically protecting the datacenter and replacing failed host hardware?",
            choices=[
                ("a", "Microsoft, as the cloud provider of the physical facility and host infrastructure"),
                ("b", "The customer, because IaaS transfers datacenter physical security to every tenant"),
                ("c", "The customer's ISP, which becomes the datacenter operator"),
                ("d", "Microsoft Purview eDiscovery, which physically guards racks"),
            ],
            correct="a",
            explanation="In public cloud IaaS, Microsoft still operates physical facilities and host hardware. The customer remains responsible for the guest OS, identities, and data.",
            source_id="doc-shared-responsibility",
            semantic_family_id="shared_responsibility_model",
            tested_decision="public_cloud_physical_host_is_microsoft",
            misconception_target="iaas_customer_owns_datacenter_buildings",
            batch=b,
        ),
        question_record(
            serial=216,
            leaf="grc_concepts",
            difficulty="intermediate",
            stem_style="short_scenario",
            stem="A regulator asks whether the company followed its stated retention and access policies. Which GRC activity is that request primarily about?",
            choices=[
                ("a", "Compliance: demonstrating that required policies and controls were actually followed"),
                ("b", "Only threat hunting in Microsoft Sentinel"),
                ("c", "Only issuing a Temporary Access Pass"),
                ("d", "Only creating an Azure virtual network"),
            ],
            correct="a",
            explanation="Compliance is about showing adherence to obligations and internal policy. Hunting, TAP, and VNets are security or identity capabilities, not the GRC compliance activity itself.",
            source_id="module-describe-security-concepts-methodologies",
            semantic_family_id="grc_concepts",
            tested_decision="compliance_demonstrates_policy_adherence",
            batch=b,
        ),
        question_record(
            serial=217,
            leaf="entra_id_overview",
            difficulty="intermediate",
            stem_style="direct_concept",
            stem="Which statement best describes a Microsoft Entra tenant in SC-900 terms?",
            choices=[
                (
                    "a",
                    "A dedicated cloud identity boundary that represents an organization and holds its directory objects",
                ),
                ("b", "A DDoS mitigation policy attached to a public IP"),
                ("c", "A Purview retention label that encrypts packets"),
                ("d", "A Sentinel playbook that replaces the need for identities"),
            ],
            correct="a",
            explanation="An Entra tenant is the organization's cloud directory boundary for users, apps, and related identity objects. It is not a network, retention, or SIEM control.",
            source_id="doc-entra-what-is",
            semantic_family_id="entra_hybrid_identity_and_ad",
            tested_decision="entra_tenant_is_org_identity_boundary",
            batch=b,
        ),
        question_record(
            serial=218,
            leaf="identity_types_including_agent_id",
            difficulty="intermediate",
            stem_style="short_scenario",
            stem="A supplier's employees must sign in to a procurement app without being created as full internal staff. Which Entra identity approach fits that need?",
            choices=[
                ("a", "External or guest identities for partner and customer collaboration"),
                ("b", "Replacing the app with Azure Key Vault so no sign-in is required"),
                ("c", "Declaring each supplier employee as a retention label"),
                ("d", "Using Microsoft Defender Vulnerability Management as the identity type"),
            ],
            correct="a",
            explanation="External/guest identities let partners or customers authenticate without becoming full internal employees. Key Vault, retention labels, and vulnerability management are not identity types.",
            source_id="module-explore-basic-services-identity-types",
            semantic_family_id="identity_types_including_agent_id",
            tested_decision="external_guest_identities_for_partners",
            batch=b,
        ),
        question_record(
            serial=219,
            leaf="hybrid_identity",
            difficulty="intermediate",
            stem_style="capability_selection",
            stem="An organization keeps on-premises Active Directory and needs those accounts available in Microsoft Entra ID. Which component is the usual synchronization engine for that hybrid identity?",
            choices=[
                ("a", "Microsoft Entra Connect, which synchronizes on-premises identities to Entra ID"),
                ("b", "Azure Web Application Firewall, which copies users during HTTP inspection"),
                ("c", "Microsoft Purview Content explorer, which syncs directory objects"),
                ("d", "Azure Bastion, which replicates passwords over RDP"),
            ],
            correct="a",
            explanation="Entra Connect (and related hybrid identity tooling) synchronizes on-premises AD identities to Entra ID. WAF, Content explorer, and Bastion do not perform directory sync.",
            source_id="doc-hybrid-identity",
            semantic_family_id="entra_hybrid_identity_and_ad",
            tested_decision="entra_connect_syncs_hybrid_identity",
            batch=b,
        ),
        question_record(
            serial=220,
            leaf="hybrid_identity",
            difficulty="intermediate",
            stem_style="concept_distinction",
            stem="Which statement correctly distinguishes password hash synchronization from pass-through authentication in hybrid identity?",
            choices=[
                (
                    "a",
                    "Password hash synchronization authenticates in the cloud using hashed secrets; pass-through authentication validates passwords against on-premises Active Directory",
                ),
                (
                    "b",
                    "Pass-through authentication stores plaintext passwords in Entra ID while hash sync disables hybrid identity",
                ),
                ("c", "Both methods are Azure Firewall FQDN rules rather than authentication paths"),
                (
                    "d",
                    "Password hash synchronization is a Defender XDR workload, and pass-through authentication is a sensitivity label",
                ),
            ],
            correct="a",
            explanation="PHS enables cloud authentication with hashed password material. PTA sends the validation to on-premises AD. Neither is a firewall or XDR control.",
            source_id="doc-hybrid-identity",
            semantic_family_id="entra_hybrid_identity_and_ad",
            tested_decision="phs_cloud_auth_vs_pta_onprem_validation",
            batch=b,
        ),
        question_record(
            serial=221,
            leaf="multifactor_authentication",
            difficulty="intermediate",
            stem_style="concept_distinction",
            stem="A company wants users to sign in with FIDO2 security keys and Microsoft Authenticator without typing a password. How does that relate to MFA?",
            choices=[
                (
                    "a",
                    "Passwordless methods can still satisfy strong multifactor or phishing-resistant authentication without using a password as a factor",
                ),
                ("b", "Passwordless sign-in is the same as disabling MFA permanently"),
                ("c", "FIDO2 keys are retention labels and cannot participate in authentication"),
                ("d", "Authenticator without a password is only a Service Trust Portal offering"),
            ],
            correct="a",
            explanation="Passwordless methods such as FIDO2 and Authenticator still use strong factors. They are not a way to turn MFA off, and they are not compliance-portal artifacts.",
            source_id="doc-mfa",
            semantic_family_id="multifactor_authentication",
            tested_decision="passwordless_can_satisfy_strong_mfa",
            misconception_target="passwordless_means_no_mfa",
            batch=b,
        ),
        question_record(
            serial=222,
            leaf="password_protection_management",
            difficulty="intermediate",
            stem_style="concept_distinction",
            stem="Helpdesk wants users to reset forgotten passwords themselves after extra verification. Security also wants to block passwords that contain the company name. Which pairing is accurate?",
            choices=[
                (
                    "a",
                    "Self-service password reset addresses forgotten-password recovery; password protection bans weak or custom banned terms",
                ),
                (
                    "b",
                    "Self-service password reset is the banned-password dictionary, and password protection is eDiscovery hold",
                ),
                ("c", "Both needs are met only by Azure DDoS Protection"),
                ("d", "Password protection recertifies guest group membership, while SSPR is a WAF policy"),
            ],
            correct="a",
            explanation="SSPR is recovery after the user proves alternative authentication. Password protection blocks globally banned and custom weak terms. They are related password capabilities, not the same control.",
            source_id="doc-sspr",
            semantic_family_id="password_protection_management",
            tested_decision="sspr_recovery_vs_banned_password_protection",
            batch=b,
        ),
        question_record(
            serial=223,
            leaf="conditional_access",
            difficulty="intermediate",
            stem_style="short_scenario",
            stem="Finance users may open a payroll app from the headquarters network without extra MFA, but the same users must complete MFA from any other network. Which Conditional Access signal supports that difference?",
            choices=[
                ("a", "Named or trusted network locations used as a condition in the policy"),
                ("b", "A retention label that changes based on the user's GPS coordinates"),
                ("c", "Azure Bastion, which classifies every public IP as trusted"),
                ("d", "Insider Risk Management, which is the grant control for named locations"),
            ],
            correct="a",
            explanation="Conditional Access can use named or trusted locations as a condition and then require MFA or allow access. Retention labels, Bastion, and Insider Risk Management do not supply that location signal.",
            source_id="doc-conditional-access",
            semantic_family_id="conditional_access_and_identity_protection",
            tested_decision="ca_named_location_as_condition_signal",
            batch=b,
        ),
        question_record(
            serial=224,
            leaf="entra_id_protection",
            difficulty="intermediate",
            stem_style="concept_distinction",
            stem="Microsoft Entra ID Protection flags one account because leaked credentials appeared in a dump, and flags another sign-in because it came from an anonymized IP. Which distinction is accurate?",
            choices=[
                (
                    "a",
                    "User risk describes the user/account, while sign-in risk describes a specific authentication attempt",
                ),
                ("b", "User risk and sign-in risk are both names for Azure Firewall application rules"),
                ("c", "Sign-in risk is only used by Purview records management"),
                ("d", "User risk replaces Conditional Access and cannot be used as a policy condition"),
            ],
            correct="a",
            explanation="ID Protection separates user risk (the identity) from sign-in risk (the attempt). Those signals can feed Conditional Access; they are not firewall or records controls.",
            source_id="doc-id-protection",
            semantic_family_id="conditional_access_and_identity_protection",
            tested_decision="user_risk_vs_signin_risk",
            batch=b,
        ),
        question_record(
            serial=225,
            leaf="privileged_identity_management",
            difficulty="intermediate",
            stem_style="short_scenario",
            stem="When an engineer activates an eligible privileged role, security wants an extra MFA prompt and a written justification before the role becomes active. Which PIM capability is that?",
            choices=[
                ("a", "Activation settings that can require multifactor authentication and justification"),
                ("b", "A retention policy that expires admin tokens after 90 days of SharePoint inactivity"),
                ("c", "Azure Web Application Firewall, which approves directory roles"),
                ("d", "Content explorer filtering, which is required to activate Entra roles"),
            ],
            correct="a",
            explanation="PIM activation can demand extra authentication, justification, and related checks before a privileged role becomes active. Retention, WAF, and Content explorer do not control Entra role activation.",
            source_id="doc-pim",
            semantic_family_id="privileged_identity_management",
            tested_decision="pim_activation_requires_mfa_and_justification",
            misconception_target="eligible_role_activates_with_no_checks",
            batch=b,
        ),
    ]
