"""Compact SC-900 knowledge units grounded in the frozen Microsoft inventory."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from ingestion.models import load_taxonomy
from tools.validate_sc900_microsoft_corpus import INVENTORY_PATH, KNOWLEDGE_UNITS_PATH, load_json

RETRIEVED_AT = "2026-09-12T18:30:00+00:00"

# leaf_id, concept, claim, source_id, locator, opportunities, family, authority_level
UNIT_SPECS: tuple[tuple[str, str, str, str, str, tuple[str, ...], str, str], ...] = (
    (
        "shared_responsibility_model",
        "definition",
        "The shared responsibility model splits security duties between Microsoft and the customer; the customer always retains responsibility for data, identities, and access.",
        "module-describe-security-concepts-methodologies",
        "describe-shared-responsibility-model",
        ("definition", "responsibility"),
        "shared_responsibility_model",
        "module",
    ),
    (
        "shared_responsibility_model",
        "saas_shift",
        "As a workload moves toward SaaS, the provider takes more infrastructure and platform duties while the customer still governs users, data, and configuration.",
        "doc-shared-responsibility",
        "saas-vs-iaas",
        ("responsibility", "scenario_application"),
        "shared_responsibility_model",
        "product_documentation",
    ),
    (
        "shared_responsibility_model",
        "misconception",
        "Choosing a cloud service does not transfer every security duty to Microsoft; customer configuration and identity hygiene remain in scope.",
        "module-describe-security-concepts-methodologies",
        "describe-shared-responsibility-model",
        ("misconception_correction",),
        "shared_responsibility_model",
        "module",
    ),
    (
        "defense_in_depth",
        "definition",
        "Defense-in-depth uses multiple independent control layers so one failed control does not expose the whole environment.",
        "module-describe-security-concepts-methodologies",
        "describe-defense-depth",
        ("definition", "security_control_matching"),
        "defense_in_depth",
        "module",
    ),
    (
        "defense_in_depth",
        "purpose",
        "Layered controls such as physical, identity, network, compute, and data protection reduce single-point-of-failure risk.",
        "module-describe-security-concepts-methodologies",
        "describe-defense-depth",
        ("purpose",),
        "defense_in_depth",
        "module",
    ),
    (
        "zero_trust_model",
        "definition",
        "Zero Trust assumes breach and verifies explicitly rather than trusting a user or device because it is on a corporate network.",
        "doc-zero-trust-overview",
        "overview",
        ("definition",),
        "zero_trust_and_identity_perimeter",
        "product_documentation",
    ),
    (
        "zero_trust_model",
        "principles",
        "Core Zero Trust principles include verify explicitly, use least privilege, and assume breach.",
        "module-describe-security-concepts-methodologies",
        "describe-zero-trust-methodology",
        ("purpose", "misconception_correction"),
        "zero_trust_and_identity_perimeter",
        "module",
    ),
    (
        "encryption_and_hashing",
        "encryption_purpose",
        "Encryption transforms readable data into ciphertext so unauthorized parties cannot understand it without the key.",
        "module-describe-security-concepts-methodologies",
        "describe-ways-encryption,-hashing,-signing-can-secure-your-data",
        ("definition", "distinction"),
        "encryption_and_hashing",
        "module",
    ),
    (
        "encryption_and_hashing",
        "hashing_distinction",
        "Hashing creates a one-way fingerprint used to detect tampering; unlike encryption it is not designed to be reversed to the original data.",
        "doc-encryption-azure",
        "hashing-vs-encryption",
        ("concept_distinction",),
        "encryption_and_hashing",
        "product_documentation",
    ),
    (
        "grc_concepts",
        "definition",
        "Governance, risk, and compliance (GRC) is the organizational system for setting policy, understanding risk, and meeting regulatory obligations.",
        "module-describe-security-concepts-methodologies",
        "describe-compliance-concepts",
        ("definition",),
        "grc_concepts",
        "module",
    ),
    (
        "grc_concepts",
        "governance_vs_compliance",
        "Governance sets the rules an organization chooses to follow; compliance measures whether those rules and external regulations are met.",
        "module-describe-security-concepts-methodologies",
        "describe-compliance-concepts",
        ("concept_distinction",),
        "grc_concepts",
        "module",
    ),
    (
        "identity_primary_security_perimeter",
        "definition",
        "In cloud environments identity is treated as a primary security perimeter because users connect from many networks, not one trusted office LAN.",
        "module-describe-identity-principles-concepts",
        "define-identity-as-primary-security-perimeter",
        ("definition",),
        "zero_trust_and_identity_perimeter",
        "module",
    ),
    (
        "identity_primary_security_perimeter",
        "implication",
        "Access decisions should depend on verified identity and context rather than assuming a request is safe because it came from an internal IP address.",
        "module-describe-identity-principles-concepts",
        "define-identity-as-primary-security-perimeter",
        ("scenario_application",),
        "zero_trust_and_identity_perimeter",
        "module",
    ),
    (
        "authentication",
        "definition",
        "Authentication proves who an identity is, typically by validating credentials or authentication factors.",
        "module-describe-identity-principles-concepts",
        "define-authentication-and-authorization",
        ("definition",),
        "authentication_vs_authorization",
        "module",
    ),
    (
        "authentication",
        "order",
        "Authentication happens before authorization: the system first verifies the identity, then decides what that identity may do.",
        "module-describe-identity-principles-concepts",
        "define-authentication-and-authorization",
        ("concept_distinction",),
        "authentication_vs_authorization",
        "module",
    ),
    (
        "authorization",
        "definition",
        "Authorization determines what an authenticated identity is allowed to access or perform.",
        "module-describe-identity-principles-concepts",
        "define-authentication-and-authorization",
        ("definition",),
        "authentication_vs_authorization",
        "module",
    ),
    (
        "authorization",
        "misconception",
        "A successful sign-in does not by itself grant every permission; authorization still evaluates roles, policies, and resource rights.",
        "module-describe-identity-principles-concepts",
        "define-authentication-and-authorization",
        ("misconception_correction",),
        "authentication_vs_authorization",
        "module",
    ),
    (
        "identity_providers",
        "definition",
        "An identity provider authenticates users and issues identity claims that applications can trust instead of storing every password locally.",
        "module-describe-identity-principles-concepts",
        "describe-modern-authentication-role-identity-provider",
        ("definition", "purpose"),
        "federation_and_identity_providers",
        "module",
    ),
    (
        "identity_providers",
        "sso",
        "Using a common identity provider enables single sign-on so a user authenticates once and reaches multiple trusted applications.",
        "module-describe-identity-principles-concepts",
        "describe-modern-authentication-role-identity-provider",
        ("purpose",),
        "federation_and_identity_providers",
        "module",
    ),
    (
        "directory_services_active_directory",
        "definition",
        "A directory service stores and organizes identities, groups, and related objects so they can be authenticated and authorized.",
        "module-describe-identity-principles-concepts",
        "describe-concept-of-directory-services-active-directory",
        ("definition",),
        "entra_hybrid_identity_and_ad",
        "module",
    ),
    (
        "directory_services_active_directory",
        "ad_ds",
        "Active Directory Domain Services is the traditional on-premises directory used for domain-joined Windows identities and Group Policy.",
        "module-describe-identity-principles-concepts",
        "describe-concept-of-directory-services-active-directory",
        ("service_selection",),
        "entra_hybrid_identity_and_ad",
        "module",
    ),
    (
        "federation",
        "definition",
        "Federation establishes a trust relationship so one organization can accept identities authenticated by another identity provider.",
        "module-describe-identity-principles-concepts",
        "describe-concept-federated-services",
        ("definition",),
        "federation_and_identity_providers",
        "module",
    ),
    (
        "federation",
        "use_case",
        "Federation is used when partners need to access resources without creating and managing a separate local username for every external user.",
        "module-describe-identity-principles-concepts",
        "describe-concept-federated-services",
        ("scenario_application",),
        "federation_and_identity_providers",
        "module",
    ),
    (
        "entra_id_overview",
        "definition",
        "Microsoft Entra ID is Microsoft's cloud identity and access management service for users, apps, and resources.",
        "module-explore-basic-services-identity-types",
        "describe-microsoft-entra",
        ("definition",),
        "entra_hybrid_identity_and_ad",
        "module",
    ),
    (
        "entra_id_overview",
        "purpose",
        "Entra ID authenticates identities and helps control access to Microsoft cloud services and integrated applications.",
        "doc-entra-what-is",
        "overview",
        ("purpose",),
        "entra_hybrid_identity_and_ad",
        "product_documentation",
    ),
    (
        "identity_types_including_agent_id",
        "user_app_device",
        "Entra ID supports human users, workload/application identities, and device identities as distinct identity types.",
        "module-explore-basic-services-identity-types",
        "describe-identity-types",
        ("definition",),
        "identity_types_including_agent_id",
        "module",
    ),
    (
        "identity_types_including_agent_id",
        "agent_id",
        "Agent ID is a current Entra identity type for AI agents so those agents can be authenticated, authorized, and governed rather than acting as unmanaged scripts.",
        "module-explore-basic-services-identity-types",
        "describe-microsoft-entra-agent-id",
        ("definition", "current_topic"),
        "identity_types_including_agent_id",
        "module",
    ),
    (
        "identity_types_including_agent_id",
        "external",
        "External identities let partners or customers authenticate to apps without becoming full internal employees in the directory.",
        "module-explore-basic-services-identity-types",
        "describe-external-identities",
        ("service_selection",),
        "identity_types_including_agent_id",
        "module",
    ),
    (
        "hybrid_identity",
        "definition",
        "Hybrid identity connects an on-premises directory with Entra ID so users can use one identity across cloud and on-premises resources.",
        "doc-hybrid-identity",
        "overview",
        ("definition",),
        "entra_hybrid_identity_and_ad",
        "product_documentation",
    ),
    (
        "hybrid_identity",
        "purpose",
        "Organizations adopt hybrid identity to keep on-premises Active Directory while enabling cloud authentication and Microsoft 365 access.",
        "module-explore-basic-services-identity-types",
        "describe-concept-of-hybrid-identities",
        ("purpose", "scenario_application"),
        "entra_hybrid_identity_and_ad",
        "module",
    ),
    (
        "authentication_methods",
        "range",
        "Entra ID authentication methods include passwords, Microsoft Authenticator, Windows Hello, FIDO2/passkeys, certificates, and Temporary Access Pass.",
        "doc-authentication-methods",
        "methods",
        ("definition",),
        "authentication_methods",
        "product_documentation",
    ),
    (
        "authentication_methods",
        "tap",
        "Temporary Access Pass is a time-limited passcode used to bootstrap passwordless method registration, not a standing privileged role.",
        "doc-temporary-access-pass",
        "tap",
        ("scenario_application",),
        "authentication_methods",
        "product_documentation",
    ),
    (
        "multifactor_authentication",
        "definition",
        "MFA requires more than one authentication factor, combining categories such as something you know, have, or are.",
        "doc-mfa",
        "how-it-works",
        ("definition",),
        "multifactor_authentication",
        "product_documentation",
    ),
    (
        "multifactor_authentication",
        "purpose",
        "MFA reduces the risk that a stolen password alone can sign in to an account.",
        "module-explore-authentication-capabilities",
        "describe-multi-factor-authentication-mfa",
        ("purpose",),
        "multifactor_authentication",
        "module",
    ),
    (
        "password_protection_management",
        "banned_passwords",
        "Microsoft Entra Password Protection blocks known weak and banned passwords, including custom banned terms an organization adds.",
        "doc-password-protection",
        "banned-passwords",
        ("purpose",),
        "password_protection_management",
        "product_documentation",
    ),
    (
        "password_protection_management",
        "sspr",
        "Self-service password reset lets users unlock or reset their own passwords after proving alternative authentication methods.",
        "doc-sspr",
        "sspr",
        ("service_selection",),
        "password_protection_management",
        "product_documentation",
    ),
    (
        "conditional_access",
        "definition",
        "Conditional Access evaluates signals such as user, device, location, and risk, then applies allow, block, or additional-control decisions.",
        "doc-conditional-access",
        "overview",
        ("definition",),
        "conditional_access_and_identity_protection",
        "product_documentation",
    ),
    (
        "conditional_access",
        "if_then",
        "A Conditional Access policy is an if-then statement: if conditions match, then require MFA, block access, or demand a compliant device.",
        "module-explore-access-management-capabilities",
        "describe-conditional-access-its-benefits",
        ("purpose", "scenario_application"),
        "conditional_access_and_identity_protection",
        "module",
    ),
    (
        "entra_roles_rbac",
        "definition",
        "Microsoft Entra roles are RBAC assignments that grant directory and identity-administration permissions, distinct from Azure resource RBAC.",
        "doc-entra-rbac",
        "overview",
        ("definition", "distinction"),
        "entra_roles_rbac",
        "product_documentation",
    ),
    (
        "entra_roles_rbac",
        "least_privilege",
        "Entra RBAC supports least privilege by assigning only the directory role needed instead of making every admin a Global Administrator.",
        "module-explore-access-management-capabilities",
        "describe-azure-role-based-access-control-rbac",
        ("governance",),
        "entra_roles_rbac",
        "module",
    ),
    (
        "entra_id_governance",
        "definition",
        "Microsoft Entra ID Governance manages identity lifecycle and access over time, including entitlement management, access reviews, and lifecycle workflows.",
        "doc-id-governance",
        "overview",
        ("definition",),
        "entra_id_governance_and_access_reviews",
        "product_documentation",
    ),
    (
        "entra_id_governance",
        "lifecycle_workflows",
        "Lifecycle Workflows automate joiner, mover, and leaver tasks such as provisioning or disabling access when employment status changes.",
        "doc-lifecycle-workflows",
        "overview",
        ("scenario_application",),
        "entra_id_governance_and_access_reviews",
        "product_documentation",
    ),
    (
        "access_reviews",
        "definition",
        "Access reviews periodically recertify whether users still need group, app, or role access and can revoke stale access.",
        "doc-access-reviews",
        "overview",
        ("definition",),
        "entra_id_governance_and_access_reviews",
        "product_documentation",
    ),
    (
        "access_reviews",
        "distinction",
        "Access reviews recertify existing access; they do not replace Conditional Access session controls or PIM just-in-time elevation.",
        "module-describe-identity-protection-governance-capabilities",
        "describe-what-is-entitlement-management-access-reviews",
        ("concept_distinction",),
        "entra_id_governance_and_access_reviews",
        "module",
    ),
    (
        "privileged_identity_management",
        "definition",
        "Privileged Identity Management provides just-in-time, time-bound, and approval-based activation of privileged Entra and Azure roles.",
        "doc-pim",
        "overview",
        ("definition",),
        "privileged_identity_management",
        "product_documentation",
    ),
    (
        "privileged_identity_management",
        "standing_admin",
        "PIM is used to avoid standing permanent admin rights by requiring activation when privileged work is needed.",
        "module-describe-identity-protection-governance-capabilities",
        "describe-privileged-identity-management",
        ("scenario_application",),
        "privileged_identity_management",
        "module",
    ),
    (
        "entra_id_protection",
        "definition",
        "Microsoft Entra ID Protection detects identity-based risks such as leaked credentials or atypical sign-ins and can feed those signals into access decisions.",
        "doc-id-protection",
        "overview",
        ("definition",),
        "conditional_access_and_identity_protection",
        "product_documentation",
    ),
    (
        "entra_id_protection",
        "purpose",
        "ID Protection is the risk-detection capability; Conditional Access is commonly used to require controls when that risk is raised.",
        "module-describe-identity-protection-governance-capabilities",
        "describe-azure",
        ("concept_distinction",),
        "conditional_access_and_identity_protection",
        "module",
    ),
    (
        "azure_ddos_protection",
        "definition",
        "Azure DDoS Protection helps absorb and mitigate volumetric network-layer denial-of-service attacks against public Azure resources.",
        "doc-ddos",
        "overview",
        ("definition",),
        "azure_nsg_firewall_waf_ddos",
        "product_documentation",
    ),
    (
        "azure_ddos_protection",
        "layer",
        "DDoS Protection is aimed at network/transport flooding, not at inspecting HTTP application payloads the way WAF does.",
        "module-describe-basic-security-capabilities-azure",
        "describe-azure-ddos-protection",
        ("concept_distinction",),
        "azure_nsg_firewall_waf_ddos",
        "module",
    ),
    (
        "azure_firewall",
        "definition",
        "Azure Firewall is a managed, stateful network firewall for filtering traffic across Azure virtual networks using centrally defined rules.",
        "doc-azure-firewall",
        "overview",
        ("definition",),
        "azure_nsg_firewall_waf_ddos",
        "product_documentation",
    ),
    (
        "azure_firewall",
        "distinction",
        "Azure Firewall operates as a centralized network traffic filter; NSGs are distributed subnet/NIC allow-deny filters and WAF inspects web requests.",
        "module-describe-basic-security-capabilities-azure",
        "describe-what-is-azure-firewall",
        ("concept_distinction",),
        "azure_nsg_firewall_waf_ddos",
        "module",
    ),
    (
        "azure_web_application_firewall",
        "definition",
        "Azure WAF protects web applications from HTTP/HTTPS attacks such as SQL injection and cross-site scripting.",
        "doc-waf",
        "overview",
        ("definition",),
        "azure_nsg_firewall_waf_ddos",
        "product_documentation",
    ),
    (
        "azure_web_application_firewall",
        "layer",
        "WAF is an application-layer control in front of web apps; it is not a replacement for NSGs or DDoS network-layer protection.",
        "module-describe-basic-security-capabilities-azure",
        "describe-what-is-web-application-firewall",
        ("service_selection",),
        "azure_nsg_firewall_waf_ddos",
        "module",
    ),
    (
        "azure_virtual_network_segmentation",
        "definition",
        "Azure virtual networks segment cloud resources into isolated private address spaces and subnets.",
        "doc-vnet",
        "overview",
        ("definition",),
        "azure_virtual_network_segmentation",
        "product_documentation",
    ),
    (
        "azure_virtual_network_segmentation",
        "purpose",
        "Network segmentation limits how workloads communicate so a compromise in one subnet does not automatically reach every resource.",
        "module-describe-basic-security-capabilities-azure",
        "describe-network-segmentation",
        ("purpose",),
        "azure_virtual_network_segmentation",
        "module",
    ),
    (
        "network_security_groups",
        "definition",
        "Network security groups contain inbound and outbound allow/deny rules associated with subnets or network interfaces.",
        "doc-nsg",
        "overview",
        ("definition",),
        "azure_nsg_firewall_waf_ddos",
        "product_documentation",
    ),
    (
        "network_security_groups",
        "scope",
        "NSGs filter traffic at the subnet or NIC; they do not provide centralized fully qualified domain name filtering the way Azure Firewall can.",
        "module-describe-basic-security-capabilities-azure",
        "describe-azure-network-security-groups",
        ("concept_distinction",),
        "azure_nsg_firewall_waf_ddos",
        "module",
    ),
    (
        "azure_bastion",
        "definition",
        "Azure Bastion provides browser-based RDP/SSH to VMs over TLS without exposing those VMs on public RDP/SSH ports.",
        "doc-bastion",
        "overview",
        ("definition",),
        "azure_bastion",
        "product_documentation",
    ),
    (
        "azure_bastion",
        "use_case",
        "Use Bastion when administrators must manage VMs securely without assigning public IPs for remote desktop or SSH.",
        "module-describe-basic-security-capabilities-azure",
        "describe-what-is-azure-bastion",
        ("scenario_application",),
        "azure_bastion",
        "module",
    ),
    (
        "azure_key_vault",
        "definition",
        "Azure Key Vault stores and controls access to secrets, keys, and certificates so applications do not hard-code credentials.",
        "doc-key-vault",
        "basic-concepts",
        ("definition",),
        "azure_key_vault",
        "product_documentation",
    ),
    (
        "azure_key_vault",
        "purpose",
        "Key Vault is the Azure service for managing cryptographic keys and application secrets, not a SIEM or DDoS control.",
        "doc-key-vault",
        "basic-concepts",
        ("service_selection",),
        "azure_key_vault",
        "product_documentation",
    ),
    (
        "microsoft_defender_for_cloud",
        "definition",
        "Microsoft Defender for Cloud is the Cloud Security Posture Management and cloud workload protection service for Azure and connected clouds.",
        "doc-defender-for-cloud",
        "introduction",
        ("definition",),
        "defender_for_cloud_cspm_cwp",
        "product_documentation",
    ),
    (
        "microsoft_defender_for_cloud",
        "secure_score",
        "Defender for Cloud presents recommendations and a secure-score style measurement of cloud security posture.",
        "module-describe-security-management-capabilities-of-azure",
        "describe-&amp;amp;-explore-azure-security-center",
        ("purpose",),
        "defender_for_cloud_cspm_cwp",
        "module",
    ),
    (
        "cloud_security_posture_management",
        "definition",
        "CSPM continuously assesses cloud configurations against security standards and recommends hardening actions.",
        "doc-cspm",
        "overview",
        ("definition",),
        "defender_for_cloud_cspm_cwp",
        "product_documentation",
    ),
    (
        "cloud_security_posture_management",
        "vs_cwp",
        "CSPM focuses on misconfiguration and posture; cloud workload protection adds threat detection and hardening for running workloads.",
        "module-describe-security-management-capabilities-of-azure",
        "describe-cloud-security-posture-management-cspm",
        ("concept_distinction",),
        "defender_for_cloud_cspm_cwp",
        "module",
    ),
    (
        "security_policies_standards_recommendations",
        "definition",
        "Security policies and standards in Defender for Cloud define the desired configuration baseline used to generate recommendations.",
        "module-describe-security-management-capabilities-of-azure",
        "baselines-for-azure",
        ("definition",),
        "defender_for_cloud_cspm_cwp",
        "module",
    ),
    (
        "security_policies_standards_recommendations",
        "purpose",
        "Recommendations tell operators which resources deviate from the assigned standard so they can improve posture and score.",
        "module-describe-security-management-capabilities-of-azure",
        "baselines-for-azure",
        ("purpose",),
        "defender_for_cloud_cspm_cwp",
        "module",
    ),
    (
        "cloud_workload_protection",
        "definition",
        "Cloud workload protection adds enhanced threat detection and security plans for workloads such as servers, containers, and databases.",
        "doc-cwp",
        "workload-protection",
        ("definition",),
        "defender_for_cloud_cspm_cwp",
        "product_documentation",
    ),
    (
        "cloud_workload_protection",
        "use_case",
        "Enable workload protection plans when the organization needs threat detection on running cloud resources, not only configuration scoring.",
        "module-describe-security-management-capabilities-of-azure",
        "describe-benefit-use-cases-defender",
        ("scenario_application",),
        "defender_for_cloud_cspm_cwp",
        "module",
    ),
    (
        "siem_and_soar",
        "siem",
        "A SIEM collects and correlates security logs and alerts so analysts can detect and investigate incidents across sources.",
        "module-describe-security-capabilities-of-azure-sentinel",
        "define-concepts-of-siem,-soar,-xdr",
        ("definition",),
        "sentinel_siem_soar_automation",
        "module",
    ),
    (
        "siem_and_soar",
        "soar",
        "SOAR automates response actions and playbooks so repeated investigation or containment steps can run consistently.",
        "module-describe-security-capabilities-of-azure-sentinel",
        "define-concepts-of-siem,-soar,-xdr",
        ("definition", "distinction"),
        "sentinel_siem_soar_automation",
        "module",
    ),
    (
        "sentinel_threat_detection_mitigation",
        "definition",
        "Microsoft Sentinel is Microsoft's cloud-native SIEM and SOAR service for collecting data, detecting threats, investigating, and automating response.",
        "doc-sentinel",
        "overview",
        ("definition", "service_selection"),
        "sentinel_siem_soar_automation",
        "product_documentation",
    ),
    (
        "sentinel_threat_detection_mitigation",
        "capabilities",
        "Sentinel uses analytics rules, incidents, hunting, and automation/playbooks to detect and mitigate threats across connected data sources.",
        "module-describe-security-capabilities-of-azure-sentinel",
        "describe-role-value-of-sentinel-providing-integrated-threat-protection",
        ("purpose",),
        "sentinel_siem_soar_automation",
        "module",
    ),
    (
        "defender_xdr_services",
        "definition",
        "Microsoft Defender XDR is an extended detection and response suite that correlates signals across endpoints, identities, email, and cloud apps.",
        "doc-defender-xdr",
        "overview",
        ("definition",),
        "defender_xdr_workload_suite",
        "product_documentation",
    ),
    (
        "defender_xdr_services",
        "suite",
        "XDR brings together workload Defender services so incidents can be investigated as one attack rather than isolated product alerts.",
        "module-describe-threat-protection-with-microsoft-365-defender",
        "describe-services",
        ("purpose",),
        "defender_xdr_workload_suite",
        "module",
    ),
    (
        "defender_for_office_365",
        "definition",
        "Microsoft Defender for Office 365 protects email, collaboration, and Office content from phishing, malware, and unsafe attachments or links.",
        "doc-defender-office",
        "overview",
        ("definition", "service_selection"),
        "defender_xdr_workload_suite",
        "product_documentation",
    ),
    (
        "defender_for_office_365",
        "not_endpoint",
        "Defender for Office 365 is not the endpoint agent; device behavioral detection is Defender for Endpoint.",
        "module-describe-threat-protection-with-microsoft-365-defender",
        "describe-microsoft-defender-for-office-365-formerly-office-365-atp",
        ("concept_distinction",),
        "defender_xdr_workload_suite",
        "module",
    ),
    (
        "defender_for_endpoint",
        "definition",
        "Microsoft Defender for Endpoint provides endpoint detection and response, behavioral monitoring, and device threat protection.",
        "doc-defender-endpoint",
        "overview",
        ("definition",),
        "defender_xdr_workload_suite",
        "product_documentation",
    ),
    (
        "defender_for_endpoint",
        "use_case",
        "Use Defender for Endpoint when the requirement is to detect and respond to attacks on workstations, servers, or other endpoints.",
        "module-describe-threat-protection-with-microsoft-365-defender",
        "describe-microsoft-defender-for-endpoint-formerly-microsoft-defender-atp",
        ("scenario_application",),
        "defender_xdr_workload_suite",
        "module",
    ),
    (
        "defender_for_cloud_apps",
        "definition",
        "Microsoft Defender for Cloud Apps is the cloud access security broker that discovers shadow IT and protects SaaS app use.",
        "doc-defender-cloud-apps",
        "overview",
        ("definition",),
        "defender_xdr_workload_suite",
        "product_documentation",
    ),
    (
        "defender_for_cloud_apps",
        "use_case",
        "Choose Defender for Cloud Apps to see which cloud apps are in use and to apply session or app controls to those SaaS services.",
        "module-describe-threat-protection-with-microsoft-365-defender",
        "describe-microsoft-cloud-app-security",
        ("scenario_application",),
        "defender_xdr_workload_suite",
        "module",
    ),
    (
        "defender_for_identity",
        "definition",
        "Microsoft Defender for Identity detects identity-based attacks by analyzing Active Directory signals such as reconnaissance, lateral movement, and credential theft.",
        "doc-defender-identity",
        "overview",
        ("definition",),
        "defender_xdr_workload_suite",
        "product_documentation",
    ),
    (
        "defender_for_identity",
        "use_case",
        "Defender for Identity is the workload control for on-premises directory threats, not the email anti-phishing stack.",
        "module-describe-threat-protection-with-microsoft-365-defender",
        "describe-microsoft-defender-for-identity-formerly-azure-atp",
        ("service_selection",),
        "defender_xdr_workload_suite",
        "module",
    ),
    (
        "defender_vulnerability_management",
        "definition",
        "Microsoft Defender Vulnerability Management discovers, assesses, and helps prioritize software and configuration vulnerabilities.",
        "doc-defender-vulnerability-management",
        "overview",
        ("definition",),
        "defender_xdr_workload_suite",
        "product_documentation",
    ),
    (
        "defender_vulnerability_management",
        "distinction",
        "Vulnerability management prioritizes weaknesses to remediate; it is not itself a SIEM correlation engine.",
        "module-describe-threat-protection-with-microsoft-365-defender",
        "describe-defender-vulnerability-management",
        ("concept_distinction",),
        "defender_xdr_workload_suite",
        "module",
    ),
    (
        "defender_threat_intelligence",
        "definition",
        "Microsoft Defender Threat Intelligence (Defender TI) provides threat-actor, infrastructure, and indicator intelligence to inform investigations.",
        "doc-defender-ti",
        "overview",
        ("definition", "current_topic"),
        "defender_xdr_workload_suite",
        "product_documentation",
    ),
    (
        "defender_threat_intelligence",
        "purpose",
        "Defender TI helps analysts understand who is attacking and which indicators are associated with campaigns, rather than isolating a single mailbox.",
        "module-describe-threat-protection-with-microsoft-365-defender",
        "describe-defender-threat-intelligence",
        ("purpose",),
        "defender_xdr_workload_suite",
        "module",
    ),
    (
        "defender_portal",
        "definition",
        "The Microsoft Defender portal is the unified operations console for Defender XDR incidents, hunting, and related security workflows.",
        "doc-defender-portal",
        "portal",
        ("definition", "current_topic"),
        "defender_xdr_workload_suite",
        "product_documentation",
    ),
    (
        "defender_portal",
        "purpose",
        "Use the Defender portal to investigate cross-product incidents in one place instead of switching among disconnected workload consoles.",
        "module-describe-threat-protection-with-microsoft-365-defender",
        "describe-microsoft-defender-portal",
        ("purpose",),
        "defender_xdr_workload_suite",
        "module",
    ),
    (
        "service_trust_portal_offerings",
        "definition",
        "The Service Trust Portal publishes Microsoft audit reports, compliance documentation, and trust materials customers use to assess Microsoft's controls.",
        "module-describe-compliance-management-capabilities-microsoft",
        "describe-offerings-of-service-trust-portal",
        ("definition",),
        "service_trust_privacy_compliance_manager",
        "module",
    ),
    (
        "service_trust_portal_offerings",
        "use_case",
        "A customer looking for SOC or ISO audit reports about Microsoft's services uses the Service Trust Portal, not Defender for Cloud secure score.",
        "doc-service-trust-portal",
        "offerings",
        ("scenario_application",),
        "service_trust_privacy_compliance_manager",
        "product_documentation",
    ),
    (
        "microsoft_privacy_principles",
        "definition",
        "Microsoft privacy principles describe commitments such as control, transparency, and protection of customer data.",
        "module-describe-compliance-management-capabilities-microsoft",
        "describe-microsofts-privacy-principles",
        ("definition",),
        "service_trust_privacy_compliance_manager",
        "module",
    ),
    (
        "microsoft_privacy_principles",
        "customer_control",
        "Microsoft's privacy approach emphasizes that customers own their data and should retain control over how it is used.",
        "module-describe-compliance-management-capabilities-microsoft",
        "describe-microsofts-privacy-principles",
        ("purpose",),
        "service_trust_privacy_compliance_manager",
        "module",
    ),
    (
        "purview_portal",
        "definition",
        "The Microsoft Purview portal is the unified compliance and data-governance workspace for Purview solutions.",
        "doc-purview-portal",
        "portal",
        ("definition", "current_topic"),
        "purview_portal",
        "product_documentation",
    ),
    (
        "purview_portal",
        "purpose",
        "Administrators use the Purview portal to reach classification, DLP, audit, eDiscovery, and related compliance tools in one experience.",
        "module-describe-purview-data-solutions",
        "introduction",
        ("purpose",),
        "purview_portal",
        "module",
    ),
    (
        "compliance_manager",
        "definition",
        "Compliance Manager helps organizations assess controls, manage improvement actions, and track progress against regulatory templates.",
        "doc-compliance-manager",
        "overview",
        ("definition",),
        "service_trust_privacy_compliance_manager",
        "product_documentation",
    ),
    (
        "compliance_manager",
        "vs_stp",
        "Compliance Manager tracks the customer's control implementation; the Service Trust Portal publishes Microsoft's own audit evidence.",
        "module-describe-purview-risk-compliance-governance",
        "describe-compliance-manager",
        ("concept_distinction",),
        "service_trust_privacy_compliance_manager",
        "module",
    ),
    (
        "compliance_score",
        "definition",
        "Compliance score estimates how well implemented improvement actions cover recommended controls and helps prioritize remaining work.",
        "doc-compliance-score",
        "scoring",
        ("definition",),
        "service_trust_privacy_compliance_manager",
        "product_documentation",
    ),
    (
        "compliance_score",
        "not_secure_score",
        "Compliance score is a compliance-control measurement in Compliance Manager, not Defender for Cloud's secure score for cloud resource posture.",
        "module-explore-plan-compliance-microsoft-365",
        "introduction",
        ("concept_distinction",),
        "service_trust_privacy_compliance_manager",
        "module",
    ),
    (
        "data_classification",
        "definition",
        "Purview data classification finds and categorizes sensitive items using sensitive information types and classifiers.",
        "doc-data-classification",
        "overview",
        ("definition",),
        "purview_information_protection_lifecycle",
        "product_documentation",
    ),
    (
        "data_classification",
        "purpose",
        "Classification answers what sensitive data exists and where it lives so protection and retention controls can be applied.",
        "module-describe-purview-data-solutions",
        "identify-sensitive-data",
        ("purpose",),
        "purview_information_protection_lifecycle",
        "module",
    ),
    (
        "content_and_activity_explorer",
        "content",
        "Content explorer shows where classified items are stored so administrators can inspect what was found.",
        "doc-content-explorer",
        "overview",
        ("definition",),
        "purview_information_protection_lifecycle",
        "product_documentation",
    ),
    (
        "content_and_activity_explorer",
        "activity",
        "Activity explorer shows what is happening to labeled or classified content, such as labeling, sharing, or DLP matches.",
        "doc-activity-explorer",
        "overview",
        ("concept_distinction",),
        "purview_information_protection_lifecycle",
        "product_documentation",
    ),
    (
        "sensitivity_labels_and_policies",
        "definition",
        "Sensitivity labels classify and protect content, and label policies determine which labels are published to which users.",
        "doc-sensitivity-labels",
        "overview",
        ("definition",),
        "purview_information_protection_lifecycle",
        "product_documentation",
    ),
    (
        "sensitivity_labels_and_policies",
        "protection",
        "Labels can apply encryption, markings, and access restrictions as content travels across services.",
        "module-describe-purview-data-solutions",
        "describe-sensitivity-labels-policies",
        ("purpose",),
        "purview_information_protection_lifecycle",
        "module",
    ),
    (
        "data_loss_prevention",
        "definition",
        "DLP policies detect and help prevent unsafe sharing or exfiltration of sensitive information across locations such as Exchange, Teams, SharePoint, and devices.",
        "doc-dlp",
        "overview",
        ("definition",),
        "purview_information_protection_lifecycle",
        "product_documentation",
    ),
    (
        "data_loss_prevention",
        "use_case",
        "Use DLP when the goal is to stop credit-card or health data from being sent outside approved channels, not to recertify group membership.",
        "module-describe-purview-data-solutions",
        "describe-data-loss-prevention",
        ("scenario_application",),
        "purview_information_protection_lifecycle",
        "module",
    ),
    (
        "records_management",
        "definition",
        "Records management declares items as records and applies regulatory retention and disposition requirements that users cannot casually change.",
        "doc-records-management",
        "overview",
        ("definition",),
        "purview_information_protection_lifecycle",
        "product_documentation",
    ),
    (
        "records_management",
        "distinction",
        "A declared record is more restrictive than an ordinary retention label because record status restricts editing and deletion during retention.",
        "module-describe-purview-risk-compliance-governance",
        "describe-records-management",
        ("concept_distinction",),
        "purview_information_protection_lifecycle",
        "module",
    ),
    (
        "retention_policies_labels",
        "definition",
        "Retention policies and retention labels keep or delete content for a defined period to meet legal or business keep/delete requirements.",
        "doc-retention",
        "overview",
        ("definition",),
        "purview_information_protection_lifecycle",
        "product_documentation",
    ),
    (
        "retention_policies_labels",
        "policy_vs_label",
        "A retention policy applies broadly to a location; a retention label can be applied to individual items, including by users or auto-labeling.",
        "module-describe-purview-risk-compliance-governance",
        "describe-data-lifecycle-management",
        ("concept_distinction",),
        "purview_information_protection_lifecycle",
        "module",
    ),
    (
        "insider_risk_management",
        "definition",
        "Insider Risk Management identifies potentially risky user activities inside the organization while using privacy controls for investigators.",
        "doc-insider-risk",
        "overview",
        ("definition",),
        "purview_audit_ediscovery_insider_risk",
        "product_documentation",
    ),
    (
        "insider_risk_management",
        "use_case",
        "Use Insider Risk Management for data theft, leak, or policy-violation patterns by employees, not for mailbox malware scanning.",
        "module-describe-purview-data-solutions",
        "describe-insider-risk-management",
        ("scenario_application",),
        "purview_audit_ediscovery_insider_risk",
        "module",
    ),
    (
        "ediscovery",
        "definition",
        "Microsoft Purview eDiscovery finds, holds, and exports content needed for legal or investigative matters.",
        "doc-ediscovery",
        "overview",
        ("definition",),
        "purview_audit_ediscovery_insider_risk",
        "product_documentation",
    ),
    (
        "ediscovery",
        "use_case",
        "Legal hold and collection of email or files for a lawsuit is an eDiscovery job, not a DLP policy or access review.",
        "module-describe-purview-risk-compliance-governance",
        "describe-ediscovery",
        ("scenario_application",),
        "purview_audit_ediscovery_insider_risk",
        "module",
    ),
    (
        "audit",
        "definition",
        "Purview audit records user and admin activities so organizations can investigate who did what, when, and where.",
        "doc-audit",
        "overview",
        ("definition",),
        "purview_audit_ediscovery_insider_risk",
        "product_documentation",
    ),
    (
        "audit",
        "distinction",
        "Audit provides an activity trail; it does not by itself block sharing or declare records.",
        "module-describe-purview-risk-compliance-governance",
        "describe-audit",
        ("concept_distinction",),
        "purview_audit_ediscovery_insider_risk",
        "module",
    ),
)


def _inventory_by_id() -> dict[str, dict[str, Any]]:
    inventory = load_json(INVENTORY_PATH)
    return {str(row["source_id"]): row for row in inventory["sources"]}


def build_knowledge_units() -> list[dict[str, Any]]:
    taxonomy = load_taxonomy()
    leaf_owner: dict[str, tuple[str, str]] = {}
    for row in taxonomy["objective_details"]:
        for leaf in row["leaf_skills"]:
            leaf_owner[str(leaf["id"])] = (str(row["domain_id"]), str(row["id"]))
    sources = _inventory_by_id()
    units: list[dict[str, Any]] = []
    seen: set[str] = set()
    for index, spec in enumerate(UNIT_SPECS, start=1):
        leaf, concept, claim, source_id, locator, opportunities, family, authority = spec
        domain_id, objective_id = leaf_owner[leaf]
        source = sources[source_id]
        unit_id = f"ku-{leaf}-{index:03d}"
        if unit_id in seen:
            raise ValueError(unit_id)
        seen.add(unit_id)
        units.append(
            {
                "knowledge_unit_id": unit_id,
                "domain_id": domain_id,
                "objective_id": objective_id,
                "leaf_skill_id": leaf,
                "concept": concept,
                "claim_summary": claim,
                "source_title": source["title"],
                "source_locator": locator,
                "source_url": source["url"],
                "retrieved_at": RETRIEVED_AT,
                "authority_level": authority,
                "currentness_status": "CURRENT",
                "question_opportunities": list(opportunities),
                "semantic_family_hint": family,
            }
        )
    return units


def write_knowledge_units() -> Path:
    units = build_knowledge_units()
    KNOWLEDGE_UNITS_PATH.parent.mkdir(parents=True, exist_ok=True)
    KNOWLEDGE_UNITS_PATH.write_text(
        "".join(json.dumps(row, ensure_ascii=False) + "\n" for row in units),
        encoding="utf-8",
    )
    return KNOWLEDGE_UNITS_PATH


if __name__ == "__main__":
    path = write_knowledge_units()
    print(f"wrote {path} units={len(build_knowledge_units())}")
