from __future__ import annotations

from tools.sc900_microsoft_corpus_qemit import question_record


def batch_06() -> list[dict]:
    b = "mlc-batch-06"
    return [
        question_record(
            serial=126,
            leaf="cloud_workload_protection",
            difficulty="intermediate",
            stem_style="misconception_correction",
            stem="Which statement about cloud workload protection is correct?",
            choices=[
                ("a", "It adds threat protection for running cloud workloads beyond configuration scoring"),
                ("b", "It is Microsoft's only identity provider"),
                ("c", "It publishes Service Trust reports"),
                ("d", "It is a retention label type"),
            ],
            correct="a",
            explanation="CWP/enhanced plans protect running workloads. They are not an IdP, STP, or retention feature.",
            source_id="doc-cwp",
            semantic_family_id="defender_for_cloud_cspm_cwp",
            tested_decision="cwp_not_identity_provider",
            batch=b,
        ),
        question_record(
            serial=127,
            leaf="sentinel_threat_detection_mitigation",
            difficulty="intermediate",
            stem_style="concept_distinction",
            stem="How does Microsoft Sentinel differ from Microsoft Defender for Cloud at a fundamentals level?",
            choices=[
                (
                    "a",
                    "Sentinel is SIEM/SOAR across many data sources; Defender for Cloud is cloud posture and workload protection",
                ),
                ("b", "They are identical"),
                ("c", "Sentinel issues FIDO2 keys"),
                ("d", "Defender for Cloud is only eDiscovery"),
            ],
            correct="a",
            explanation="Sentinel correlates security data and automates response. Defender for Cloud assesses and protects cloud resources.",
            source_id="doc-sentinel",
            semantic_family_id="sentinel_siem_soar_automation",
            tested_decision="sentinel_siem_vs_dfc_posture",
            batch=b,
        ),
        question_record(
            serial=128,
            leaf="siem_and_soar",
            difficulty="intermediate",
            stem_style="short_scenario",
            stem="Every phishing incident currently requires five manual ticket updates. Which concept describes automating those repeatable response steps?",
            choices=[("a", "SOAR"), ("b", "Hashing"), ("c", "Federation"), ("d", "Records declaration")],
            correct="a",
            explanation="SOAR is orchestration and automated response for repeatable steps. Hashing, federation, and records are unrelated.",
            source_id="module-describe-security-capabilities-of-azure-sentinel",
            semantic_family_id="sentinel_siem_soar_automation",
            tested_decision="soar_for_repeatable_incident_steps",
            batch=b,
        ),
        question_record(
            serial=129,
            leaf="defender_xdr_services",
            difficulty="beginner",
            stem_style="misconception_correction",
            stem="Which statement about Microsoft Defender XDR is correct?",
            choices=[
                (
                    "a",
                    "It is an extended detection and response suite, not a replacement for Entra ID as an identity provider",
                ),
                ("b", "It is the only way to create Azure VNets"),
                ("c", "It is a Service Trust Portal synonym"),
                ("d", "It is a TAP authentication method"),
            ],
            correct="a",
            explanation="XDR correlates Defender workload signals. It does not replace Entra ID, VNets, or STP.",
            source_id="doc-defender-xdr",
            semantic_family_id="defender_xdr_workload_suite",
            tested_decision="xdr_not_an_idp",
            batch=b,
        ),
        question_record(
            serial=130,
            leaf="defender_for_office_365",
            difficulty="beginner",
            stem_style="misconception_correction",
            stem="Which statement about Defender for Office 365 is correct?",
            choices=[
                ("a", "It protects email and collaboration from phishing and malware"),
                ("b", "It is Azure's stateful network firewall"),
                ("c", "It is Privileged Identity Management"),
                ("d", "It is Content explorer"),
            ],
            correct="a",
            explanation="MDO is email/collaboration threat protection, not Firewall, PIM, or classification browsing.",
            source_id="doc-defender-office",
            semantic_family_id="defender_xdr_workload_suite",
            tested_decision="mdo_not_azure_firewall",
            batch=b,
        ),
        question_record(
            serial=131,
            leaf="defender_for_endpoint",
            difficulty="beginner",
            stem_style="misconception_correction",
            stem="Which statement about Defender for Endpoint is correct?",
            choices=[
                ("a", "It provides endpoint detection and response for devices"),
                ("b", "It is a DDoS anycast network"),
                ("c", "It recertifies Entra groups"),
                ("d", "It stores app secrets as its primary purpose"),
            ],
            correct="a",
            explanation="MDE is EDR/device protection.",
            source_id="doc-defender-endpoint",
            semantic_family_id="defender_xdr_workload_suite",
            tested_decision="mde_not_ddos_or_pim",
            batch=b,
        ),
        question_record(
            serial=132,
            leaf="defender_portal",
            difficulty="beginner",
            stem_style="misconception_correction",
            stem="Which statement about the Microsoft Defender portal is correct?",
            choices=[
                ("a", "It is the unified operations experience for Defender XDR"),
                ("b", "It is where Microsoft publishes ISO audit reports for customers"),
                ("c", "It is Azure Key Vault"),
                ("d", "It is Conditional Access"),
            ],
            correct="a",
            explanation="The Defender portal is XDR operations. ISO reports are Service Trust Portal. Key Vault and Conditional Access are other consoles/capabilities.",
            source_id="doc-defender-portal",
            semantic_family_id="defender_xdr_workload_suite",
            tested_decision="defender_portal_not_stp",
            batch=b,
        ),
        question_record(
            serial=133,
            leaf="defender_threat_intelligence",
            difficulty="beginner",
            stem_style="misconception_correction",
            stem="Which statement about Defender Threat Intelligence is correct?",
            choices=[
                ("a", "It supplies threat-actor and indicator intelligence for investigations"),
                ("b", "It is a subnet NSG"),
                ("c", "It is Lifecycle Workflows"),
                ("d", "It is hashing"),
            ],
            correct="a",
            explanation="Defender TI is intelligence context, not networking, joiner automation, or cryptography.",
            source_id="doc-defender-ti",
            semantic_family_id="defender_xdr_workload_suite",
            tested_decision="ti_not_nsg",
            batch=b,
        ),
        question_record(
            serial=134,
            leaf="azure_web_application_firewall",
            difficulty="beginner",
            stem_style="misconception_correction",
            stem="Which statement about Azure WAF is correct?",
            choices=[
                ("a", "It helps protect web apps from HTTP attacks such as injection and XSS"),
                ("b", "It is Microsoft Entra MFA"),
                ("c", "It is Purview audit"),
                ("d", "It is Azure Bastion"),
            ],
            correct="a",
            explanation="WAF is application-layer HTTP protection.",
            source_id="doc-waf",
            semantic_family_id="azure_nsg_firewall_waf_ddos",
            tested_decision="waf_not_mfa",
            batch=b,
        ),
        question_record(
            serial=135,
            leaf="azure_virtual_network_segmentation",
            difficulty="beginner",
            stem_style="misconception_correction",
            stem="Which statement about Azure virtual network segmentation is correct?",
            choices=[
                ("a", "It isolates private address spaces so traffic between workloads can be controlled"),
                ("b", "It is a SIEM"),
                ("c", "It is eDiscovery"),
                ("d", "It is Password Protection"),
            ],
            correct="a",
            explanation="VNets provide private, segmentable networks.",
            source_id="doc-vnet",
            semantic_family_id="azure_virtual_network_segmentation",
            tested_decision="vnet_not_siem",
            batch=b,
        ),
        question_record(
            serial=136,
            leaf="azure_bastion",
            difficulty="beginner",
            stem_style="direct_concept",
            stem="Azure Bastion connects administrators to VMs using which remote protocols over TLS in the browser?",
            choices=[("a", "RDP and SSH"), ("b", "SMTP and IMAP"), ("c", "BGP only"), ("d", "SNMP traps only")],
            correct="a",
            explanation="Bastion's purpose is managed RDP/SSH to VMs over TLS.",
            source_id="module-describe-basic-security-capabilities-azure",
            semantic_family_id="azure_bastion",
            tested_decision="bastion_rdp_ssh_over_tls",
            batch=b,
        ),
        question_record(
            serial=137,
            leaf="security_policies_standards_recommendations",
            difficulty="beginner",
            stem_style="misconception_correction",
            stem="Which statement about Defender for Cloud recommendations is correct?",
            choices=[
                ("a", "They identify resources that do not meet the assigned security standard"),
                ("b", "They are Entra access packages"),
                ("c", "They are Safe Attachments policies"),
                ("d", "They are Key Vault secrets"),
            ],
            correct="a",
            explanation="Recommendations are posture-gap items from assigned standards/policies.",
            source_id="module-describe-security-management-capabilities-of-azure",
            semantic_family_id="defender_for_cloud_cspm_cwp",
            tested_decision="recommendations_are_posture_gaps",
            batch=b,
        ),
        question_record(
            serial=138,
            leaf="cloud_security_posture_management",
            difficulty="beginner",
            stem_style="misconception_correction",
            stem="Which statement about CSPM is correct?",
            choices=[
                ("a", "CSPM continuously assesses cloud configuration against security standards"),
                ("b", "CSPM is mailbox anti-phishing"),
                ("c", "CSPM is guest access recertification"),
                ("d", "CSPM is RDP jump-hosting"),
            ],
            correct="a",
            explanation="CSPM is configuration assessment, not email, reviews, or Bastion.",
            source_id="doc-cspm",
            semantic_family_id="defender_for_cloud_cspm_cwp",
            tested_decision="cspm_not_phishing",
            batch=b,
        ),
        question_record(
            serial=139,
            leaf="defender_for_cloud_apps",
            difficulty="beginner",
            stem_style="direct_concept",
            stem="Discovering that staff use an unsanctioned file-sharing SaaS app is a classic job for which Defender service?",
            choices=[
                ("a", "Microsoft Defender for Cloud Apps"),
                ("b", "Azure DDoS Protection"),
                ("c", "Azure Key Vault"),
                ("d", "Privileged Identity Management"),
            ],
            correct="a",
            explanation="Shadow IT discovery is a CASB/Defender for Cloud Apps scenario.",
            source_id="module-describe-threat-protection-with-microsoft-365-defender",
            semantic_family_id="defender_xdr_workload_suite",
            tested_decision="shadow_it_discovery_mcas",
            batch=b,
        ),
        question_record(
            serial=140,
            leaf="defender_for_identity",
            difficulty="beginner",
            stem_style="misconception_correction",
            stem="Which statement about Defender for Identity is correct?",
            choices=[
                ("a", "It detects identity-based attacks using Active Directory signals"),
                ("b", "It is Azure WAF"),
                ("c", "It is a retention policy"),
                ("d", "It is DDoS Protection"),
            ],
            correct="a",
            explanation="Defender for Identity is AD-signal identity threat detection.",
            source_id="doc-defender-identity",
            semantic_family_id="defender_xdr_workload_suite",
            tested_decision="mdi_not_waf",
            batch=b,
        ),
        question_record(
            serial=141,
            leaf="defender_vulnerability_management",
            difficulty="beginner",
            stem_style="misconception_correction",
            stem="Which statement about Defender Vulnerability Management is correct?",
            choices=[
                ("a", "It helps find and prioritize vulnerabilities so they can be remediated"),
                ("b", "It is Conditional Access"),
                ("c", "It is Federation"),
                ("d", "It is hashing"),
            ],
            correct="a",
            explanation="Vulnerability management is discover-and-prioritize, not identity policy, federation, or hashing.",
            source_id="doc-defender-vulnerability-management",
            semantic_family_id="defender_xdr_workload_suite",
            tested_decision="mdvm_not_conditional_access",
            batch=b,
        ),
        question_record(
            serial=142,
            leaf="azure_firewall",
            difficulty="intermediate",
            stem_style="short_scenario",
            stem="A hub-and-spoke design needs one place to inspect traffic between spokes using FQDN application rules. Which service is designed for that central inspection?",
            choices=[
                ("a", "Azure Firewall"),
                ("b", "A single NSG on one NIC only, with no hub"),
                ("c", "Temporary Access Pass"),
                ("d", "Content explorer"),
            ],
            correct="a",
            explanation="Azure Firewall is commonly placed in a hub for centralized FQDN and network rule inspection. A lone NIC NSG is not that hub firewall.",
            source_id="module-describe-basic-security-capabilities-azure",
            semantic_family_id="azure_nsg_firewall_waf_ddos",
            tested_decision="hub_firewall_fqdn_rules",
            batch=b,
        ),
        question_record(
            serial=143,
            leaf="network_security_groups",
            difficulty="intermediate",
            stem_style="concept_distinction",
            stem="Why might an organization still use NSGs when Azure Firewall is present?",
            choices=[
                ("a", "NSGs provide distributed subnet/NIC filters in addition to a centralized firewall"),
                ("b", "NSGs replace Entra ID"),
                ("c", "NSGs declare records"),
                ("d", "NSGs issue passkeys"),
            ],
            correct="a",
            explanation="Defense-in-depth often pairs distributed NSGs with a centralized firewall. They are complementary filters.",
            source_id="doc-nsg",
            semantic_family_id="azure_nsg_firewall_waf_ddos",
            tested_decision="nsgs_complement_firewall",
            batch=b,
        ),
        question_record(
            serial=144,
            leaf="azure_ddos_protection",
            difficulty="intermediate",
            stem_style="short_scenario",
            stem="A public-facing Azure load balancer is at risk of being overwhelmed by spoofed traffic. Which Azure service is purpose-built for that availability threat?",
            choices=[
                ("a", "Azure DDoS Protection"),
                ("b", "Microsoft Entra ID Governance"),
                ("c", "Purview Insider Risk Management"),
                ("d", "Access reviews"),
            ],
            correct="a",
            explanation="Availability against volumetric attacks is DDoS Protection, not identity governance or insider-risk compliance.",
            source_id="doc-ddos",
            semantic_family_id="azure_nsg_firewall_waf_ddos",
            tested_decision="ddos_for_public_lb_availability",
            batch=b,
        ),
        question_record(
            serial=145,
            leaf="azure_web_application_firewall",
            difficulty="intermediate",
            stem_style="short_scenario",
            stem="An API Management or Application Gateway front end should block OWASP-style web attacks before they reach the app. Which control does that?",
            choices=[
                ("a", "Azure Web Application Firewall"),
                ("b", "Microsoft Entra Password Protection"),
                ("c", "Azure Bastion"),
                ("d", "Defender TI"),
            ],
            correct="a",
            explanation="WAF sits in front of web applications/APIs to inspect HTTP for OWASP-class attacks.",
            source_id="doc-waf",
            semantic_family_id="azure_nsg_firewall_waf_ddos",
            tested_decision="waf_in_front_of_app_gateway",
            batch=b,
        ),
        question_record(
            serial=146,
            leaf="microsoft_defender_for_cloud",
            difficulty="intermediate",
            stem_style="concept_distinction",
            stem="Secure score in Defender for Cloud measures which kind of health?",
            choices=[
                ("a", "Cloud resource security posture against recommendations"),
                ("b", "Compliance Manager regulatory improvement actions"),
                ("c", "Mailbox phishing catch rate only"),
                ("d", "Entra password banned-list size"),
            ],
            correct="a",
            explanation="Defender for Cloud secure score is posture, not Compliance Manager compliance score or mailbox metrics.",
            source_id="doc-defender-for-cloud",
            semantic_family_id="defender_for_cloud_cspm_cwp",
            tested_decision="secure_score_not_compliance_score",
            batch=b,
        ),
        question_record(
            serial=147,
            leaf="sentinel_threat_detection_mitigation",
            difficulty="beginner",
            stem_style="short_scenario",
            stem="Security wants one place to ingest Microsoft 365, Azure, and firewall logs, then create incidents. Which service is designed for that collection and detection?",
            choices=[
                ("a", "Microsoft Sentinel"),
                ("b", "Azure Bastion"),
                ("c", "Temporary Access Pass"),
                ("d", "Sensitivity labels"),
            ],
            correct="a",
            explanation="Sentinel ingests many data sources for SIEM detection. Bastion, TAP, and labels do not do that.",
            source_id="doc-sentinel",
            semantic_family_id="sentinel_siem_soar_automation",
            tested_decision="sentinel_ingests_many_log_sources",
            batch=b,
        ),
        question_record(
            serial=148,
            leaf="defender_xdr_services",
            difficulty="intermediate",
            stem_style="multi_select",
            stem="Which two Microsoft Defender workloads are part of the Defender XDR family described in current SC-900 training? (Choose two.)",
            choices=[
                ("a", "Microsoft Defender for Endpoint"),
                ("b", "Microsoft Defender for Office 365"),
                ("c", "Azure DDoS Protection"),
                ("d", "Azure Bastion"),
            ],
            correct=["a", "b"],
            explanation="Defender for Endpoint and Defender for Office 365 are XDR workload services. DDoS Protection and Bastion are Azure infrastructure controls, not XDR workloads.",
            source_id="module-describe-threat-protection-with-microsoft-365-defender",
            semantic_family_id="defender_xdr_workload_suite",
            tested_decision="xdr_workloads_endpoint_and_office",
            qtype="multi_select",
            batch=b,
        ),
        question_record(
            serial=149,
            leaf="azure_key_vault",
            difficulty="beginner",
            stem_style="capability_selection",
            stem="Which Azure service is the fundamentals answer for storing cryptographic keys used by cloud applications?",
            choices=[
                ("a", "Azure Key Vault"),
                ("b", "Microsoft Defender for Office 365"),
                ("c", "Access reviews"),
                ("d", "Azure DDoS Protection"),
            ],
            correct="a",
            explanation="Key Vault stores cryptographic keys. The other services are email security, identity recertification, or DDoS mitigation.",
            source_id="doc-key-vault",
            semantic_family_id="azure_key_vault",
            tested_decision="key_vault_for_crypto_keys",
            batch=b,
        ),
        question_record(
            serial=150,
            leaf="entra_id_governance",
            difficulty="beginner",
            stem_style="short_scenario",
            stem="Business users should request access to a group of apps through a package with approval. Which Entra ID Governance feature does that?",
            choices=[
                ("a", "Entitlement management access packages"),
                ("b", "Azure Firewall"),
                ("c", "DDoS Protection"),
                ("d", "Key Vault"),
            ],
            correct="a",
            explanation="Entitlement management packages resources into requestable access packages with approval workflows.",
            source_id="doc-id-governance",
            semantic_family_id="entra_id_governance_and_access_reviews",
            tested_decision="users_request_access_packages",
            batch=b,
        ),
    ]
