from __future__ import annotations

from tools.sc900_microsoft_corpus_qemit import question_record


def batch_12() -> list[dict]:
    b = "mlc-batch-12"
    return [
        question_record(
            serial=276,
            leaf="defender_threat_intelligence",
            difficulty="intermediate",
            stem_style="concept_distinction",
            stem="An analyst looks up a domain in Microsoft threat-intel articles. A user clicks a URL in email. Which pairing is accurate?",
            choices=[
                (
                    "a",
                    "Defender Threat Intelligence provides actor and infrastructure context; Safe Links is the email time-of-click control",
                ),
                ("b", "Defender TI detonates mailbox attachments as Safe Attachments"),
                ("c", "Safe Links is Microsoft's actor encyclopedia"),
                ("d", "Both jobs are Azure Key Vault certificate issuance"),
            ],
            correct="a",
            explanation="Defender TI is intelligence context. Safe Links is a Defender for Office 365 URL control. Looking up a domain in TI is not the same as protecting mailbox clicks.",
            source_id="doc-defender-ti",
            semantic_family_id="defender_xdr_workload_suite",
            tested_decision="defender_ti_intel_not_mdo_safe_links",
            batch=b,
        ),
        question_record(
            serial=277,
            leaf="microsoft_privacy_principles",
            difficulty="intermediate",
            stem_style="direct_concept",
            stem="Microsoft lists protection of customer data, including security safeguards, among its privacy commitments. Which statement matches that principle?",
            choices=[
                (
                    "a",
                    "Protecting customer data with security controls is part of Microsoft's privacy commitments, not a reason to ignore encryption or access control",
                ),
                ("b", "Privacy means Microsoft must disable MFA so support can read mailboxes"),
                ("c", "Privacy is achieved by publishing NSG allow-all rules"),
                ("d", "Privacy is a Defender XDR workload name"),
            ],
            correct="a",
            explanation="Microsoft privacy principles include protection of customer data. Privacy is not a justification for weakening authentication or opening networks.",
            source_id="doc-privacy-principles",
            semantic_family_id="service_trust_privacy_compliance_manager",
            tested_decision="privacy_principle_includes_data_protection",
            batch=b,
        ),
        question_record(
            serial=278,
            leaf="microsoft_privacy_principles",
            difficulty="intermediate",
            stem_style="short_scenario",
            stem="A learner says Microsoft's privacy principles and Purview Compliance Manager are the same feature. Which correction is accurate?",
            choices=[
                (
                    "a",
                    "Privacy principles are Microsoft's data-handling commitments; Compliance Manager tracks customer improvement actions against assessments",
                ),
                ("b", "Privacy principles are a Compliance Manager score formula"),
                ("c", "Compliance Manager is Microsoft's public privacy statement"),
                ("d", "Both are Azure DDoS Protection SKUs"),
            ],
            correct="a",
            explanation="Privacy principles describe Microsoft's commitments. Compliance Manager is a Purview tool for assessing and improving the customer's control implementation.",
            source_id="module-describe-compliance-management-capabilities-microsoft",
            semantic_family_id="service_trust_privacy_compliance_manager",
            tested_decision="privacy_principles_not_compliance_manager_tool",
            batch=b,
        ),
        question_record(
            serial=279,
            leaf="service_trust_portal_offerings",
            difficulty="intermediate",
            stem_style="concept_distinction",
            stem="A prospect wants Microsoft's ISO and SOC audit reports. An administrator wants to configure DLP in the tenant. Which pairing is accurate?",
            choices=[
                (
                    "a",
                    "Service Trust Portal for Microsoft's audit reports; Microsoft Purview portal for the tenant's DLP configuration",
                ),
                ("b", "The Service Trust Portal is where you create tenant DLP policies"),
                ("c", "The Purview portal publishes Microsoft's SOC reports as its primary job"),
                ("d", "Both jobs are done in Azure Bastion"),
            ],
            correct="a",
            explanation="STP hosts Microsoft's trust and audit documentation. Tenant compliance configuration is done in Purview. Those portals serve different audiences.",
            source_id="doc-service-trust-portal",
            semantic_family_id="service_trust_privacy_compliance_manager",
            tested_decision="stp_microsoft_reports_vs_purview_tenant_config",
            batch=b,
        ),
        question_record(
            serial=280,
            leaf="purview_portal",
            difficulty="intermediate",
            stem_style="short_scenario",
            stem="Identity admins work in the Microsoft Entra admin center. Compliance admins need DLP, audit, and eDiscovery. Why is the Entra admin center the wrong primary console for that compliance work?",
            choices=[
                (
                    "a",
                    "Those Purview solutions are reached from the Microsoft Purview portal, not from Entra identity administration",
                ),
                ("b", "The Entra admin center is the only supported DLP console"),
                ("c", "eDiscovery holds are Conditional Access grant controls"),
                ("d", "DLP policies are Azure Bastion settings"),
            ],
            correct="a",
            explanation="Entra admin center is for identity. Purview portal is for compliance solutions such as DLP, audit, and eDiscovery.",
            source_id="doc-purview-portal",
            semantic_family_id="purview_portal",
            tested_decision="purview_compliance_not_entra_admin_center",
            batch=b,
        ),
        question_record(
            serial=281,
            leaf="compliance_manager",
            difficulty="intermediate",
            stem_style="concept_distinction",
            stem="Compliance Manager shows some GDPR-related actions as Microsoft-managed and others as customer-managed. What does that split mean?",
            choices=[
                (
                    "a",
                    "Microsoft implements some controls for its service; the customer still completes remaining improvement actions",
                ),
                ("b", "Customer-managed actions are performed automatically by Azure Firewall"),
                ("c", "Microsoft-managed actions recertify Entra guest groups"),
                ("d", "The split means the customer no longer owns any data"),
            ],
            correct="a",
            explanation="Compliance Manager distinguishes Microsoft-implemented service controls from customer improvement actions. SaaS does not finish the customer's compliance work.",
            source_id="doc-compliance-manager",
            semantic_family_id="service_trust_privacy_compliance_manager",
            tested_decision="cm_microsoft_managed_vs_customer_actions",
            misconception_target="microsoft_completes_all_gdpr_actions",
            batch=b,
        ),
        question_record(
            serial=282,
            leaf="compliance_score",
            difficulty="intermediate",
            stem_style="misconception_correction",
            stem="A manager treats compliance score as a pass/fail exam result that proves the company is certified. What is the accurate correction?",
            choices=[
                (
                    "a",
                    "Compliance score estimates remaining improvement-action progress; it is not itself a certification or exam grade",
                ),
                ("b", "A score of 100 is Microsoft's official ISO certificate"),
                ("c", "Compliance score replaces the need for the Service Trust Portal"),
                ("d", "Compliance score is Defender for Cloud's only secure-score value"),
            ],
            correct="a",
            explanation="Compliance score is a prioritization metric inside Compliance Manager. It does not certify the organization or replace Microsoft audit reports.",
            source_id="doc-compliance-score",
            semantic_family_id="service_trust_privacy_compliance_manager",
            tested_decision="compliance_score_is_not_a_certification",
            misconception_target="compliance_score_equals_certification",
            batch=b,
        ),
        question_record(
            serial=283,
            leaf="data_classification",
            difficulty="intermediate",
            stem_style="short_scenario",
            stem="Classification found credit-card numbers. A learner says that finding already encrypts the files. What is missing?",
            choices=[
                (
                    "a",
                    "Classification identifies sensitive items; protection still requires labels, DLP, or other controls that act on those findings",
                ),
                ("b", "Sensitive information types automatically issue FIDO2 keys"),
                ("c", "Classification is Azure DDoS Protection"),
                ("d", "Finding a pattern deletes the file, so encryption is unnecessary"),
            ],
            correct="a",
            explanation="Classification answers what exists and where. Encryption, labeling, and DLP are separate protection decisions.",
            source_id="doc-data-classification",
            semantic_family_id="purview_information_protection_lifecycle",
            tested_decision="classification_finds_data_it_does_not_encrypt",
            batch=b,
        ),
        question_record(
            serial=284,
            leaf="content_and_activity_explorer",
            difficulty="intermediate",
            stem_style="concept_distinction",
            stem="Content explorer shows where labeled items live. Activity explorer shows labeling, sharing, and DLP events. Why are those explorers not DLP policies?",
            choices=[
                ("a", "Explorers provide visibility; DLP policies detect and help prevent risky sharing"),
                ("b", "Content explorer blocks outbound credit-card numbers as its primary job"),
                ("c", "Activity explorer declares records automatically"),
                ("d", "Both explorers are Azure Firewall application rules"),
            ],
            correct="a",
            explanation="The explorers answer where content is and what happened to it. They do not replace DLP prevention policies.",
            source_id="doc-content-explorer",
            semantic_family_id="purview_information_protection_lifecycle",
            tested_decision="explorers_are_visibility_not_dlp_prevention",
            batch=b,
        ),
        question_record(
            serial=285,
            leaf="sensitivity_labels_and_policies",
            difficulty="intermediate",
            stem_style="multi_select",
            stem="Which two protection outcomes can a sensitivity label apply to a document in addition to classifying it? (Choose two.)",
            choices=[
                ("a", "Encryption and access restrictions that travel with the file"),
                ("b", "Visual markings such as headers, footers, or watermarks"),
                ("c", "Azure DDoS Protection for the author's public IP"),
                ("d", "Just-in-time Global Administrator activation"),
            ],
            correct=["a", "b"],
            explanation="Sensitivity labels can encrypt content and apply markings. They are not DDoS or PIM controls.",
            source_id="doc-sensitivity-labels",
            semantic_family_id="purview_information_protection_lifecycle",
            tested_decision="label_protection_encryption_and_markings",
            qtype="multi_select",
            batch=b,
        ),
        question_record(
            serial=286,
            leaf="data_loss_prevention",
            difficulty="intermediate",
            stem_style="concept_distinction",
            stem="A file is labeled Confidential and encrypted, but a user can still paste the same credit-card numbers into a Teams chat. Which control is missing?",
            choices=[
                (
                    "a",
                    "Data loss prevention policies that detect and restrict sensitive sharing in locations such as Teams",
                ),
                ("b", "Azure DDoS Protection on the Teams tenant"),
                ("c", "Azure Bastion for the Teams client"),
                ("d", "Privileged Identity Management eligible roles"),
            ],
            correct="a",
            explanation="Labels can protect a document. DLP watches sharing channels such as Teams for sensitive information types. Encryption on one file does not automatically DLP the chat channel.",
            source_id="doc-dlp",
            semantic_family_id="purview_information_protection_lifecycle",
            tested_decision="labeled_file_encryption_does_not_replace_teams_dlp",
            batch=b,
        ),
        question_record(
            serial=287,
            leaf="data_loss_prevention",
            difficulty="intermediate",
            stem_style="short_scenario",
            stem="Security wants the same credit-card DLP check in Exchange email, SharePoint, Teams, and on endpoints. What should the learner expect?",
            choices=[
                ("a", "DLP policies can apply across multiple locations rather than only one mailbox"),
                ("b", "DLP exists only as an Azure NSG application rule"),
                ("c", "DLP can run only after a file is declared a record"),
                ("d", "Endpoint DLP is a Conditional Access grant control"),
            ],
            correct="a",
            explanation="Purview DLP is designed to cover multiple locations including email, sites, chat, and devices. It is not an NSG, a record requirement, or a Conditional Access grant.",
            source_id="doc-dlp",
            semantic_family_id="purview_information_protection_lifecycle",
            tested_decision="dlp_covers_multiple_locations",
            batch=b,
        ),
        question_record(
            serial=288,
            leaf="records_management",
            difficulty="intermediate",
            stem_style="concept_distinction",
            stem="A records team needs a scheduled review before a declared record can be disposed of at the end of its retention period. Which records-management idea is that?",
            choices=[
                ("a", "Disposition review, which can require approval before a record is destroyed"),
                ("b", "Azure WAF custom rules that delete SharePoint items"),
                ("c", "Microsoft Entra access reviews of VM start rights"),
                ("d", "Safe Links time-of-click URL checks"),
            ],
            correct="a",
            explanation="Records management can require disposition review so records are not silently deleted when the retention period ends. WAF, Entra access reviews, and Safe Links are not records disposition.",
            source_id="doc-records-management",
            semantic_family_id="purview_information_protection_lifecycle",
            tested_decision="records_disposition_review_before_destruction",
            batch=b,
        ),
        question_record(
            serial=289,
            leaf="compliance_score",
            difficulty="intermediate",
            stem_style="multi_select",
            stem="Which two elements does Compliance Manager use when it helps an organization understand remaining compliance work? (Choose two.)",
            choices=[
                ("a", "Improvement actions the customer still needs to complete"),
                ("b", "A compliance score that estimates progress against recommended controls"),
                ("c", "Azure DDoS Protection SKU assignment"),
                ("d", "FIDO2 security-key inventory"),
            ],
            correct=["a", "b"],
            explanation="Compliance Manager combines improvement actions and a compliance score to prioritize remaining customer work. DDoS SKUs and FIDO2 inventory are not Compliance Manager elements.",
            source_id="doc-compliance-score",
            semantic_family_id="service_trust_privacy_compliance_manager",
            tested_decision="cm_actions_and_score_prioritize_remaining_work",
            qtype="multi_select",
            batch=b,
        ),
        question_record(
            serial=290,
            leaf="insider_risk_management",
            difficulty="intermediate",
            stem_style="concept_distinction",
            stem="DLP blocked a credit-card number in email. Separately, a departing employee downloaded thousands of unlabeled files over two weeks. Which tool is designed for that second pattern?",
            choices=[
                (
                    "a",
                    "Insider Risk Management, which looks for risky user behavior patterns, not only a single DLP match",
                ),
                ("b", "Azure DDoS Protection"),
                ("c", "Azure Bastion"),
                ("d", "Microsoft Entra Temporary Access Pass"),
            ],
            correct="a",
            explanation="DLP is policy matching on sensitive content. Insider Risk Management looks at sequences of potentially risky user activity such as departing-employee exfiltration.",
            source_id="doc-insider-risk",
            semantic_family_id="purview_audit_ediscovery_insider_risk",
            tested_decision="irm_behavior_pattern_not_single_dlp_match",
            batch=b,
        ),
        question_record(
            serial=291,
            leaf="ediscovery",
            difficulty="intermediate",
            stem_style="concept_distinction",
            stem="Legal needs mailboxes preserved for a lawsuit even if users try to delete messages. How does that differ from a routine retention period?",
            choices=[
                (
                    "a",
                    "eDiscovery hold preserves content for a legal matter; retention is a lifecycle keep-or-delete schedule",
                ),
                ("b", "Retention holds are the only way to respond to a lawsuit"),
                ("c", "eDiscovery hold is a Conditional Access grant control"),
                ("d", "A lawsuit is preserved only by Azure Firewall"),
            ],
            correct="a",
            explanation="Legal hold is an eDiscovery preservation action for a matter. Retention policies serve ongoing lifecycle requirements. They can coexist but they are not the same decision.",
            source_id="doc-ediscovery",
            semantic_family_id="purview_audit_ediscovery_insider_risk",
            tested_decision="legal_hold_vs_lifecycle_retention",
            batch=b,
        ),
        question_record(
            serial=292,
            leaf="audit",
            difficulty="intermediate",
            stem_style="short_scenario",
            stem="Investigators ask who changed a DLP policy yesterday and from where. They do not need to export an entire mailbox for court. Which Purview capability answers that?",
            choices=[
                ("a", "Audit logging of user and admin activities"),
                ("b", "Azure Bastion session recording of the mailbox"),
                ("c", "Microsoft Entra lifecycle workflows"),
                ("d", "Azure DDoS Protection reports"),
            ],
            correct="a",
            explanation="Purview audit records who did what, when, and where. Exporting a mailbox for court is eDiscovery. Bastion, lifecycle workflows, and DDoS reports are not that activity trail.",
            source_id="doc-audit",
            semantic_family_id="purview_audit_ediscovery_insider_risk",
            tested_decision="audit_answers_who_changed_policy_not_mailbox_export",
            batch=b,
        ),
        question_record(
            serial=293,
            leaf="compliance_manager",
            difficulty="intermediate",
            stem_style="short_scenario",
            stem="A customer must show progress against ISO 27001 improvement actions in their own tenant, not download Microsoft's ISO report. Which tool is that customer-side tracker?",
            choices=[
                ("a", "Microsoft Purview Compliance Manager"),
                ("b", "The Service Trust Portal only"),
                ("c", "Azure Bastion"),
                ("d", "Microsoft Defender Vulnerability Management"),
            ],
            correct="a",
            explanation="Compliance Manager tracks the customer's control implementation. STP publishes Microsoft's evidence. The customer still needs Compliance Manager for their own remaining actions.",
            source_id="doc-compliance-manager",
            semantic_family_id="service_trust_privacy_compliance_manager",
            tested_decision="cm_tracks_customer_iso_actions_not_microsoft_pdf",
            batch=b,
        ),
        question_record(
            serial=294,
            leaf="content_and_activity_explorer",
            difficulty="intermediate",
            stem_style="short_scenario",
            stem="An investigator knows a file was labeled Highly Confidential this morning and then shared externally. Which explorer shows that activity timeline?",
            choices=[
                ("a", "Activity explorer"),
                ("b", "Azure DDoS Protection metrics"),
                ("c", "Microsoft Entra Privileged Identity Management"),
                ("d", "Azure Key Vault insights"),
            ],
            correct="a",
            explanation="Activity explorer shows labeling, sharing, and DLP-related events. Content explorer would answer where items are stored, not the event timeline.",
            source_id="doc-activity-explorer",
            semantic_family_id="purview_information_protection_lifecycle",
            tested_decision="activity_explorer_timeline_for_label_and_share",
            batch=b,
        ),
        question_record(
            serial=295,
            leaf="sensitivity_labels_and_policies",
            difficulty="intermediate",
            stem_style="short_scenario",
            stem="Users should see Confidential markings on documents, but not every label defined in the tenant. Which statement is accurate?",
            choices=[
                ("a", "A label policy publishes selected labels to those users; unused labels can remain unpublished"),
                ("b", "Every label in the tenant is always visible in Word"),
                ("c", "Named locations publish sensitivity labels"),
                ("d", "Network security groups publish labels to Word"),
            ],
            correct="a",
            explanation="Creating a label does not automatically show it to users. Label policies control publication. This is a different decision from what protection a label applies.",
            source_id="doc-sensitivity-labels",
            semantic_family_id="purview_information_protection_lifecycle",
            tested_decision="unpublished_labels_are_not_visible_to_users",
            batch=b,
        ),
        question_record(
            serial=296,
            leaf="retention_policies_labels",
            difficulty="intermediate",
            stem_style="short_scenario",
            stem="Email must be kept for seven years, but the same mailbox must still be prevented from sending credit-card numbers. Which pairing is accurate?",
            choices=[
                (
                    "a",
                    "Retention keeps content for the required period; DLP prevents risky sharing of sensitive information",
                ),
                ("b", "Retention blocks outbound credit-card numbers as its primary job"),
                ("c", "DLP is the keep-or-delete lifecycle engine"),
                ("d", "Both needs are met only by Azure Bastion"),
            ],
            correct="a",
            explanation="Retention is lifecycle keep-or-delete. DLP is preventive sharing control. A seven-year keep does not by itself stop credit-card exfiltration.",
            source_id="doc-retention",
            semantic_family_id="purview_information_protection_lifecycle",
            tested_decision="retention_keep_is_not_dlp_prevention",
            batch=b,
        ),
        question_record(
            serial=297,
            leaf="ediscovery",
            difficulty="intermediate",
            stem_style="short_scenario",
            stem="After a hold is in place, legal still needs to search, review, and export a set of emails for opposing counsel. Which Purview solution family covers that workflow?",
            choices=[
                ("a", "eDiscovery"),
                ("b", "Azure DDoS Protection"),
                ("c", "Microsoft Entra password protection"),
                ("d", "Azure virtual network peering"),
            ],
            correct="a",
            explanation="eDiscovery covers hold, search, review, and export for legal matters. DDoS, password protection, and VNet peering do not produce a legal production set.",
            source_id="doc-ediscovery",
            semantic_family_id="purview_audit_ediscovery_insider_risk",
            tested_decision="ediscovery_search_review_export_after_hold",
            batch=b,
        ),
        question_record(
            serial=298,
            leaf="audit",
            difficulty="intermediate",
            stem_style="concept_distinction",
            stem="Audit tells who changed a policy. eDiscovery exports mailbox content for a lawsuit. DLP tries to stop a share. Which statement keeps those jobs separate?",
            choices=[
                (
                    "a",
                    "Audit is detective history, eDiscovery is legal preservation and production, and DLP is preventive control",
                ),
                ("b", "Audit blocks sharing, eDiscovery is a firewall, and DLP exports mailboxes"),
                ("c", "All three are Azure Bastion features"),
                ("d", "All three are Conditional Access grant controls"),
            ],
            correct="a",
            explanation="SC-900 expects learners to place audit, eDiscovery, and DLP in detective, legal, and preventive roles rather than treating Purview as one interchangeable switch.",
            source_id="doc-audit",
            semantic_family_id="purview_audit_ediscovery_insider_risk",
            tested_decision="audit_detective_ediscovery_legal_dlp_preventive",
            batch=b,
        ),
        question_record(
            serial=299,
            leaf="insider_risk_management",
            difficulty="intermediate",
            stem_style="misconception_correction",
            stem="A manager wants Insider Risk Management to replace Conditional Access and block every risky sign-in. What is the accurate correction?",
            choices=[
                (
                    "a",
                    "Insider Risk Management analyzes internal user activity patterns; Conditional Access still evaluates sign-in conditions",
                ),
                ("b", "Insider Risk Management is Microsoft's only MFA grant control"),
                ("c", "Conditional Access is a subset of Insider Risk Management file plans"),
                ("d", "Insider Risk Management issues FIDO2 keys"),
            ],
            correct="a",
            explanation="Insider risk is a Purview compliance capability for internal behavior. Sign-in grants and blocks remain an Entra Conditional Access job.",
            source_id="doc-insider-risk",
            semantic_family_id="purview_audit_ediscovery_insider_risk",
            tested_decision="irm_does_not_replace_conditional_access",
            misconception_target="irm_is_conditional_access",
            batch=b,
        ),
        question_record(
            serial=300,
            leaf="purview_portal",
            difficulty="intermediate",
            stem_style="misconception_correction",
            stem="An Azure administrator opens the Azure portal to create a Microsoft Purview DLP policy for Exchange Online and cannot find it. What is the likely reason?",
            choices=[
                (
                    "a",
                    "Microsoft 365 DLP and related Purview solutions are administered in the Microsoft Purview portal, not as an Azure VM setting",
                ),
                ("b", "DLP policies can be created only in Azure Bastion"),
                ("c", "Exchange DLP is a network security group"),
                ("d", "The Azure portal is the only supported Purview console"),
            ],
            correct="a",
            explanation="Purview compliance solutions are reached from the Purview portal. The Azure portal is the wrong console for Exchange DLP.",
            source_id="doc-purview-portal",
            semantic_family_id="purview_portal",
            tested_decision="purview_dlp_not_configured_as_azure_vm_setting",
            misconception_target="azure_portal_is_purview_dlp_console",
            batch=b,
        ),
    ]
