from __future__ import annotations

from tools.sc900_microsoft_corpus_qemit import question_record


def batch_03() -> list[dict]:
    b = "mlc-batch-03"
    return [
        question_record(
            serial=51,
            leaf="entra_id_overview",
            difficulty="beginner",
            stem_style="misconception_correction",
            stem="Which statement about Microsoft Entra ID is correct?",
            choices=[
                ("a", "It is only a physical badge printer"),
                ("b", "It is Microsoft's cloud identity and access management service"),
                ("c", "It replaces Azure virtual networks"),
                ("d", "It is a DDoS scrubbing center"),
            ],
            correct="b",
            explanation="Entra ID is cloud IAM. It is not a badge printer, VNet replacement, or DDoS service.",
            source_id="doc-entra-what-is",
            semantic_family_id="entra_hybrid_identity_and_ad",
            tested_decision="entra_id_not_network_or_ddos",
            batch=b,
        ),
        question_record(
            serial=52,
            leaf="hybrid_identity",
            difficulty="beginner",
            stem_style="direct_concept",
            stem="What problem does hybrid identity primarily solve?",
            choices=[
                ("a", "Using one identity across on-premises directories and cloud apps"),
                ("b", "Blocking SQL injection at a web gateway"),
                ("c", "Scoring cloud misconfigurations"),
                ("d", "Holding email for legal discovery"),
            ],
            correct="a",
            explanation="Hybrid identity unifies on-premises and cloud identity use. WAF, CSPM, and eDiscovery solve other problems.",
            source_id="doc-hybrid-identity",
            semantic_family_id="entra_hybrid_identity_and_ad",
            tested_decision="hybrid_solves_split_directory_problem",
            batch=b,
        ),
        question_record(
            serial=53,
            leaf="authentication_methods",
            difficulty="intermediate",
            stem_style="short_scenario",
            stem="A user wants to sign in with a device-bound biometric and PIN instead of a password. Which Entra method family supports that Windows experience?",
            choices=[
                ("a", "Windows Hello for Business"),
                ("b", "Purview Communication Compliance"),
                ("c", "Azure Firewall NAT"),
                ("d", "Defender TI articles"),
            ],
            correct="a",
            explanation="Windows Hello for Business is an Entra-supported passwordless authentication method using device-bound credentials.",
            source_id="doc-authentication-methods",
            semantic_family_id="authentication_methods",
            tested_decision="windows_hello_passwordless",
            batch=b,
        ),
        question_record(
            serial=54,
            leaf="password_protection_management",
            difficulty="beginner",
            stem_style="misconception_correction",
            stem="Which statement about Entra password protection is correct?",
            choices=[
                ("a", "It can block passwords that appear on banned lists, including custom terms"),
                ("b", "It encrypts NSG flow logs"),
                ("c", "It is a SIEM connector"),
                ("d", "It declares SharePoint records"),
            ],
            correct="a",
            explanation="Password Protection evaluates passwords against banned lists. It is not a SIEM, NSG, or records feature.",
            source_id="doc-password-protection",
            semantic_family_id="password_protection_management",
            tested_decision="custom_banned_password_list",
            batch=b,
        ),
        question_record(
            serial=55,
            leaf="conditional_access",
            difficulty="beginner",
            stem_style="capability_selection",
            stem="Which signal can Conditional Access evaluate when deciding whether to allow a sign-in?",
            choices=[
                ("a", "Device compliance state"),
                ("b", "The organization's ISO certificate PDF"),
                ("c", "The color of a sensitivity label ribbon"),
                ("d", "The number of Key Vault secrets"),
            ],
            correct="a",
            explanation="Device compliance is a classic Conditional Access condition. ISO PDFs, label colors, and secret counts are not CA signals.",
            source_id="module-explore-access-management-capabilities",
            semantic_family_id="conditional_access_and_identity_protection",
            tested_decision="ca_evaluates_device_compliance",
            batch=b,
        ),
        question_record(
            serial=56,
            leaf="entra_roles_rbac",
            difficulty="beginner",
            stem_style="short_scenario",
            stem="A technician only needs to reset user passwords. Which approach follows Entra RBAC least privilege?",
            choices=[
                ("a", "Assign a role that includes password reset without granting Global Administrator"),
                ("b", "Share the Global Administrator password in chat"),
                ("c", "Disable Conditional Access for everyone"),
                ("d", "Open RDP to the internet"),
            ],
            correct="a",
            explanation="Entra roles exist so password-reset work does not require Global Administrator. Sharing GA credentials is the opposite of least privilege.",
            source_id="doc-entra-rbac",
            semantic_family_id="entra_roles_rbac",
            tested_decision="password_reset_role_not_ga",
            batch=b,
        ),
        question_record(
            serial=57,
            leaf="entra_id_governance",
            difficulty="beginner",
            stem_style="direct_concept",
            stem="What is entitlement management in Microsoft Entra ID Governance used for?",
            choices=[
                ("a", "Packaging resources into access packages that users can request"),
                ("b", "Scrubbing volumetric network floods"),
                ("c", "Scanning endpoints for malware"),
                ("d", "Publishing Microsoft SOC reports"),
            ],
            correct="a",
            explanation="Entitlement management packages groups, apps, and sites into requestable access packages. The other options are network, XDR, or trust-portal jobs.",
            source_id="doc-id-governance",
            semantic_family_id="entra_id_governance_and_access_reviews",
            tested_decision="entitlement_management_access_packages",
            batch=b,
        ),
        question_record(
            serial=58,
            leaf="access_reviews",
            difficulty="beginner",
            stem_style="short_scenario",
            stem="Guest accounts piled up in a Teams-connected group. Which Entra capability asks reviewers whether those guests still need access?",
            choices=[
                ("a", "Access reviews"),
                ("b", "Azure WAF"),
                ("c", "Defender for Endpoint"),
                ("d", "DDoS Protection"),
            ],
            correct="a",
            explanation="Access reviews recertify guest and group access. WAF, endpoint detection, and DDoS Protection do not recertify group membership.",
            source_id="doc-access-reviews",
            semantic_family_id="entra_id_governance_and_access_reviews",
            tested_decision="reviews_for_guest_group_cleanup",
            batch=b,
        ),
        question_record(
            serial=59,
            leaf="privileged_identity_management",
            difficulty="intermediate",
            stem_style="misconception_correction",
            stem="Which statement about PIM is correct?",
            choices=[
                ("a", "PIM can require approval and a time limit when activating a privileged role"),
                ("b", "PIM is a replacement for virtual networks"),
                ("c", "PIM classifies credit-card data in emails"),
                ("d", "PIM is only a WAF managed rule set"),
            ],
            correct="a",
            explanation="PIM activation can include approval, MFA, and duration. It is not networking, DLP classification, or WAF.",
            source_id="doc-pim",
            semantic_family_id="privileged_identity_management",
            tested_decision="pim_approval_and_duration",
            batch=b,
        ),
        question_record(
            serial=60,
            leaf="entra_id_protection",
            difficulty="beginner",
            stem_style="direct_concept",
            stem="Leaked credentials appearing in attacker dumps are an example of which Entra capability's detections?",
            choices=[
                ("a", "Microsoft Entra ID Protection"),
                ("b", "Azure Key Vault access policies only"),
                ("c", "Purview records disposition"),
                ("d", "Azure Bastion shareable links"),
            ],
            correct="a",
            explanation="ID Protection includes leaked-credential and other identity-risk detections.",
            source_id="doc-id-protection",
            semantic_family_id="conditional_access_and_identity_protection",
            tested_decision="leaked_credentials_are_id_protection",
            batch=b,
        ),
        question_record(
            serial=61,
            leaf="identity_types_including_agent_id",
            difficulty="beginner",
            stem_style="service_selection",
            stem="A daemon application needs its own identity to call Microsoft Graph without a signed-in user. Which identity type is that?",
            choices=[
                ("a", "A workload or application identity"),
                ("b", "A sensitivity label"),
                ("c", "An NSG"),
                ("d", "A retention label"),
            ],
            correct="a",
            explanation="Apps and workloads use application/workload identities (and related credentials) rather than a human user sign-in.",
            source_id="module-explore-basic-services-identity-types",
            semantic_family_id="identity_types_including_agent_id",
            tested_decision="workload_app_identity_no_user",
            batch=b,
        ),
        question_record(
            serial=62,
            leaf="hybrid_identity",
            difficulty="intermediate",
            stem_style="short_scenario",
            stem="Password hash synchronization is being considered so users can sign in to cloud apps with the same password they use on-premises. Which capability area is this part of?",
            choices=[
                ("a", "Hybrid identity"),
                ("b", "Insider Risk Management"),
                ("c", "Azure DDoS Protection"),
                ("d", "Content explorer"),
            ],
            correct="a",
            explanation="Password hash sync is a hybrid identity authentication method that lets Entra ID verify hashes derived from on-premises passwords.",
            source_id="module-explore-basic-services-identity-types",
            semantic_family_id="entra_hybrid_identity_and_ad",
            tested_decision="password_hash_sync_is_hybrid",
            batch=b,
        ),
        question_record(
            serial=63,
            leaf="authentication_methods",
            difficulty="beginner",
            stem_style="misconception_correction",
            stem="Which statement about Temporary Access Pass is correct?",
            choices=[
                (
                    "a",
                    "It is a time-limited passcode for sign-in and method registration, not a standing directory role",
                ),
                ("b", "It is a Global Administrator role"),
                ("c", "It is a DLP location"),
                ("d", "It is a Sentinel table"),
            ],
            correct="a",
            explanation="TAP is an authentication method with a lifetime. It is not a directory role, DLP location, or SIEM table.",
            source_id="doc-temporary-access-pass",
            semantic_family_id="authentication_methods",
            tested_decision="tap_is_not_a_directory_role",
            batch=b,
        ),
        question_record(
            serial=64,
            leaf="multifactor_authentication",
            difficulty="intermediate",
            stem_style="short_scenario",
            stem="A policy requires MFA only for administrators. Which Microsoft Entra feature is commonly used to scope that requirement?",
            choices=[
                ("a", "Conditional Access targeting directory roles"),
                ("b", "Azure WAF custom rules"),
                ("c", "Purview audit search"),
                ("d", "Key Vault soft-delete"),
            ],
            correct="a",
            explanation="Conditional Access can target users or roles and then require MFA. WAF, audit search, and Key Vault soft-delete do not issue MFA challenges.",
            source_id="doc-mfa",
            semantic_family_id="multifactor_authentication",
            tested_decision="mfa_scoped_with_conditional_access",
            batch=b,
        ),
        question_record(
            serial=65,
            leaf="password_protection_management",
            difficulty="intermediate",
            stem_style="short_scenario",
            stem="The company name and product names keep appearing in user passwords. Which control can reject those custom weak terms?",
            choices=[
                ("a", "Microsoft Entra Password Protection custom banned password list"),
                ("b", "Azure Bastion diagnostic settings"),
                ("c", "Defender TI WHOIS lookup"),
                ("d", "eDiscovery hold"),
            ],
            correct="a",
            explanation="Password Protection accepts custom banned terms so organization-specific weak passwords are rejected.",
            source_id="doc-password-protection",
            semantic_family_id="password_protection_management",
            tested_decision="custom_banned_terms_company_name",
            batch=b,
        ),
        question_record(
            serial=66,
            leaf="conditional_access",
            difficulty="intermediate",
            stem_style="short_scenario",
            stem="The security team wants to block legacy authentication protocols that cannot perform MFA. Which Entra capability is designed for that access decision?",
            choices=[
                ("a", "Conditional Access"),
                ("b", "Records management"),
                ("c", "Azure DDoS Protection"),
                ("d", "Content explorer"),
            ],
            correct="a",
            explanation="Conditional Access can block client apps/legacy protocols that cannot satisfy modern authentication controls such as MFA.",
            source_id="doc-conditional-access",
            semantic_family_id="conditional_access_and_identity_protection",
            tested_decision="ca_blocks_legacy_auth",
            batch=b,
        ),
        question_record(
            serial=67,
            leaf="entra_roles_rbac",
            difficulty="intermediate",
            stem_style="short_scenario",
            stem="A custom Entra role is created with only the permissions needed to manage groups. What principle does that apply?",
            choices=[
                ("a", "Least privilege"),
                ("b", "Defense-in-depth physical cameras"),
                ("c", "Hashing"),
                ("d", "Data residency"),
            ],
            correct="a",
            explanation="Custom Entra roles exist to grant only required directory permissions, which is least privilege.",
            source_id="doc-entra-rbac",
            semantic_family_id="entra_roles_rbac",
            tested_decision="custom_entra_role_least_privilege",
            batch=b,
        ),
        question_record(
            serial=68,
            leaf="entra_id_governance",
            difficulty="intermediate",
            stem_style="concept_distinction",
            stem="Which Entra ID Governance pairing is accurate?",
            choices=[
                (
                    "a",
                    "Lifecycle Workflows automate joiner/mover/leaver tasks; access reviews recertify whether access is still needed",
                ),
                ("b", "Lifecycle Workflows mitigate DDoS; access reviews encrypt disks"),
                ("c", "Both replace Microsoft Entra ID"),
                ("d", "Both are Azure Firewall SKUs"),
            ],
            correct="a",
            explanation="Those two ID Governance capabilities cover automation of lifecycle versus periodic recertification.",
            source_id="doc-lifecycle-workflows",
            semantic_family_id="entra_id_governance_and_access_reviews",
            tested_decision="workflows_vs_reviews_pairing",
            batch=b,
        ),
        question_record(
            serial=69,
            leaf="privileged_identity_management",
            difficulty="beginner",
            stem_style="capability_selection",
            stem="Which capability can send an alert when a privileged role is activated?",
            choices=[
                ("a", "Privileged Identity Management"),
                ("b", "Sensitivity label headers"),
                ("c", "Azure WAF bot manager only"),
                ("d", "Activity explorer file lists"),
            ],
            correct="a",
            explanation="PIM includes monitoring and alerting around privileged role activation and assignment.",
            source_id="module-describe-identity-protection-governance-capabilities",
            semantic_family_id="privileged_identity_management",
            tested_decision="pim_alerts_on_activation",
            batch=b,
        ),
        question_record(
            serial=70,
            leaf="entra_id_protection",
            difficulty="intermediate",
            stem_style="concept_distinction",
            stem="How does Entra ID Protection differ from Microsoft Defender for Identity at a fundamentals level?",
            choices=[
                (
                    "a",
                    "ID Protection focuses on Entra sign-in and identity risk; Defender for Identity focuses on Active Directory identity threats such as lateral movement",
                ),
                ("b", "They are both Azure Firewall policies"),
                ("c", "ID Protection is only a retention label"),
                ("d", "Defender for Identity issues FIDO2 keys"),
            ],
            correct="a",
            explanation="ID Protection is cloud identity risk. Defender for Identity analyzes AD DS-style identity attacks. Both are identity-security related but not the same product.",
            source_id="doc-id-protection",
            semantic_family_id="conditional_access_and_identity_protection",
            tested_decision="id_protection_vs_defender_for_identity",
            batch=b,
        ),
        question_record(
            serial=71,
            leaf="entra_id_overview",
            difficulty="beginner",
            stem_style="short_scenario",
            stem="Developers want users to sign in to a custom app with work accounts already in Microsoft 365. Which directory should the app trust?",
            choices=[
                ("a", "Microsoft Entra ID"),
                ("b", "Azure DDoS Protection"),
                ("c", "Purview Content explorer"),
                ("d", "Microsoft Sentinel"),
            ],
            correct="a",
            explanation="Custom apps trust Entra ID as the identity provider for work accounts. DDoS, Content explorer, and Sentinel are not directories.",
            source_id="module-explore-basic-services-identity-types",
            semantic_family_id="entra_hybrid_identity_and_ad",
            tested_decision="apps_trust_entra_for_work_accounts",
            batch=b,
        ),
        question_record(
            serial=72,
            leaf="identity_types_including_agent_id",
            difficulty="beginner",
            stem_style="direct_concept",
            stem="A laptop that must be recognized during Conditional Access is an example of which identity type?",
            choices=[
                ("a", "Device identity"),
                ("b", "A retention label"),
                ("c", "A DDoS policy"),
                ("d", "A WAF managed rule"),
            ],
            correct="a",
            explanation="Devices can have identities in Entra ID so compliance and access policies can evaluate them.",
            source_id="module-explore-basic-services-identity-types",
            semantic_family_id="identity_types_including_agent_id",
            tested_decision="device_identity_for_ca",
            batch=b,
        ),
        question_record(
            serial=73,
            leaf="access_reviews",
            difficulty="intermediate",
            stem_style="misconception_correction",
            stem="Which statement about access reviews is correct?",
            choices=[
                ("a", "They can remove access that is no longer justified after reviewers decide"),
                ("b", "They patch guest operating systems in IaaS"),
                ("c", "They replace encryption keys in Key Vault automatically as their only job"),
                ("d", "They are Azure Firewall application rules"),
            ],
            correct="a",
            explanation="Reviewers can approve or deny continued access, and denied access can be removed. OS patching, Key Vault rotation, and firewall rules are different controls.",
            source_id="module-describe-identity-protection-governance-capabilities",
            semantic_family_id="entra_id_governance_and_access_reviews",
            tested_decision="reviews_can_remove_unjustified_access",
            batch=b,
        ),
        question_record(
            serial=74,
            leaf="entra_roles_rbac",
            difficulty="beginner",
            stem_style="direct_concept",
            stem="What does assigning a Microsoft Entra role control?",
            choices=[
                ("a", "Directory and identity-administration permissions in Entra ID"),
                ("b", "Layer 3/4 DDoS mitigation only"),
                ("c", "Whether a file is a record"),
                ("d", "Whether a VM has a public IP"),
            ],
            correct="a",
            explanation="Entra roles grant identity-administration permissions. DDoS, records, and public IPs are other planes.",
            source_id="doc-entra-rbac",
            semantic_family_id="entra_roles_rbac",
            tested_decision="entra_role_controls_directory_admin",
            batch=b,
        ),
        question_record(
            serial=75,
            leaf="authentication_methods",
            difficulty="beginner",
            stem_style="capability_selection",
            stem="Certificate-based authentication in Entra ID is an example of which factor category?",
            choices=[
                ("a", "Something you have (a certificate on a device or smart card)"),
                ("b", "A Purview audit record"),
                ("c", "A WAF exclusion"),
                ("d", "A Sentinel bookmark"),
            ],
            correct="a",
            explanation="Certificates are possession factors used as an Entra authentication method.",
            source_id="doc-authentication-methods",
            semantic_family_id="authentication_methods",
            tested_decision="certificate_auth_is_possession_factor",
            batch=b,
        ),
    ]
