from __future__ import annotations

from tools.sc900_microsoft_corpus_qemit import question_record


def batch_10() -> list[dict]:
    b = "mlc-batch-10"
    return [
        question_record(
            serial=226,
            leaf="entra_roles_rbac",
            difficulty="intermediate",
            stem_style="concept_distinction",
            stem="A cloud operator needs to start and stop virtual machines in a subscription but should not manage users in Microsoft Entra ID. Which access model fits?",
            choices=[
                ("a", "Azure resource RBAC for the subscription or resource group, not an Entra directory role"),
                ("b", "Global Administrator, because Azure VM power-state is a directory setting"),
                ("c", "A sensitivity label published to the operator"),
                ("d", "Microsoft Sentinel hunting queries, which grant VM start rights"),
            ],
            correct="a",
            explanation="Azure RBAC authorizes Azure resource actions such as VM operations. Entra roles authorize directory administration. Those planes are not interchangeable.",
            source_id="doc-entra-rbac",
            semantic_family_id="entra_roles_rbac",
            tested_decision="azure_resource_rbac_not_entra_directory_role",
            misconception_target="global_admin_required_for_vm_operations",
            batch=b,
        ),
        question_record(
            serial=227,
            leaf="entra_id_governance",
            difficulty="intermediate",
            stem_style="short_scenario",
            stem="On an employee's first day, security wants an automated workflow to create the Entra account, add a welcome group, and send a manager task. Which ID Governance capability is designed for that joiner path?",
            choices=[
                ("a", "Lifecycle workflows that automate joiner, mover, and leaver identity tasks"),
                ("b", "Azure Firewall DNAT rules that create users when port 443 is allowed"),
                ("c", "Defender Threat Intelligence actor profiles"),
                ("d", "Network security groups that provision mailboxes"),
            ],
            correct="a",
            explanation="Lifecycle workflows automate joiner-mover-leaver identity tasks. Firewall, threat intelligence, and NSGs do not provision Entra joiner processes.",
            source_id="doc-lifecycle-workflows",
            semantic_family_id="entra_id_governance_and_access_reviews",
            tested_decision="lifecycle_workflows_joiner_automation",
            batch=b,
        ),
        question_record(
            serial=228,
            leaf="entra_id_governance",
            difficulty="intermediate",
            stem_style="concept_distinction",
            stem="Users should request a bundle of groups, apps, and roles for a project, with approval and a time limit. How does that differ from Privileged Identity Management?",
            choices=[
                (
                    "a",
                    "Entitlement management packages project access for users; PIM activates privileged directory or Azure roles just in time",
                ),
                (
                    "b",
                    "Entitlement management is only for Global Administrators, and PIM is only for guest password reset",
                ),
                ("c", "Both capabilities are Azure WAF policies with different names"),
                ("d", "PIM publishes sensitivity labels, and entitlement management is a DDoS plan"),
            ],
            correct="a",
            explanation="Entitlement management issues access packages. PIM governs activation of privileged roles. They are related governance tools with different jobs.",
            source_id="doc-id-governance",
            semantic_family_id="entra_id_governance_and_access_reviews",
            tested_decision="entitlement_packages_vs_pim_privileged_activation",
            batch=b,
        ),
        question_record(
            serial=229,
            leaf="access_reviews",
            difficulty="intermediate",
            stem_style="concept_distinction",
            stem="Group owners must periodically confirm that guests still need a project group. Why is that not the same as Privileged Identity Management?",
            choices=[
                (
                    "a",
                    "Access reviews recertify whether existing access should continue; PIM activates privileged roles just in time",
                ),
                ("b", "Access reviews are the only way to require MFA on role activation"),
                ("c", "PIM recertifies guest groups, and access reviews encrypt virtual machines"),
                ("d", "They are identical services with two marketing names"),
            ],
            correct="a",
            explanation="Access reviews ask whether current access is still justified. PIM is about time-bound privileged-role activation, not guest-group recertification.",
            source_id="doc-access-reviews",
            semantic_family_id="entra_id_governance_and_access_reviews",
            tested_decision="reviews_recertify_access_pim_activates_privilege",
            batch=b,
        ),
        question_record(
            serial=230,
            leaf="entra_id_protection",
            difficulty="intermediate",
            stem_style="short_scenario",
            stem="A user's risk is high because leaked credentials were found. Security wants that user blocked or forced to a secure password reset before further access. Which pairing is appropriate?",
            choices=[
                ("a", "ID Protection risk combined with Conditional Access user-risk policy"),
                ("b", "Azure Bastion session recording as the leaked-credential control"),
                ("c", "Records management file-plan disposition"),
                ("d", "Defender for Office 365 Safe Attachments as the only leaked-credential control"),
            ],
            correct="a",
            explanation="ID Protection calculates identity risk and Conditional Access can require remediation such as password reset or block. Bastion, records, and Safe Attachments are not leaked-credential identity-risk engines.",
            source_id="doc-id-protection",
            semantic_family_id="conditional_access_and_identity_protection",
            tested_decision="id_protection_risk_remediation_via_ca",
            batch=b,
        ),
        question_record(
            serial=231,
            leaf="hybrid_identity",
            difficulty="intermediate",
            stem_style="capability_selection",
            stem="A company already uses AD FS and wants cloud apps to trust those on-premises federation claims. Which hybrid identity option is that?",
            choices=[
                ("a", "Federation with an on-premises identity provider such as AD FS"),
                ("b", "Password hash synchronization only, which never uses federation"),
                ("c", "Microsoft Defender for Cloud Apps session policy as the directory sync engine"),
                ("d", "Compliance Manager improvement actions that issue SAML tokens"),
            ],
            correct="a",
            explanation="Hybrid identity can federate authentication to AD FS or another IdP. PHS is a different cloud-auth path, and Defender for Cloud Apps or Compliance Manager are not federation engines.",
            source_id="doc-hybrid-identity",
            semantic_family_id="entra_hybrid_identity_and_ad",
            tested_decision="hybrid_federation_adfs_claims_trust",
            batch=b,
        ),
        question_record(
            serial=232,
            leaf="password_protection_management",
            difficulty="intermediate",
            stem_style="short_scenario",
            stem="Hybrid users reset passwords in the cloud and must have the new password written back to on-premises Active Directory. Which password-management capability is required?",
            choices=[
                ("a", "Self-service password reset with password writeback"),
                ("b", "Azure Key Vault access policies that rewrite AD DS passwords"),
                ("c", "eDiscovery holds that push password hashes to domain controllers"),
                ("d", "Azure WAF custom rules that perform directory writeback"),
            ],
            correct="a",
            explanation="SSPR with password writeback updates on-premises AD after a cloud reset. Key Vault, eDiscovery, and WAF do not write hybrid passwords back to AD DS.",
            source_id="doc-sspr",
            semantic_family_id="password_protection_management",
            tested_decision="sspr_password_writeback_for_hybrid",
            batch=b,
        ),
        question_record(
            serial=233,
            leaf="authentication_methods",
            difficulty="intermediate",
            stem_style="capability_selection",
            stem="Security wants phishing-resistant sign-in for admins and is willing to retire SMS one-time codes for those accounts. Which comparison is accurate at SC-900 level?",
            choices=[
                (
                    "a",
                    "FIDO2 security keys are phishing-resistant possession methods; SMS codes are easier to intercept or phish",
                ),
                ("b", "SMS one-time codes are more phishing-resistant than FIDO2 keys"),
                ("c", "SMS codes are retention labels, and FIDO2 keys are NSG rules"),
                ("d", "Phishing resistance is measured only by compliance score"),
            ],
            correct="a",
            explanation="Microsoft treats FIDO2/passkeys as phishing-resistant. SMS can still be phished or intercepted, so it is a weaker authentication method for high-value accounts.",
            source_id="doc-authentication-methods",
            semantic_family_id="authentication_methods",
            tested_decision="fido2_more_phishing_resistant_than_sms",
            batch=b,
        ),
        question_record(
            serial=234,
            leaf="conditional_access",
            difficulty="intermediate",
            stem_style="misconception_correction",
            stem="A compliance analyst says Conditional Access can classify a Word document as confidential and prevent it from being emailed. What is the accurate correction?",
            choices=[
                (
                    "a",
                    "Conditional Access evaluates sign-in conditions and grant or session controls; classification and email DLP are Purview capabilities",
                ),
                ("b", "Conditional Access is the only Microsoft service that applies sensitivity labels"),
                ("c", "Conditional Access declares records and therefore blocks all email"),
                ("d", "Conditional Access is a Defender for Office 365 Safe Links wrapper"),
            ],
            correct="a",
            explanation="Conditional Access is an identity policy engine. Labeling and DLP protect content. Using CA as a substitute for Purview information protection is a category error.",
            source_id="doc-conditional-access",
            semantic_family_id="conditional_access_and_identity_protection",
            tested_decision="ca_is_not_purview_classification_or_dlp",
            misconception_target="conditional_access_labels_documents",
            batch=b,
        ),
        question_record(
            serial=235,
            leaf="entra_id_overview",
            difficulty="intermediate",
            stem_style="short_scenario",
            stem="Developers currently store usernames and passwords inside each line-of-business app. Security wants one cloud directory those apps can trust instead. Which service is the SC-900 answer?",
            choices=[
                ("a", "Microsoft Entra ID as the cloud identity and access management directory"),
                ("b", "Azure DDoS Protection as the application identity store"),
                ("c", "Microsoft Purview Activity explorer as the token issuer"),
                ("d", "Azure Bastion as the organizational identity provider"),
            ],
            correct="a",
            explanation="Entra ID is the cloud IAM directory apps can trust. DDoS Protection, Activity explorer, and Bastion are not identity directories.",
            source_id="doc-entra-what-is",
            semantic_family_id="entra_hybrid_identity_and_ad",
            tested_decision="entra_replaces_per_app_password_stores",
            batch=b,
        ),
        question_record(
            serial=236,
            leaf="identity_types_including_agent_id",
            difficulty="intermediate",
            stem_style="concept_distinction",
            stem="A background integration uses a registered application identity with no human signing in. How does that identity type differ from a user account?",
            choices=[
                (
                    "a",
                    "Workload or application identities represent apps or services, not a person who interactively signs in",
                ),
                ("b", "Workload identities are guest users who must complete MFA every hour"),
                ("c", "Application identities are sensitivity labels attached to service principals"),
                ("d", "Only user accounts can be granted Azure RBAC roles; apps cannot have identities"),
            ],
            correct="a",
            explanation="Workload/app identities authenticate services without a human sign-in. They are not guests, labels, or a prohibition on app authorization.",
            source_id="doc-entra-identity-types",
            semantic_family_id="identity_types_including_agent_id",
            tested_decision="workload_identity_is_not_interactive_user",
            batch=b,
        ),
        question_record(
            serial=237,
            leaf="entra_roles_rbac",
            difficulty="intermediate",
            stem_style="short_scenario",
            stem="Helpdesk should reset user passwords but must not manage billing or Conditional Access policies. Which Entra practice matches least privilege?",
            choices=[
                ("a", "Assign a built-in password-administration role instead of Global Administrator"),
                ("b", "Assign Global Administrator and then hide the billing blade in the portal"),
                ("c", "Assign Azure Firewall Contributor, which includes password reset"),
                ("d", "Assign Compliance Manager assessor, which resets Entra passwords"),
            ],
            correct="a",
            explanation="Entra built-in roles such as password administration target a job without standing Global Administrator. Hiding blades or using firewall/compliance roles does not implement directory least privilege.",
            source_id="doc-entra-rbac",
            semantic_family_id="entra_roles_rbac",
            tested_decision="password_admin_role_instead_of_hiding_ga_blades",
            misconception_target="hide_portal_blades_equals_least_privilege",
            batch=b,
        ),
        question_record(
            serial=238,
            leaf="multifactor_authentication",
            difficulty="intermediate",
            stem_style="short_scenario",
            stem="A user completes MFA and is then denied access to a finance SharePoint site. A helpdesk agent says MFA failure is the only possible explanation. What is the better reading?",
            choices=[
                ("a", "MFA succeeded as authentication; a separate authorization decision still denied the site"),
                ("b", "MFA encrypts SharePoint libraries, so denial means hashing failed"),
                ("c", "MFA is a DLP policy that deletes site permissions"),
                ("d", "MFA recertifies guest groups, which is the only SharePoint authorization model"),
            ],
            correct="a",
            explanation="MFA is an authentication strength control. SharePoint access is still authorized by permissions, groups, or Conditional Access grant outcomes. Completing MFA does not grant every site.",
            source_id="doc-mfa",
            semantic_family_id="multifactor_authentication",
            tested_decision="mfa_success_is_not_sharepoint_authorization",
            misconception_target="mfa_is_the_only_access_decision",
            batch=b,
        ),
        question_record(
            serial=239,
            leaf="access_reviews",
            difficulty="intermediate",
            stem_style="short_scenario",
            stem="A team used a temporary SharePoint group for a six-week audit. After the audit, owners should be forced to keep or remove remaining members. Which governance control is that recertification?",
            choices=[
                ("a", "An access review on the group's membership"),
                ("b", "A Defender for Cloud secure-score recommendation"),
                ("c", "An Azure Firewall threat-intelligence rule"),
                ("d", "A Temporary Access Pass issued to the group"),
            ],
            correct="a",
            explanation="Access reviews recertify group membership after a project ends. Secure score, firewall TI, and TAP do not recertify SharePoint group members.",
            source_id="doc-access-reviews",
            semantic_family_id="entra_id_governance_and_access_reviews",
            tested_decision="reviews_recertify_temporary_project_group",
            batch=b,
        ),
        question_record(
            serial=240,
            leaf="entra_id_governance",
            difficulty="intermediate",
            stem_style="capability_selection",
            stem="Which Microsoft Entra ID Governance family includes access packages, access reviews, Privileged Identity Management, and lifecycle workflows?",
            choices=[
                ("a", "Microsoft Entra ID Governance identity-governance capabilities"),
                ("b", "Microsoft Defender XDR email workloads"),
                ("c", "Azure virtual network segmentation"),
                ("d", "Microsoft Purview records management"),
            ],
            correct="a",
            explanation="ID Governance is the family that groups entitlement management, access reviews, PIM, and lifecycle workflows. XDR, VNets, and records management are different solution areas.",
            source_id="doc-id-governance",
            semantic_family_id="entra_id_governance_and_access_reviews",
            tested_decision="id_governance_family_includes_packages_reviews_pim_workflows",
            batch=b,
        ),
        question_record(
            serial=241,
            leaf="privileged_identity_management",
            difficulty="intermediate",
            stem_style="concept_distinction",
            stem="An auditor asks whether anyone permanently holds Privileged Role Administrator. Security wants assignments to stay eligible until a person activates them. Which PIM idea is that?",
            choices=[
                ("a", "Eligible assignments instead of permanent active privileged assignments"),
                ("b", "Publishing a sensitivity label named Eligible Admin"),
                ("c", "Placing the directory in eDiscovery hold to remove standing roles"),
                ("d", "Using Azure Bastion native client as the privileged-role catalog"),
            ],
            correct="a",
            explanation="PIM eligible assignments avoid standing active privilege until activation. Labels, eDiscovery, and Bastion do not convert directory roles to eligible.",
            source_id="doc-pim",
            semantic_family_id="privileged_identity_management",
            tested_decision="pim_eligible_assignment_not_permanent_active",
            batch=b,
        ),
        question_record(
            serial=242,
            leaf="conditional_access",
            difficulty="intermediate",
            stem_style="short_scenario",
            stem="A payroll app should be reachable from iOS and Android managed devices but blocked from unmanaged Windows PCs. Which Conditional Access condition supports that split?",
            choices=[
                ("a", "Device platform conditions that include or exclude operating systems"),
                ("b", "A Key Vault secret named LegacyAuth"),
                ("c", "A DLP policy that classifies Windows as a sensitive information type"),
                ("d", "A Defender Vulnerability Management browser update"),
            ],
            correct="a",
            explanation="Conditional Access can use device platform as a condition. Key Vault, DLP SITs, and vulnerability management do not select OS platforms for app access.",
            source_id="doc-conditional-access",
            semantic_family_id="conditional_access_and_identity_protection",
            tested_decision="ca_device_platform_as_condition",
            batch=b,
        ),
        question_record(
            serial=243,
            leaf="federation",
            difficulty="intermediate",
            stem_style="short_scenario",
            stem="Your app does not authenticate partner employees directly. It accepts tokens from the partner's identity provider over a configured trust. Which identity concept is in use?",
            choices=[
                ("a", "Federation, in which a relying party trusts claims from an external identity provider"),
                ("b", "Hashing, in which the app decrypts partner passwords"),
                ("c", "Cloud workload protection, in which tokens are server threat detections"),
                ("d", "Records management, in which tokens are declared records"),
            ],
            correct="a",
            explanation="Federation lets a relying party trust another organization's IdP. Hashing, CWP, and records management are not token-trust relationships.",
            source_id="module-describe-identity-principles-concepts",
            semantic_family_id="federation_and_identity_providers",
            tested_decision="relying_party_trusts_partner_idp_claims",
            batch=b,
        ),
        question_record(
            serial=244,
            leaf="identity_providers",
            difficulty="intermediate",
            stem_style="misconception_correction",
            stem="A developer says every application must store and validate its own passwords to be secure. Which identity-provider correction is accurate?",
            choices=[
                ("a", "Apps can trust an identity provider such as Entra ID instead of storing passwords locally"),
                ("b", "Identity providers are only for DDoS logs and cannot authenticate people"),
                ("c", "Storing passwords in each app is required before Conditional Access can work"),
                ("d", "Identity providers replace encryption, so apps should disable TLS"),
            ],
            correct="a",
            explanation="A central identity provider authenticates users and issues tokens. Local password stores in every app are not a security requirement and increase credential sprawl.",
            source_id="module-describe-identity-principles-concepts",
            semantic_family_id="federation_and_identity_providers",
            tested_decision="apps_need_not_store_local_passwords",
            misconception_target="each_app_must_store_passwords",
            batch=b,
        ),
        question_record(
            serial=245,
            leaf="azure_key_vault",
            difficulty="intermediate",
            stem_style="short_scenario",
            stem="An application needs a TLS certificate and a database connection string at runtime, and developers must not check those values into Git. Which Azure service is designed to store both?",
            choices=[
                ("a", "Azure Key Vault, which stores secrets, keys, and certificates"),
                ("b", "Microsoft Entra access reviews"),
                ("c", "Privileged Identity Management activation alerts"),
                ("d", "Purview Content explorer"),
            ],
            correct="a",
            explanation="Key Vault stores secrets, keys, and certificates so apps retrieve them at runtime instead of embedding them in source control. Access reviews, PIM alerts, and Content explorer are not secret stores.",
            source_id="doc-key-vault",
            semantic_family_id="azure_key_vault",
            tested_decision="key_vault_runtime_store_for_secrets_keys_certs",
            batch=b,
        ),
        question_record(
            serial=246,
            leaf="azure_firewall",
            difficulty="intermediate",
            stem_style="concept_distinction",
            stem="A hub must filter TCP/UDP flows between virtual networks, while a public website also needs inspection of HTTP cookies and request bodies. Which pairing is accurate?",
            choices=[
                ("a", "Azure Firewall filters network flows; Azure WAF inspects HTTP application requests"),
                ("b", "Azure WAF is the only service that can filter virtual-network TCP flows in a hub"),
                ("c", "Azure Firewall recertifies guest users, and WAF issues MFA challenges"),
                ("d", "Firewall and WAF are both Microsoft Defender for Identity sensors"),
            ],
            correct="a",
            explanation="Azure Firewall is a network-layer (and related) traffic filter. WAF inspects HTTP application payloads. They address different layers and are not identity sensors.",
            source_id="doc-azure-firewall",
            semantic_family_id="azure_nsg_firewall_waf_ddos",
            tested_decision="azure_firewall_network_vs_waf_http_inspection",
            batch=b,
        ),
        question_record(
            serial=247,
            leaf="azure_ddos_protection",
            difficulty="intermediate",
            stem_style="concept_distinction",
            stem="A public website stays online during a large volumetric flood, but users can still be phished by a fake sign-in page. What does that illustrate about Azure DDoS Protection?",
            choices=[
                (
                    "a",
                    "DDoS Protection helps availability against floods; it does not by itself stop identity phishing or application-layer abuse",
                ),
                ("b", "DDoS Protection replaces Microsoft Entra multifactor authentication"),
                ("c", "DDoS Protection classifies and encrypts SharePoint files"),
                ("d", "A surviving public IP means Conditional Access is no longer required"),
            ],
            correct="a",
            explanation="DDoS Protection is an availability control against volumetric attacks. It is not an identity, labeling, or phishing control.",
            source_id="doc-ddos",
            semantic_family_id="azure_nsg_firewall_waf_ddos",
            tested_decision="ddos_availability_not_phishing_or_identity",
            batch=b,
        ),
        question_record(
            serial=248,
            leaf="network_security_groups",
            difficulty="intermediate",
            stem_style="short_scenario",
            stem="An NSG allows TCP 443 to a web subnet. Attackers then send SQL injection in HTTPS bodies. Why might that NSG still be insufficient?",
            choices=[
                (
                    "a",
                    "NSGs filter ports and addresses; they do not inspect HTTP application payloads the way a WAF does",
                ),
                ("b", "NSGs decrypt TLS and therefore already block injection"),
                ("c", "An allow-443 NSG is equivalent to Microsoft Entra ID Protection"),
                ("d", "SQL injection is remediated only by Service Trust Portal reports"),
            ],
            correct="a",
            explanation="NSGs are network allow/deny filters. Application-layer inspection of HTTP payloads is a WAF job. Opening 443 does not imply payload inspection.",
            source_id="doc-nsg",
            semantic_family_id="azure_nsg_firewall_waf_ddos",
            tested_decision="nsg_filters_ports_not_http_payloads",
            batch=b,
        ),
        question_record(
            serial=249,
            leaf="azure_virtual_network_segmentation",
            difficulty="intermediate",
            stem_style="short_scenario",
            stem="A payment workload must not share the same private address space as a general development environment. Which Azure construct provides that isolation?",
            choices=[
                ("a", "Separate virtual networks or subnets that segment the workloads"),
                ("b", "A Temporary Access Pass issued to the payment subnet"),
                ("c", "A compliance score target of 100"),
                ("d", "Microsoft Defender Threat Intelligence articles"),
            ],
            correct="a",
            explanation="Virtual networks and subnets segment Azure resources into isolated private address spaces. TAP, compliance score, and Defender TI do not create network isolation.",
            source_id="doc-vnet",
            semantic_family_id="azure_virtual_network_segmentation",
            tested_decision="separate_vnets_or_subnets_isolate_workloads",
            batch=b,
        ),
        question_record(
            serial=250,
            leaf="azure_bastion",
            difficulty="intermediate",
            stem_style="concept_distinction",
            stem="Administrators need browser-based RDP to Azure VMs. Why is Azure Bastion a different answer from a site-to-site VPN?",
            choices=[
                (
                    "a",
                    "Bastion provides managed RDP/SSH over TLS to VMs without exposing RDP/SSH ports; a VPN extends network connectivity rather than replacing that managed jump host",
                ),
                ("b", "A VPN is the Microsoft service that opens RDP on every public IP"),
                ("c", "Bastion is an identity provider, and a VPN is a sensitivity label"),
                ("d", "Bastion and VPN are both names for Microsoft Entra Conditional Access"),
            ],
            correct="a",
            explanation="Bastion is a managed jump-host service for RDP/SSH over TLS. A VPN connects networks; it is not the SC-900 control that removes public RDP/SSH from VMs.",
            source_id="doc-bastion",
            semantic_family_id="azure_bastion",
            tested_decision="bastion_jump_host_not_the_same_as_vpn",
            batch=b,
        ),
    ]
