from __future__ import annotations

from tools.sc900_microsoft_corpus_qemit import question_record


def batch_07() -> list[dict]:
    b = "mlc-batch-07"
    return [
        question_record(
            serial=151,
            leaf="service_trust_portal_offerings",
            difficulty="beginner",
            stem_style="capability_selection",
            stem="A customer needs Microsoft's independent audit reports and compliance documentation for due diligence. Where should they look?",
            choices=[
                ("a", "The Service Trust Portal"),
                ("b", "Azure Bastion"),
                ("c", "Temporary Access Pass"),
                ("d", "Network security groups"),
            ],
            correct="a",
            explanation="The Service Trust Portal publishes Microsoft audit reports and trust documentation for customers.",
            source_id="module-describe-compliance-management-capabilities-microsoft",
            semantic_family_id="service_trust_privacy_compliance_manager",
            tested_decision="stp_for_microsoft_audit_reports",
            batch=b,
        ),
        question_record(
            serial=152,
            leaf="microsoft_privacy_principles",
            difficulty="beginner",
            stem_style="direct_concept",
            stem="Which idea is part of Microsoft's privacy principles as taught for SC-900?",
            choices=[
                ("a", "Customers should have control over their data"),
                ("b", "Customers must disable encryption"),
                ("c", "Microsoft owns all customer mailbox content as a default principle"),
                ("d", "Privacy replaces authentication"),
            ],
            correct="a",
            explanation="Microsoft privacy principles emphasize customer control and related commitments, not disabling encryption or replacing authentication.",
            source_id="module-describe-compliance-management-capabilities-microsoft",
            semantic_family_id="service_trust_privacy_compliance_manager",
            tested_decision="privacy_customer_control_of_data",
            batch=b,
        ),
        question_record(
            serial=153,
            leaf="purview_portal",
            difficulty="beginner",
            stem_style="current_topic",
            stem="Which portal is the unified Microsoft compliance and data-governance workspace for Purview solutions?",
            choices=[
                ("a", "The Microsoft Purview portal"),
                ("b", "Azure DDoS Protection"),
                ("c", "Azure Bastion"),
                ("d", "Microsoft Entra Password Protection"),
            ],
            correct="a",
            explanation="The Purview portal is the current unified compliance workspace.",
            source_id="doc-purview-portal",
            semantic_family_id="purview_portal",
            tested_decision="purview_portal_unified_compliance",
            batch=b,
        ),
        question_record(
            serial=154,
            leaf="compliance_manager",
            difficulty="beginner",
            stem_style="direct_concept",
            stem="What is Microsoft Purview Compliance Manager primarily used for?",
            choices=[
                ("a", "Assessing controls and tracking improvement actions against regulatory templates"),
                ("b", "Mitigating SYN floods"),
                ("c", "Issuing FIDO2 keys"),
                ("d", "Hosting RDP jump boxes"),
            ],
            correct="a",
            explanation="Compliance Manager helps organizations implement and track their own compliance improvement actions.",
            source_id="doc-compliance-manager",
            semantic_family_id="service_trust_privacy_compliance_manager",
            tested_decision="compliance_manager_customer_controls",
            batch=b,
        ),
        question_record(
            serial=155,
            leaf="compliance_score",
            difficulty="intermediate",
            stem_style="concept_distinction",
            stem="How does compliance score differ from Defender for Cloud secure score?",
            choices=[
                (
                    "a",
                    "Compliance score tracks Compliance Manager improvement actions; secure score tracks cloud resource security posture",
                ),
                ("b", "They are the same number stored in Key Vault"),
                ("c", "Compliance score is a DDoS metric"),
                ("d", "Secure score recertifies guests"),
            ],
            correct="a",
            explanation="The two scores measure different programs: regulatory/control improvement versus cloud configuration posture.",
            source_id="doc-compliance-score",
            semantic_family_id="service_trust_privacy_compliance_manager",
            tested_decision="compliance_score_vs_secure_score",
            batch=b,
        ),
        question_record(
            serial=156,
            leaf="data_classification",
            difficulty="beginner",
            stem_style="direct_concept",
            stem="Which Purview capability uses sensitive information types and classifiers to find personal or financial data?",
            choices=[
                ("a", "Data classification"),
                ("b", "Azure Bastion"),
                ("c", "Azure DDoS Protection"),
                ("d", "Temporary Access Pass"),
            ],
            correct="a",
            explanation="Classification finds and categorizes sensitive items so they can be protected.",
            source_id="doc-data-classification",
            semantic_family_id="purview_information_protection_lifecycle",
            tested_decision="classification_sits_and_classifiers",
            batch=b,
        ),
        question_record(
            serial=157,
            leaf="content_and_activity_explorer",
            difficulty="intermediate",
            stem_style="concept_distinction",
            stem="Which Purview explorer pairing is accurate?",
            choices=[
                (
                    "a",
                    "Content explorer shows where classified items are; Activity explorer shows what is happening to labeled or classified content",
                ),
                ("b", "Both are Azure Firewall SKUs"),
                ("c", "Content explorer issues Entra roles"),
                ("d", "Activity explorer is DDoS Protection"),
            ],
            correct="a",
            explanation="Content explorer is location/inventory of classified items; Activity explorer is operations on that content.",
            source_id="doc-activity-explorer",
            semantic_family_id="purview_information_protection_lifecycle",
            tested_decision="content_where_activity_what",
            batch=b,
        ),
        question_record(
            serial=158,
            leaf="sensitivity_labels_and_policies",
            difficulty="beginner",
            stem_style="direct_concept",
            stem="What do sensitivity labels do?",
            choices=[
                ("a", "Classify and can protect content as it travels across services"),
                ("b", "Mitigate volumetric DDoS"),
                ("c", "Activate privileged Entra roles"),
                ("d", "Open RDP ports"),
            ],
            correct="a",
            explanation="Sensitivity labels classify and can apply protection such as encryption and markings.",
            source_id="doc-sensitivity-labels",
            semantic_family_id="purview_information_protection_lifecycle",
            tested_decision="sensitivity_labels_classify_and_protect",
            batch=b,
        ),
        question_record(
            serial=159,
            leaf="data_loss_prevention",
            difficulty="beginner",
            stem_style="short_scenario",
            stem="The organization must stop credit-card numbers from being emailed outside the company. Which Purview capability is designed for that?",
            choices=[
                ("a", "Data loss prevention"),
                ("b", "Azure Bastion"),
                ("c", "DDoS Protection"),
                ("d", "Key Vault diagnostic settings"),
            ],
            correct="a",
            explanation="DLP detects and helps prevent unsafe sharing of sensitive information such as payment card data.",
            source_id="doc-dlp",
            semantic_family_id="purview_information_protection_lifecycle",
            tested_decision="dlp_blocks_outbound_pci",
            batch=b,
        ),
        question_record(
            serial=160,
            leaf="records_management",
            difficulty="beginner",
            stem_style="direct_concept",
            stem="What is the purpose of records management in Microsoft Purview?",
            choices=[
                (
                    "a",
                    "Declare items as records and apply regulatory keep-and-disposition rules that users cannot casually override",
                ),
                ("b", "Issue TAP codes"),
                ("c", "Filter NSG traffic"),
                ("d", "Hunt in Sentinel"),
            ],
            correct="a",
            explanation="Records management applies restrictive retention/disposition to declared records.",
            source_id="doc-records-management",
            semantic_family_id="purview_information_protection_lifecycle",
            tested_decision="records_restrict_edit_delete",
            batch=b,
        ),
        question_record(
            serial=161,
            leaf="retention_policies_labels",
            difficulty="beginner",
            stem_style="direct_concept",
            stem="What do retention policies and retention labels control?",
            choices=[
                ("a", "How long content is kept or deleted to meet business or legal requirements"),
                ("b", "Whether a VM has a public IP"),
                ("c", "Whether MFA is required"),
                ("d", "Whether a WAF rule is OWASP"),
            ],
            correct="a",
            explanation="Retention keeps or deletes content for a defined period. Public IPs, MFA, and WAF are other domains.",
            source_id="doc-retention",
            semantic_family_id="purview_information_protection_lifecycle",
            tested_decision="retention_keep_or_delete_period",
            batch=b,
        ),
        question_record(
            serial=162,
            leaf="insider_risk_management",
            difficulty="beginner",
            stem_style="capability_selection",
            stem="Which Purview solution looks for potentially risky activities by people inside the organization?",
            choices=[
                ("a", "Insider Risk Management"),
                ("b", "Azure DDoS Protection"),
                ("c", "Azure Firewall"),
                ("d", "Temporary Access Pass"),
            ],
            correct="a",
            explanation="Insider Risk Management is the internal-risk compliance solution.",
            source_id="doc-insider-risk",
            semantic_family_id="purview_audit_ediscovery_insider_risk",
            tested_decision="irm_internal_risky_activity",
            batch=b,
        ),
        question_record(
            serial=163,
            leaf="ediscovery",
            difficulty="beginner",
            stem_style="short_scenario",
            stem="Legal counsel needs email and files preserved and collected for a lawsuit. Which Purview capability is designed for that?",
            choices=[("a", "eDiscovery"), ("b", "Azure Bastion"), ("c", "Password Protection"), ("d", "Defender TI")],
            correct="a",
            explanation="eDiscovery finds, holds, and exports content for legal or investigative matters.",
            source_id="doc-ediscovery",
            semantic_family_id="purview_audit_ediscovery_insider_risk",
            tested_decision="ediscovery_legal_hold_collection",
            batch=b,
        ),
        question_record(
            serial=164,
            leaf="audit",
            difficulty="beginner",
            stem_style="direct_concept",
            stem="Which Purview capability records who did what, when, and where across audited activities?",
            choices=[("a", "Audit"), ("b", "Azure DDoS Protection"), ("c", "Windows Hello"), ("d", "Azure WAF")],
            correct="a",
            explanation="Audit provides an activity trail. DDoS, Windows Hello, and WAF are not activity-audit solutions.",
            source_id="doc-audit",
            semantic_family_id="purview_audit_ediscovery_insider_risk",
            tested_decision="audit_who_what_when",
            batch=b,
        ),
        question_record(
            serial=165,
            leaf="service_trust_portal_offerings",
            difficulty="intermediate",
            stem_style="concept_distinction",
            stem="Which Service Trust Portal and Compliance Manager pairing is accurate?",
            choices=[
                (
                    "a",
                    "Service Trust Portal publishes Microsoft's audit evidence; Compliance Manager tracks the customer's implemented controls",
                ),
                ("b", "Service Trust Portal is Defender XDR"),
                ("c", "Compliance Manager mitigates DDoS"),
                ("d", "Both replace Entra ID"),
            ],
            correct="a",
            explanation="STP is Microsoft's trust documentation. Compliance Manager is the customer's control implementation tracker.",
            source_id="module-describe-purview-risk-compliance-governance",
            semantic_family_id="service_trust_privacy_compliance_manager",
            tested_decision="stp_microsoft_evidence_cm_customer_actions",
            batch=b,
        ),
        question_record(
            serial=166,
            leaf="purview_portal",
            difficulty="intermediate",
            stem_style="short_scenario",
            stem="A compliance admin wants one workspace for DLP, audit, eDiscovery, and classification tools. Which portal is that in the current SC-900 material?",
            choices=[
                ("a", "The Microsoft Purview portal"),
                ("b", "Azure Bastion"),
                ("c", "The Defender portal only"),
                ("d", "Key Vault"),
            ],
            correct="a",
            explanation="Those compliance tools are reached from the Purview portal. The Defender portal is XDR operations.",
            source_id="doc-purview-portal",
            semantic_family_id="purview_portal",
            tested_decision="purview_portal_not_defender_portal",
            batch=b,
        ),
        question_record(
            serial=167,
            leaf="compliance_manager",
            difficulty="intermediate",
            stem_style="short_scenario",
            stem="An organization must show progress implementing GDPR-related improvement actions. Which Purview tool is designed for that assessment workflow?",
            choices=[
                ("a", "Compliance Manager"),
                ("b", "Azure Firewall"),
                ("c", "Defender for Endpoint"),
                ("d", "Azure Bastion"),
            ],
            correct="a",
            explanation="Compliance Manager uses assessments and improvement actions against regulatory templates such as privacy regulations.",
            source_id="doc-compliance-manager",
            semantic_family_id="service_trust_privacy_compliance_manager",
            tested_decision="cm_gdpr_improvement_actions",
            batch=b,
        ),
        question_record(
            serial=168,
            leaf="sensitivity_labels_and_policies",
            difficulty="intermediate",
            stem_style="short_scenario",
            stem="Only the legal team should see a Highly Confidential label in Office apps. What determines which labels are published to which users?",
            choices=[
                ("a", "Sensitivity label policies"),
                ("b", "NSG rules"),
                ("c", "DDoS policies"),
                ("d", "Bastion host SKUs"),
            ],
            correct="a",
            explanation="Label policies publish labels to scoped users. Network and Bastion controls do not publish labels.",
            source_id="module-describe-purview-data-solutions",
            semantic_family_id="purview_information_protection_lifecycle",
            tested_decision="label_policies_publish_to_users",
            batch=b,
        ),
        question_record(
            serial=169,
            leaf="data_loss_prevention",
            difficulty="intermediate",
            stem_style="concept_distinction",
            stem="How does DLP differ from sensitivity labels at a fundamentals level?",
            choices=[
                (
                    "a",
                    "Labels classify and can protect content; DLP detects and helps prevent risky sharing of sensitive information",
                ),
                ("b", "DLP is only a directory role"),
                ("c", "Labels mitigate DDoS"),
                ("d", "They are both Azure Firewall NAT rules"),
            ],
            correct="a",
            explanation="Labels mark/protect. DLP enforces sharing/exfiltration policies, often using those classifications.",
            source_id="doc-dlp",
            semantic_family_id="purview_information_protection_lifecycle",
            tested_decision="labels_protect_dlp_prevents_sharing",
            batch=b,
        ),
        question_record(
            serial=170,
            leaf="retention_policies_labels",
            difficulty="intermediate",
            stem_style="concept_distinction",
            stem="Which comparison between a retention policy and a retention label is accurate?",
            choices=[
                ("a", "A policy applies broadly to a location; a label can be applied to individual items"),
                ("b", "A policy is MFA; a label is WAF"),
                ("c", "They both assign Entra roles"),
                ("d", "A label is DDoS Protection"),
            ],
            correct="a",
            explanation="Policies are location-wide; labels target items, including user or auto application.",
            source_id="module-describe-purview-risk-compliance-governance",
            semantic_family_id="purview_information_protection_lifecycle",
            tested_decision="policy_location_label_item",
            batch=b,
        ),
        question_record(
            serial=171,
            leaf="records_management",
            difficulty="intermediate",
            stem_style="concept_distinction",
            stem="Why is a declared record more restrictive than an ordinary retained item?",
            choices=[
                ("a", "Record status restricts editing and deletion during the retention period"),
                ("b", "Records cannot be stored in Microsoft 365"),
                ("c", "Records disable encryption"),
                ("d", "Records replace authentication"),
            ],
            correct="a",
            explanation="Declaring a record locks down changes while retention applies. It does not forbid storage or encryption.",
            source_id="doc-records-management",
            semantic_family_id="purview_information_protection_lifecycle",
            tested_decision="record_locks_vs_ordinary_retention",
            batch=b,
        ),
        question_record(
            serial=172,
            leaf="insider_risk_management",
            difficulty="intermediate",
            stem_style="concept_distinction",
            stem="Which Insider Risk Management and eDiscovery pairing is accurate?",
            choices=[
                (
                    "a",
                    "Insider Risk Management looks for internal risky behavior; eDiscovery collects content for legal matters",
                ),
                ("b", "Both are Azure WAF policies"),
                ("c", "Insider Risk Management is DDoS Protection"),
                ("d", "eDiscovery issues TAP codes"),
            ],
            correct="a",
            explanation="Those Purview solutions address different problems: insider behavior versus legal collection.",
            source_id="doc-insider-risk",
            semantic_family_id="purview_audit_ediscovery_insider_risk",
            tested_decision="irm_behavior_vs_ediscovery_legal",
            batch=b,
        ),
        question_record(
            serial=173,
            leaf="audit",
            difficulty="intermediate",
            stem_style="concept_distinction",
            stem="Why is audit not a substitute for DLP?",
            choices=[
                (
                    "a",
                    "Audit records what happened; DLP is designed to prevent or constrain risky sharing as it happens",
                ),
                ("b", "Audit encrypts NSGs"),
                ("c", "DLP recertifies roles"),
                ("d", "They are identical"),
            ],
            correct="a",
            explanation="Audit is detective/historical. DLP is a preventive sharing control.",
            source_id="doc-audit",
            semantic_family_id="purview_audit_ediscovery_insider_risk",
            tested_decision="audit_detective_dlp_preventive",
            batch=b,
        ),
        question_record(
            serial=174,
            leaf="ediscovery",
            difficulty="intermediate",
            stem_style="concept_distinction",
            stem="Which task is eDiscovery rather than Insider Risk Management?",
            choices=[
                ("a", "Placing a legal hold on a custodian's mailbox and exporting results for counsel"),
                ("b", "Scoring whether an employee is exfiltrating files to a personal cloud"),
                ("c", "Mitigating a DDoS flood"),
                ("d", "Resetting an Entra password"),
            ],
            correct="a",
            explanation="Legal hold and export are eDiscovery. Exfiltration scoring is closer to insider risk. DDoS and password reset are unrelated.",
            source_id="module-describe-purview-risk-compliance-governance",
            semantic_family_id="purview_audit_ediscovery_insider_risk",
            tested_decision="legal_hold_is_ediscovery",
            batch=b,
        ),
        question_record(
            serial=175,
            leaf="data_classification",
            difficulty="intermediate",
            stem_style="short_scenario",
            stem="Before creating DLP or label policies, the team wants to know whether the tenant actually contains health data. Which capability answers that?",
            choices=[
                ("a", "Data classification"),
                ("b", "Azure Bastion"),
                ("c", "Privileged Identity Management"),
                ("d", "Azure Firewall"),
            ],
            correct="a",
            explanation="Classification discovers what sensitive data exists. Bastion, PIM, and Firewall do not inventory health data in content.",
            source_id="module-describe-purview-data-solutions",
            semantic_family_id="purview_information_protection_lifecycle",
            tested_decision="classify_before_dlp_to_know_what_exists",
            batch=b,
        ),
    ]
