from __future__ import annotations

from tools.sc900_microsoft_corpus_qemit import question_record


def batch_02() -> list[dict]:
    b = "mlc-batch-02"
    return [
        question_record(
            serial=26,
            leaf="password_protection_management",
            difficulty="beginner",
            stem_style="capability_selection",
            stem="Which Entra capability is designed to block globally banned and organization-specific weak passwords?",
            choices=[
                ("a", "Microsoft Entra Password Protection"),
                ("b", "Azure Bastion"),
                ("c", "Content explorer"),
                ("d", "Defender for Office 365"),
            ],
            correct="a",
            explanation="Password Protection bans known weak and custom banned passwords. Bastion, Content explorer, and Defender for Office 365 do not perform that password-quality function.",
            source_id="doc-password-protection",
            semantic_family_id="password_protection_management",
            tested_decision="password_protection_bans_weak_passwords",
            batch=b,
        ),
        question_record(
            serial=27,
            leaf="password_protection_management",
            difficulty="intermediate",
            stem_style="short_scenario",
            stem="Users forget passwords and the help desk is overloaded. Which Entra capability lets users reset their own passwords after proving alternative methods?",
            choices=[
                ("a", "Self-service password reset"),
                ("b", "Azure DDoS Protection"),
                ("c", "Records management"),
                ("d", "Microsoft Defender Threat Intelligence"),
            ],
            correct="a",
            explanation="SSPR lets users unlock or reset passwords themselves after verifying other authentication methods.",
            source_id="doc-sspr",
            semantic_family_id="password_protection_management",
            tested_decision="sspr_reduces_helpdesk_resets",
            batch=b,
        ),
        question_record(
            serial=28,
            leaf="conditional_access",
            difficulty="beginner",
            stem_style="direct_concept",
            stem="Which Microsoft Entra capability uses if-then policies based on user, device, location, and risk signals?",
            choices=[
                ("a", "Conditional Access"),
                ("b", "Azure Key Vault"),
                ("c", "Purview eDiscovery"),
                ("d", "Azure Firewall"),
            ],
            correct="a",
            explanation="Conditional Access evaluates identity and context signals and then allows, blocks, or requires controls such as MFA.",
            source_id="doc-conditional-access",
            semantic_family_id="conditional_access_and_identity_protection",
            tested_decision="ca_if_then_signal_policies",
            batch=b,
        ),
        question_record(
            serial=29,
            leaf="conditional_access",
            difficulty="intermediate",
            stem_style="short_scenario",
            stem="Finance users must complete MFA when they sign in from outside named locations. Which Entra capability enforces that requirement?",
            choices=[
                ("a", "A retention label policy"),
                ("b", "Conditional Access"),
                ("c", "Azure Web Application Firewall"),
                ("d", "Service Trust Portal"),
            ],
            correct="b",
            explanation="Requiring MFA based on user and location is a Conditional Access decision. Retention, WAF, and STP do not evaluate those sign-in signals.",
            source_id="module-explore-access-management-capabilities",
            semantic_family_id="conditional_access_and_identity_protection",
            tested_decision="ca_requires_mfa_from_untrusted_location",
            batch=b,
        ),
        question_record(
            serial=30,
            leaf="entra_roles_rbac",
            difficulty="intermediate",
            stem_style="concept_distinction",
            stem="Which statement correctly distinguishes Microsoft Entra roles from Azure resource RBAC?",
            choices=[
                (
                    "a",
                    "Entra roles govern directory and identity administration; Azure RBAC governs access to Azure subscriptions and resources",
                ),
                ("b", "They are identical and always assigned together"),
                ("c", "Azure RBAC replaces MFA"),
                ("d", "Entra roles only apply to printers"),
            ],
            correct="a",
            explanation="Entra roles are for identity/directory administration. Azure RBAC is for Azure resource access. They are related least-privilege systems but not the same assignment plane.",
            source_id="doc-entra-rbac",
            semantic_family_id="entra_roles_rbac",
            tested_decision="entra_roles_vs_azure_rbac_planes",
            batch=b,
        ),
        question_record(
            serial=31,
            leaf="entra_roles_rbac",
            difficulty="beginner",
            stem_style="governance_compliance",
            stem="Why should an organization avoid making every IT staff member a Global Administrator?",
            choices=[
                ("a", "Because Entra RBAC supports assigning only the directory role needed for the job"),
                ("b", "Because Global Administrator cannot sign in to Microsoft 365"),
                ("c", "Because roles cannot be assigned in Entra ID"),
                ("d", "Because encryption forbids administrators"),
            ],
            correct="a",
            explanation="Least privilege means using the smallest Entra role that can do the work instead of standing Global Administrator rights for everyone.",
            source_id="module-explore-access-management-capabilities",
            semantic_family_id="entra_roles_rbac",
            tested_decision="least_privilege_not_everyone_ga",
            batch=b,
        ),
        question_record(
            serial=32,
            leaf="entra_id_governance",
            difficulty="beginner",
            stem_style="capability_selection",
            stem="Which Microsoft Entra family of capabilities is designed for governing identity lifecycle and access over time?",
            choices=[
                ("a", "Microsoft Entra ID Governance"),
                ("b", "Azure DDoS Protection"),
                ("c", "Microsoft Defender for Office 365"),
                ("d", "Network security groups"),
            ],
            correct="a",
            explanation="ID Governance covers lifecycle, entitlement, access reviews, and related access-over-time controls, not network or email threat protection.",
            source_id="doc-id-governance",
            semantic_family_id="entra_id_governance_and_access_reviews",
            tested_decision="id_governance_family",
            batch=b,
        ),
        question_record(
            serial=33,
            leaf="entra_id_governance",
            difficulty="intermediate",
            stem_style="short_scenario",
            stem="When employees change departments, their app access should be adjusted automatically. Which ID Governance capability is built for joiner/mover/leaver automation?",
            choices=[
                ("a", "Lifecycle Workflows"),
                ("b", "Azure Firewall DNAT rules"),
                ("c", "Content explorer"),
                ("d", "Defender TI articles"),
            ],
            correct="a",
            explanation="Lifecycle Workflows automate joiner, mover, and leaver tasks. Firewall DNAT, Content explorer, and threat intel are unrelated.",
            source_id="doc-lifecycle-workflows",
            semantic_family_id="entra_id_governance_and_access_reviews",
            tested_decision="lifecycle_workflows_mover_automation",
            batch=b,
        ),
        question_record(
            serial=34,
            leaf="access_reviews",
            difficulty="beginner",
            stem_style="direct_concept",
            stem="What is the primary purpose of Microsoft Entra access reviews?",
            choices=[
                ("a", "To recertify whether users still need group, app, or role access"),
                ("b", "To mitigate volumetric DDoS floods"),
                ("c", "To hash files at rest"),
                ("d", "To host RDP jump boxes"),
            ],
            correct="a",
            explanation="Access reviews periodically recertify access and can remove stale membership. They are not network, crypto, or Bastion controls.",
            source_id="doc-access-reviews",
            semantic_family_id="entra_id_governance_and_access_reviews",
            tested_decision="access_reviews_recertify_stale_access",
            batch=b,
        ),
        question_record(
            serial=35,
            leaf="privileged_identity_management",
            difficulty="intermediate",
            stem_style="short_scenario",
            stem="Admins currently hold permanent Privileged Role Administrator rights even on days they do no directory work. Which Entra capability is designed to replace that standing access with time-bound activation?",
            choices=[
                ("a", "Privileged Identity Management"),
                ("b", "Azure Web Application Firewall"),
                ("c", "Microsoft Purview Audit"),
                ("d", "Defender for Cloud Apps"),
            ],
            correct="a",
            explanation="PIM provides just-in-time, time-bound, approval-capable activation of privileged roles instead of standing assignment.",
            source_id="doc-pim",
            semantic_family_id="privileged_identity_management",
            tested_decision="pim_replaces_standing_privilege",
            batch=b,
        ),
        question_record(
            serial=36,
            leaf="entra_id_protection",
            difficulty="beginner",
            stem_style="capability_selection",
            stem="Which Entra capability detects identity risks such as leaked credentials or atypical sign-ins?",
            choices=[
                ("a", "Microsoft Entra ID Protection"),
                ("b", "Azure Bastion"),
                ("c", "Retention labels"),
                ("d", "Service Trust Portal"),
            ],
            correct="a",
            explanation="ID Protection is the identity-risk detection service. Bastion, retention, and STP do not score sign-in risk.",
            source_id="doc-id-protection",
            semantic_family_id="conditional_access_and_identity_protection",
            tested_decision="id_protection_detects_identity_risk",
            batch=b,
        ),
        question_record(
            serial=37,
            leaf="identity_types_including_agent_id",
            difficulty="beginner",
            stem_style="direct_concept",
            stem="Which set lists identity types that Microsoft Entra ID can represent?",
            choices=[
                ("a", "Users, workload/application identities, devices, and agent identities"),
                ("b", "Only NSGs and firewalls"),
                ("c", "Only sensitivity labels"),
                ("d", "Only Sentinel workbooks"),
            ],
            correct="a",
            explanation="Entra ID represents people, apps/workloads, devices, and now agent identities. Network and compliance objects are not Entra identity types.",
            source_id="module-explore-basic-services-identity-types",
            semantic_family_id="identity_types_including_agent_id",
            tested_decision="entra_identity_type_set",
            batch=b,
        ),
        question_record(
            serial=38,
            leaf="hybrid_identity",
            difficulty="intermediate",
            stem_style="misconception_correction",
            stem="Which statement about hybrid identity is correct?",
            choices=[
                ("a", "Hybrid identity requires deleting Active Directory Domain Services on day one"),
                ("b", "Hybrid identity lets on-premises identities be used with Entra ID and cloud apps"),
                ("c", "Hybrid identity is a Purview eDiscovery case type"),
                ("d", "Hybrid identity replaces encryption"),
            ],
            correct="b",
            explanation="Hybrid identity connects AD DS identities to Entra ID. It does not require immediately removing AD DS or changing eDiscovery/encryption products.",
            source_id="module-explore-basic-services-identity-types",
            semantic_family_id="entra_hybrid_identity_and_ad",
            tested_decision="hybrid_keeps_ad_ds_connected",
            batch=b,
        ),
        question_record(
            serial=39,
            leaf="authentication_methods",
            difficulty="beginner",
            stem_style="short_scenario",
            stem="A help desk needs a short-lived sign-in method so a new hire can register Authenticator. Which method is designed for that bootstrap?",
            choices=[
                ("a", "Temporary Access Pass"),
                ("b", "A DLP policy"),
                ("c", "An NSG deny-all rule"),
                ("d", "A Defender TI indicator"),
            ],
            correct="a",
            explanation="Temporary Access Pass is a time-limited passcode for bootstrapping passwordless registration. DLP, NSGs, and threat intel are not sign-in methods.",
            source_id="doc-temporary-access-pass",
            semantic_family_id="authentication_methods",
            tested_decision="tap_bootstrap_new_hire_registration",
            batch=b,
        ),
        question_record(
            serial=40,
            leaf="multifactor_authentication",
            difficulty="intermediate",
            stem_style="concept_distinction",
            stem="A user enters a password and then scans a fingerprint. Why does that qualify as MFA?",
            choices=[
                ("a", "Because two different factor categories are combined"),
                ("b", "Because the fingerprint replaces authorization"),
                ("c", "Because hashing occurred"),
                ("d", "Because a WAF inspected the request"),
            ],
            correct="a",
            explanation="MFA combines distinct factor categories such as knowledge and inherence. The second factor is not authorization, hashing, or WAF inspection.",
            source_id="module-explore-authentication-capabilities",
            semantic_family_id="multifactor_authentication",
            tested_decision="mfa_two_factor_categories",
            batch=b,
        ),
        question_record(
            serial=41,
            leaf="conditional_access",
            difficulty="intermediate",
            stem_style="misconception_correction",
            stem="Which statement about Conditional Access is correct?",
            choices=[
                ("a", "It is a SIEM that stores all Azure activity logs"),
                ("b", "It can require a compliant device or MFA when sign-in conditions match"),
                ("c", "It declares items as records"),
                ("d", "It is only a DDoS mitigation service"),
            ],
            correct="b",
            explanation="Conditional Access enforces session and grant controls when policy conditions match. It is not SIEM, records management, or DDoS protection.",
            source_id="doc-conditional-access",
            semantic_family_id="conditional_access_and_identity_protection",
            tested_decision="ca_grant_controls_not_siem",
            batch=b,
        ),
        question_record(
            serial=42,
            leaf="privileged_identity_management",
            difficulty="beginner",
            stem_style="direct_concept",
            stem="Which PIM characteristic most directly supports least privilege for administrators?",
            choices=[
                ("a", "Just-in-time activation instead of always-on privileged roles"),
                ("b", "Automatic public IP assignment to VMs"),
                ("c", "Disabling authentication"),
                ("d", "Publishing ISO reports"),
            ],
            correct="a",
            explanation="Just-in-time activation keeps privileged roles inactive until needed, which is the PIM least-privilege pattern.",
            source_id="module-describe-identity-protection-governance-capabilities",
            semantic_family_id="privileged_identity_management",
            tested_decision="pim_jit_least_privilege",
            batch=b,
        ),
        question_record(
            serial=43,
            leaf="entra_id_protection",
            difficulty="intermediate",
            stem_style="short_scenario",
            stem="Sign-ins from impossible travel are raising identity risk. Which pairing is the fundamentals-level way Microsoft expects those detections to influence access?",
            choices=[
                ("a", "ID Protection detects the risk; Conditional Access can require controls or block the sign-in"),
                ("b", "Azure Bastion hashes the token"),
                ("c", "WAF declares a record"),
                ("d", "eDiscovery assigns an Entra role"),
            ],
            correct="a",
            explanation="ID Protection produces risk signals; Conditional Access commonly consumes them to require MFA, block, or other grants.",
            source_id="doc-id-protection",
            semantic_family_id="conditional_access_and_identity_protection",
            tested_decision="id_protection_feeds_conditional_access",
            batch=b,
        ),
        question_record(
            serial=44,
            leaf="access_reviews",
            difficulty="intermediate",
            stem_style="concept_distinction",
            stem="Which task is a better fit for access reviews than for Lifecycle Workflows?",
            choices=[
                ("a", "Automatically creating a mailbox on day one of employment"),
                ("b", "Asking owners to recertify who still needs a security group"),
                ("c", "Mitigating a SYN flood"),
                ("d", "Storing TLS certificates"),
            ],
            correct="b",
            explanation="Access reviews recertify existing access. Joiner automation is Lifecycle Workflows. DDoS and Key Vault are unrelated.",
            source_id="doc-access-reviews",
            semantic_family_id="entra_id_governance_and_access_reviews",
            tested_decision="reviews_recertify_not_joiner_provisioning",
            batch=b,
        ),
        question_record(
            serial=45,
            leaf="entra_id_overview",
            difficulty="intermediate",
            stem_style="short_scenario",
            stem="A startup is moving from local application usernames to a cloud directory that can also protect Microsoft 365. Which service should it use?",
            choices=[
                ("a", "Microsoft Entra ID"),
                ("b", "Azure Firewall"),
                ("c", "Microsoft Purview Records Management"),
                ("d", "Defender Vulnerability Management"),
            ],
            correct="a",
            explanation="Entra ID is the cloud directory for users and app access, including Microsoft 365. The other tools are network, records, or vulnerability products.",
            source_id="module-explore-basic-services-identity-types",
            semantic_family_id="entra_hybrid_identity_and_ad",
            tested_decision="entra_replaces_local_app_directories",
            batch=b,
        ),
        question_record(
            serial=46,
            leaf="identity_types_including_agent_id",
            difficulty="intermediate",
            stem_style="concept_distinction",
            stem="Why should an AI agent not share a human user's identity?",
            choices=[
                ("a", "Because agent activity could not be authenticated, authorized, or reviewed separately"),
                ("b", "Because agents cannot use HTTPS"),
                ("c", "Because Entra ID forbids applications"),
                ("d", "Because hashing would stop working"),
            ],
            correct="a",
            explanation="Distinct agent identities exist so automation can be governed on its own. Entra ID already supports app and agent identity types.",
            source_id="module-explore-basic-services-identity-types",
            semantic_family_id="identity_types_including_agent_id",
            tested_decision="agents_need_distinct_identity",
            batch=b,
        ),
        question_record(
            serial=47,
            leaf="authentication_methods",
            difficulty="beginner",
            stem_style="direct_concept",
            stem="Which option is an Entra authentication method rather than an access-governance feature?",
            choices=[
                ("a", "Microsoft Authenticator passwordless sign-in"),
                ("b", "Access reviews"),
                ("c", "Entitlement management catalogs"),
                ("d", "Lifecycle Workflows"),
            ],
            correct="a",
            explanation="Authenticator is an authentication method. Access reviews, entitlement catalogs, and Lifecycle Workflows govern access over time.",
            source_id="module-explore-authentication-capabilities",
            semantic_family_id="authentication_methods",
            tested_decision="authenticator_is_auth_method_not_governance",
            batch=b,
        ),
        question_record(
            serial=48,
            leaf="multifactor_authentication",
            difficulty="beginner",
            stem_style="short_scenario",
            stem="An attacker has a user's password but not the user's phone. Which control is intended to stop that sign-in?",
            choices=[
                ("a", "Multifactor authentication"),
                ("b", "A retention policy"),
                ("c", "Azure DDoS Protection"),
                ("d", "Content explorer"),
            ],
            correct="a",
            explanation="MFA requires another factor the attacker likely does not have. Retention, DDoS, and Content explorer do not challenge extra sign-in factors.",
            source_id="doc-mfa",
            semantic_family_id="multifactor_authentication",
            tested_decision="mfa_stops_password_replay_without_second_factor",
            batch=b,
        ),
        question_record(
            serial=49,
            leaf="defense_in_depth",
            difficulty="intermediate",
            stem_style="short_scenario",
            stem="Identity MFA is strong, but a stolen session still reaches plaintext files on a laptop. Which defense-in-depth lesson does this illustrate?",
            choices=[
                ("a", "One strong layer does not remove the need for data and endpoint controls"),
                ("b", "MFA makes encryption illegal"),
                ("c", "Defense-in-depth applies only to DNS"),
                ("d", "Zero Trust forbids laptops"),
            ],
            correct="a",
            explanation="Defense-in-depth expects additional layers such as endpoint protection and data encryption even when identity controls succeed.",
            source_id="module-describe-security-concepts-methodologies",
            semantic_family_id="defense_in_depth",
            tested_decision="identity_layer_not_enough_alone",
            batch=b,
        ),
        question_record(
            serial=50,
            leaf="grc_concepts",
            difficulty="beginner",
            stem_style="short_scenario",
            stem="Leadership wants written policies, assigned owners, and oversight of security decisions. Which GRC concept is that request describing?",
            choices=[("a", "Governance"), ("b", "Azure Bastion"), ("c", "Hashing"), ("d", "Defender for Identity")],
            correct="a",
            explanation="Governance is the direction-and-control system of policies, owners, and oversight. The other options are technical controls.",
            source_id="module-describe-security-concepts-methodologies",
            semantic_family_id="grc_concepts",
            tested_decision="governance_is_policy_and_oversight",
            batch=b,
        ),
    ]
