from __future__ import annotations

from tools.sc900_microsoft_corpus_qemit import question_record


def batch_01() -> list[dict]:
    b = "mlc-batch-01"
    return [
        question_record(
            serial=1,
            leaf="shared_responsibility_model",
            difficulty="beginner",
            stem_style="responsibility_governance",
            stem="An organization hosts virtual machines in Azure IaaS. Which security duty typically remains with the customer rather than Microsoft?",
            choices=[
                ("a", "Physically securing the datacenter building"),
                ("b", "Patching the guest operating system and configuring its access"),
                ("c", "Replacing failed host hardware"),
                ("d", "Operating the underlying cloud fabric"),
            ],
            correct="b",
            explanation="In IaaS, Microsoft operates the physical host and fabric, while the customer remains responsible for the guest OS, identity, data, and in-guest configuration.",
            source_id="doc-shared-responsibility",
            semantic_family_id="shared_responsibility_model",
            tested_decision="iaas_guest_os_customer",
            misconception_target="all_cloud_duties_transfer",
            batch=b,
        ),
        question_record(
            serial=2,
            leaf="defense_in_depth",
            difficulty="intermediate",
            stem_style="short_scenario",
            stem="A company relies on a single perimeter firewall and no additional identity or data controls. Which security model is it failing to apply?",
            choices=[
                ("a", "Federation"),
                ("b", "Records management"),
                ("c", "Defense-in-depth"),
                ("d", "Privileged Identity Management"),
            ],
            correct="c",
            explanation="Defense-in-depth requires multiple independent layers. Depending on one perimeter firewall leaves other layers unprotected if that control fails.",
            source_id="module-describe-security-concepts-methodologies",
            semantic_family_id="defense_in_depth",
            tested_decision="single_layer_is_not_defense_in_depth",
            batch=b,
        ),
        question_record(
            serial=3,
            leaf="zero_trust_model",
            difficulty="beginner",
            stem_style="direct_concept",
            stem="Which statement best describes a Zero Trust approach to access?",
            choices=[
                ("a", "Trust every request that originates on the corporate network"),
                ("b", "Verify explicitly and grant only the access needed, even for internal users"),
                ("c", "Disable authentication after a user is on a VPN"),
                ("d", "Replace encryption with network location checks"),
            ],
            correct="b",
            explanation="Zero Trust verifies explicitly and uses least privilege instead of assuming that an internal network location is trustworthy.",
            source_id="doc-zero-trust-overview",
            semantic_family_id="zero_trust_and_identity_perimeter",
            tested_decision="verify_explicitly_not_network_trust",
            batch=b,
        ),
        question_record(
            serial=4,
            leaf="encryption_and_hashing",
            difficulty="intermediate",
            stem_style="concept_distinction",
            stem="A team needs to confirm a downloaded file was not altered, but it does not need to hide the file contents. Which technique is designed for that integrity check?",
            choices=[
                ("a", "Hashing"),
                ("b", "Symmetric encryption of the file"),
                ("c", "Issuing a Temporary Access Pass"),
                ("d", "Creating a retention label"),
            ],
            correct="a",
            explanation="Hashing produces a one-way fingerprint used to detect change. Encryption hides contents, and the other options are identity or compliance controls.",
            source_id="module-describe-security-concepts-methodologies",
            semantic_family_id="encryption_and_hashing",
            tested_decision="hashing_for_integrity_not_confidentiality",
            batch=b,
        ),
        question_record(
            serial=5,
            leaf="grc_concepts",
            difficulty="beginner",
            stem_style="direct_concept",
            stem="Which GRC activity is primarily about identifying, analyzing, and treating uncertainty that could affect objectives?",
            choices=[
                ("a", "Risk management"),
                ("b", "Labeling a document as a record"),
                ("c", "Deploying Azure Bastion"),
                ("d", "Enabling Microsoft Defender for Endpoint"),
            ],
            correct="a",
            explanation="Risk management is the GRC discipline for identifying and treating risk. The other options are protection or compliance product actions, not the risk process itself.",
            source_id="module-describe-security-concepts-methodologies",
            semantic_family_id="grc_concepts",
            tested_decision="risk_management_vs_product_control",
            batch=b,
        ),
        question_record(
            serial=6,
            leaf="identity_primary_security_perimeter",
            difficulty="intermediate",
            stem_style="short_scenario",
            stem="Users now sign in to SaaS apps from home networks, coffee shops, and mobile devices. Why do security programs treat identity as a primary perimeter?",
            choices=[
                ("a", "Because SaaS apps cannot use encryption"),
                ("b", "Because a single trusted office network no longer surrounds every access request"),
                ("c", "Because passwords are no longer used anywhere"),
                ("d", "Because firewalls cannot be deployed in Azure"),
            ],
            correct="b",
            explanation="Cloud access originates from many networks, so verified identity and contextual access become the practical control point rather than a single office LAN.",
            source_id="module-describe-identity-principles-concepts",
            semantic_family_id="zero_trust_and_identity_perimeter",
            tested_decision="cloud_access_breaks_network_perimeter",
            batch=b,
        ),
        question_record(
            serial=7,
            leaf="authentication",
            difficulty="beginner",
            stem_style="direct_concept",
            stem="A sign-in screen asks a user for a password and then a phone approval. What process is occurring?",
            choices=[
                ("a", "Authorization of SharePoint sites"),
                ("b", "Authentication of the user's identity"),
                ("c", "Records declaration"),
                ("d", "Network segmentation"),
            ],
            correct="b",
            explanation="Checking credentials or authentication factors verifies who the user is. That is authentication, not the later decision about what they may access.",
            source_id="module-describe-identity-principles-concepts",
            semantic_family_id="authentication_vs_authorization",
            tested_decision="factors_verify_identity",
            batch=b,
        ),
        question_record(
            serial=8,
            leaf="authorization",
            difficulty="intermediate",
            stem_style="short_scenario",
            stem="A user authenticates successfully but cannot open a finance app. Which process denied the access?",
            choices=[
                ("a", "Hashing"),
                ("b", "Federation metadata exchange"),
                ("c", "Authorization"),
                ("d", "DNS resolution"),
            ],
            correct="c",
            explanation="Authorization evaluates permissions after authentication. A valid sign-in can still be denied if the identity lacks rights to the app.",
            source_id="module-describe-identity-principles-concepts",
            semantic_family_id="authentication_vs_authorization",
            tested_decision="authz_can_deny_after_authn",
            batch=b,
        ),
        question_record(
            serial=9,
            leaf="identity_providers",
            difficulty="beginner",
            stem_style="capability_selection",
            stem="An application trusts tokens issued by Microsoft Entra ID instead of storing its own local passwords. What role is Entra ID playing?",
            choices=[
                ("a", "Data loss prevention broker"),
                ("b", "Identity provider"),
                ("c", "SIEM collector"),
                ("d", "Web application firewall"),
            ],
            correct="b",
            explanation="An identity provider authenticates users and issues claims/tokens that applications accept. DLP, SIEM, and WAF are different control types.",
            source_id="module-describe-identity-principles-concepts",
            semantic_family_id="federation_and_identity_providers",
            tested_decision="idp_issues_trusted_tokens",
            batch=b,
        ),
        question_record(
            serial=10,
            leaf="directory_services_active_directory",
            difficulty="beginner",
            stem_style="direct_concept",
            stem="Which on-premises directory service traditionally stores domain-joined Windows identities and Group Policy objects?",
            choices=[
                ("a", "Microsoft Sentinel"),
                ("b", "Azure DDoS Protection"),
                ("c", "Active Directory Domain Services"),
                ("d", "Microsoft Purview eDiscovery"),
            ],
            correct="c",
            explanation="AD DS is the on-premises directory for domain identities and Group Policy. The other services are SIEM, network, or compliance capabilities.",
            source_id="module-describe-identity-principles-concepts",
            semantic_family_id="entra_hybrid_identity_and_ad",
            tested_decision="ad_ds_on_prem_directory",
            batch=b,
        ),
        question_record(
            serial=11,
            leaf="federation",
            difficulty="intermediate",
            stem_style="short_scenario",
            stem="A supplier's employees need to access an internal app using the supplier's own sign-in service, without a new local password for each person. Which identity concept enables that trust?",
            choices=[
                ("a", "Federation"),
                ("b", "Azure Bastion"),
                ("c", "Content explorer"),
                ("d", "Defender Vulnerability Management"),
            ],
            correct="a",
            explanation="Federation creates a trust so one organization can accept identities authenticated by another provider, avoiding duplicate local accounts.",
            source_id="module-describe-identity-principles-concepts",
            semantic_family_id="federation_and_identity_providers",
            tested_decision="federation_for_partner_access",
            batch=b,
        ),
        question_record(
            serial=12,
            leaf="grc_concepts",
            difficulty="intermediate",
            stem_style="concept_distinction",
            stem="Which statement correctly distinguishes governance from compliance?",
            choices=[
                ("a", "Governance is only a Microsoft Defender XDR incident queue"),
                (
                    "b",
                    "Governance sets the organization's chosen rules and oversight; compliance assesses whether internal and external requirements are met",
                ),
                ("c", "Compliance replaces the need for encryption"),
                ("d", "Governance applies only to on-premises firewalls"),
            ],
            correct="b",
            explanation="Governance is how an organization directs and controls itself. Compliance is the demonstration that obligations and policies are being met.",
            source_id="module-describe-security-concepts-methodologies",
            semantic_family_id="grc_concepts",
            tested_decision="governance_sets_rules_compliance_measures",
            batch=b,
        ),
        question_record(
            serial=13,
            leaf="encryption_and_hashing",
            difficulty="beginner",
            stem_style="direct_concept",
            stem="What is the primary purpose of encrypting data at rest?",
            choices=[
                ("a", "To make stored data unreadable without authorized keys"),
                ("b", "To replace multifactor authentication"),
                ("c", "To create a SIEM incident automatically"),
                ("d", "To publish Microsoft audit reports"),
            ],
            correct="a",
            explanation="Encryption protects confidentiality of stored data by requiring keys to read it. It does not replace identity, SIEM, or trust-portal functions.",
            source_id="doc-encryption-azure",
            semantic_family_id="encryption_and_hashing",
            tested_decision="encryption_confidentiality_at_rest",
            batch=b,
        ),
        question_record(
            serial=14,
            leaf="zero_trust_model",
            difficulty="intermediate",
            stem_style="misconception_correction",
            stem="Which statement about Zero Trust is correct?",
            choices=[
                ("a", "Zero Trust means never authenticating employees after they join the company"),
                ("b", "Zero Trust assumes a breach is possible and continuously validates requests"),
                ("c", "Zero Trust requires turning off Conditional Access"),
                ("d", "Zero Trust applies only to printers"),
            ],
            correct="b",
            explanation="Assume breach and continuous validation are Zero Trust ideas. It does not mean skipping authentication or disabling access policies.",
            source_id="doc-zero-trust-overview",
            semantic_family_id="zero_trust_and_identity_perimeter",
            tested_decision="assume_breach_continuous_validation",
            batch=b,
        ),
        question_record(
            serial=15,
            leaf="defense_in_depth",
            difficulty="beginner",
            stem_style="capability_selection",
            stem="Which example best illustrates defense-in-depth?",
            choices=[
                ("a", "Using only a long password and no other controls"),
                ("b", "Combining identity controls, network filters, endpoint protection, and data encryption"),
                ("c", "Storing all secrets in a public Git repository"),
                ("d", "Allowing every inbound port to simplify operations"),
            ],
            correct="b",
            explanation="Defense-in-depth stacks independent controls across layers. A single password or an open network is the opposite pattern.",
            source_id="module-describe-security-concepts-methodologies",
            semantic_family_id="defense_in_depth",
            tested_decision="multiple_independent_layers",
            batch=b,
        ),
        question_record(
            serial=16,
            leaf="shared_responsibility_model",
            difficulty="intermediate",
            stem_style="concept_distinction",
            stem="Under the shared responsibility model, which comparison is accurate as an organization moves from IaaS toward SaaS?",
            choices=[
                ("a", "The customer becomes responsible for Microsoft's physical hosts"),
                (
                    "b",
                    "Microsoft typically takes on more of the underlying platform while the customer still owns data and identities",
                ),
                ("c", "Identity management disappears"),
                ("d", "Encryption is no longer allowed"),
            ],
            correct="b",
            explanation="More managed services shift infrastructure duties to Microsoft, but customers still own their data, identities, and access configuration.",
            source_id="doc-shared-responsibility",
            semantic_family_id="shared_responsibility_model",
            tested_decision="saas_shifts_platform_not_customer_data",
            batch=b,
        ),
        question_record(
            serial=17,
            leaf="identity_primary_security_perimeter",
            difficulty="beginner",
            stem_style="direct_concept",
            stem="Which change most strongly pushed identity to become a primary security perimeter?",
            choices=[
                ("a", "Applications and users moving outside a single corporate network boundary"),
                ("b", "The retirement of encryption"),
                ("c", "The requirement that all admins use Telnet"),
                ("d", "The removal of authentication from cloud apps"),
            ],
            correct="a",
            explanation="When apps and users left the castle-and-moat network, identity verification became the practical perimeter for access decisions.",
            source_id="module-describe-identity-principles-concepts",
            semantic_family_id="zero_trust_and_identity_perimeter",
            tested_decision="users_and_apps_left_the_lan",
            batch=b,
        ),
        question_record(
            serial=18,
            leaf="authentication",
            difficulty="intermediate",
            stem_style="misconception_correction",
            stem="Which statement about authentication is correct?",
            choices=[
                ("a", "Authentication decides which files a user may edit"),
                ("b", "Authentication only applies to printers"),
                ("c", "Authentication verifies claimed identity before access rights are evaluated"),
                ("d", "Authentication is the same as data classification"),
            ],
            correct="c",
            explanation="Authentication is identity proofing. Editing rights are authorization, and classification is a data-protection concept.",
            source_id="module-describe-identity-principles-concepts",
            semantic_family_id="authentication_vs_authorization",
            tested_decision="authn_is_not_file_permissions",
            batch=b,
        ),
        question_record(
            serial=19,
            leaf="authorization",
            difficulty="beginner",
            stem_style="direct_concept",
            stem="What does authorization determine?",
            choices=[
                ("a", "Whether the presented credentials belong to the claimed identity"),
                ("b", "What an already verified identity is allowed to do"),
                ("c", "Whether a hash algorithm is collision resistant"),
                ("d", "Whether a datacenter has cameras"),
            ],
            correct="b",
            explanation="Authorization is the permission decision after identity has been verified.",
            source_id="module-describe-identity-principles-concepts",
            semantic_family_id="authentication_vs_authorization",
            tested_decision="authorization_is_permission_decision",
            batch=b,
        ),
        question_record(
            serial=20,
            leaf="federation",
            difficulty="beginner",
            stem_style="direct_concept",
            stem="What does identity federation establish between organizations?",
            choices=[
                ("a", "A DDoS mitigation anycast network"),
                ("b", "A trust so one party can accept identities authenticated by the other"),
                ("c", "A Purview retention schedule"),
                ("d", "A Key Vault deletion lock"),
            ],
            correct="b",
            explanation="Federation is a trust relationship for cross-organization authentication, not a network, retention, or key-management feature.",
            source_id="module-describe-identity-principles-concepts",
            semantic_family_id="federation_and_identity_providers",
            tested_decision="federation_is_identity_trust",
            batch=b,
        ),
        question_record(
            serial=21,
            leaf="entra_id_overview",
            difficulty="beginner",
            stem_style="capability_selection",
            stem="Which Microsoft service is the cloud identity and access management directory used to sign in to Microsoft 365 and many integrated apps?",
            choices=[
                ("a", "Azure Firewall"),
                ("b", "Microsoft Entra ID"),
                ("c", "Microsoft Purview Audit"),
                ("d", "Azure DDoS Protection"),
            ],
            correct="b",
            explanation="Microsoft Entra ID is the cloud IAM directory. Firewall, audit, and DDoS Protection serve other purposes.",
            source_id="doc-entra-what-is",
            semantic_family_id="entra_hybrid_identity_and_ad",
            tested_decision="entra_id_is_cloud_iam",
            batch=b,
        ),
        question_record(
            serial=22,
            leaf="identity_types_including_agent_id",
            difficulty="intermediate",
            stem_style="current_topic",
            stem="An organization deploys AI agents that must call APIs under their own governed identity rather than a shared human mailbox. Which Entra identity type is intended for that pattern?",
            choices=[("a", "Agent ID"), ("b", "Sensitivity label"), ("c", "NSG rule"), ("d", "Retention policy")],
            correct="a",
            explanation="Agent ID is the Entra identity type for AI agents so they can be authenticated and governed. Labels, NSGs, and retention policies are not identity types.",
            source_id="module-explore-basic-services-identity-types",
            semantic_family_id="identity_types_including_agent_id",
            tested_decision="agent_id_for_ai_agents",
            batch=b,
        ),
        question_record(
            serial=23,
            leaf="hybrid_identity",
            difficulty="beginner",
            stem_style="short_scenario",
            stem="A company wants staff to use the same account for on-premises AD DS resources and Microsoft 365. Which capability addresses that requirement?",
            choices=[
                ("a", "Hybrid identity with Microsoft Entra ID"),
                ("b", "Azure Web Application Firewall"),
                ("c", "Insider Risk Management"),
                ("d", "Azure Bastion"),
            ],
            correct="a",
            explanation="Hybrid identity connects on-premises directory identities with Entra ID so one identity can be used in both environments.",
            source_id="doc-hybrid-identity",
            semantic_family_id="entra_hybrid_identity_and_ad",
            tested_decision="hybrid_identity_one_account_both_worlds",
            batch=b,
        ),
        question_record(
            serial=24,
            leaf="authentication_methods",
            difficulty="intermediate",
            stem_style="service_selection",
            stem="Which Entra authentication method is a phishing-resistant passkey that can replace passwords for sign-in?",
            choices=[
                ("a", "FIDO2 security key / passkey"),
                ("b", "A Purview DLP rule"),
                ("c", "A Sentinel playbook"),
                ("d", "A compliance score action"),
            ],
            correct="a",
            explanation="FIDO2/passkeys are phishing-resistant Entra authentication methods. DLP, playbooks, and compliance score are not authentication methods.",
            source_id="doc-authentication-methods",
            semantic_family_id="authentication_methods",
            tested_decision="fido2_passkey_phishing_resistant",
            batch=b,
        ),
        question_record(
            serial=25,
            leaf="multifactor_authentication",
            difficulty="beginner",
            stem_style="direct_concept",
            stem="Why does multifactor authentication reduce account-takeover risk?",
            choices=[
                ("a", "It removes the need to authorize access"),
                ("b", "A stolen password alone is not enough if another factor is required"),
                ("c", "It encrypts every NSG rule"),
                ("d", "It publishes Service Trust Portal reports"),
            ],
            correct="b",
            explanation="MFA requires an additional factor category, so password theft by itself should not complete sign-in.",
            source_id="doc-mfa",
            semantic_family_id="multifactor_authentication",
            tested_decision="mfa_blocks_password_only_takeover",
            batch=b,
        ),
    ]
