from __future__ import annotations

from tools.sc900_microsoft_corpus_qemit import question_record


def batch_04() -> list[dict]:
    b = "mlc-batch-04"
    return [
        question_record(
            serial=76,
            leaf="azure_ddos_protection",
            difficulty="beginner",
            stem_style="capability_selection",
            stem="Which Azure service is intended to mitigate large volumetric attacks that try to overwhelm public IP addresses?",
            choices=[
                ("a", "Azure DDoS Protection"),
                ("b", "Microsoft Entra access reviews"),
                ("c", "Purview records management"),
                ("d", "Compliance Manager"),
            ],
            correct="a",
            explanation="DDoS Protection is the network-layer volumetric mitigation service. The other options are identity or compliance capabilities.",
            source_id="doc-ddos",
            semantic_family_id="azure_nsg_firewall_waf_ddos",
            tested_decision="ddos_volumetric_public_ip",
            batch=b,
        ),
        question_record(
            serial=77,
            leaf="azure_firewall",
            difficulty="beginner",
            stem_style="direct_concept",
            stem="What is Azure Firewall?",
            choices=[
                ("a", "A managed, stateful network firewall for Azure virtual networks"),
                ("b", "A mailbox anti-phishing filter"),
                ("c", "A privileged role activation service"),
                ("d", "A file retention engine"),
            ],
            correct="a",
            explanation="Azure Firewall is a centralized stateful network firewall. It is not Defender for Office 365, PIM, or Purview retention.",
            source_id="doc-azure-firewall",
            semantic_family_id="azure_nsg_firewall_waf_ddos",
            tested_decision="azure_firewall_stateful_vnet",
            batch=b,
        ),
        question_record(
            serial=78,
            leaf="azure_web_application_firewall",
            difficulty="beginner",
            stem_style="short_scenario",
            stem="A public website is being probed with SQL injection and cross-site scripting. Which Azure control inspects HTTP requests for those attacks?",
            choices=[
                ("a", "Azure Web Application Firewall"),
                ("b", "Azure DDoS Protection"),
                ("c", "Microsoft Entra Password Protection"),
                ("d", "Service Trust Portal"),
            ],
            correct="a",
            explanation="WAF inspects application-layer HTTP/HTTPS traffic for common web attacks. DDoS Protection addresses volumetric floods, not payload inspection.",
            source_id="doc-waf",
            semantic_family_id="azure_nsg_firewall_waf_ddos",
            tested_decision="waf_inspects_http_injection",
            batch=b,
        ),
        question_record(
            serial=79,
            leaf="azure_virtual_network_segmentation",
            difficulty="beginner",
            stem_style="direct_concept",
            stem="What does placing workloads in separate Azure virtual network subnets primarily achieve?",
            choices=[
                ("a", "Network segmentation so communication can be controlled between groups of resources"),
                ("b", "Automatic MFA for every packet"),
                ("c", "Legal hold on email"),
                ("d", "Banned-password enforcement"),
            ],
            correct="a",
            explanation="VNets and subnets create segmented private networks. They do not by themselves perform MFA, eDiscovery, or password bans.",
            source_id="doc-vnet",
            semantic_family_id="azure_virtual_network_segmentation",
            tested_decision="vnet_subnets_segment_workloads",
            batch=b,
        ),
        question_record(
            serial=80,
            leaf="network_security_groups",
            difficulty="beginner",
            stem_style="capability_selection",
            stem="Which Azure feature uses allow and deny rules associated with a subnet or NIC?",
            choices=[
                ("a", "Network security groups"),
                ("b", "Compliance score"),
                ("c", "Access reviews"),
                ("d", "Defender Threat Intelligence"),
            ],
            correct="a",
            explanation="NSGs filter traffic with 5-tuple style allow/deny rules at subnet or NIC scope.",
            source_id="doc-nsg",
            semantic_family_id="azure_nsg_firewall_waf_ddos",
            tested_decision="nsg_subnet_or_nic_rules",
            batch=b,
        ),
        question_record(
            serial=81,
            leaf="azure_bastion",
            difficulty="beginner",
            stem_style="short_scenario",
            stem="Administrators must RDP to Azure VMs without giving those VMs public IP addresses. Which service provides browser-based RDP/SSH over TLS?",
            choices=[
                ("a", "Azure Bastion"),
                ("b", "Microsoft Purview DLP"),
                ("c", "Entra ID Protection"),
                ("d", "Defender for Office 365"),
            ],
            correct="a",
            explanation="Bastion is the managed jump-host service for RDP/SSH without public management ports on the VMs.",
            source_id="doc-bastion",
            semantic_family_id="azure_bastion",
            tested_decision="bastion_rdp_without_public_ip",
            batch=b,
        ),
        question_record(
            serial=82,
            leaf="azure_key_vault",
            difficulty="beginner",
            stem_style="direct_concept",
            stem="Where should an Azure application retrieve secrets and cryptographic keys instead of embedding them in source code?",
            choices=[
                ("a", "Azure Key Vault"),
                ("b", "A public GitHub gist"),
                ("c", "An NSG rule list"),
                ("d", "A Service Trust Portal user guide"),
            ],
            correct="a",
            explanation="Key Vault is the Azure service for storing and controlling access to secrets, keys, and certificates.",
            source_id="doc-key-vault",
            semantic_family_id="azure_key_vault",
            tested_decision="key_vault_not_hardcoded_secrets",
            batch=b,
        ),
        question_record(
            serial=83,
            leaf="microsoft_defender_for_cloud",
            difficulty="beginner",
            stem_style="capability_selection",
            stem="Which Microsoft service assesses Azure resource configurations and presents security recommendations and secure score?",
            choices=[
                ("a", "Microsoft Defender for Cloud"),
                ("b", "Microsoft Entra Lifecycle Workflows"),
                ("c", "Purview eDiscovery"),
                ("d", "Azure Bastion"),
            ],
            correct="a",
            explanation="Defender for Cloud is the CSPM/CWP service with recommendations and secure score. The other tools are identity lifecycle, legal discovery, or VM access.",
            source_id="doc-defender-for-cloud",
            semantic_family_id="defender_for_cloud_cspm_cwp",
            tested_decision="dfc_recommendations_and_secure_score",
            batch=b,
        ),
        question_record(
            serial=84,
            leaf="cloud_security_posture_management",
            difficulty="beginner",
            stem_style="direct_concept",
            stem="What does Cloud Security Posture Management (CSPM) focus on?",
            choices=[
                ("a", "Finding and recommending fixes for cloud misconfigurations against security standards"),
                ("b", "Just-in-time Entra role activation"),
                ("c", "Mailbox detonation of attachments"),
                ("d", "Browser RDP to VMs"),
            ],
            correct="a",
            explanation="CSPM is configuration/posture assessment. PIM, Defender for Office 365, and Bastion are different functions.",
            source_id="doc-cspm",
            semantic_family_id="defender_for_cloud_cspm_cwp",
            tested_decision="cspm_is_misconfiguration_posture",
            batch=b,
        ),
        question_record(
            serial=85,
            leaf="cloud_workload_protection",
            difficulty="intermediate",
            stem_style="concept_distinction",
            stem="How does cloud workload protection differ from CSPM?",
            choices=[
                (
                    "a",
                    "Workload protection adds threat detection and plans for running workloads; CSPM emphasizes configuration posture",
                ),
                ("b", "They are both eDiscovery case types"),
                ("c", "CSPM replaces encryption"),
                ("d", "Workload protection is only a banned-password list"),
            ],
            correct="a",
            explanation="CSPM scores and recommends configuration. CWP/enhanced plans add threat protection for servers and other workloads.",
            source_id="doc-cwp",
            semantic_family_id="defender_for_cloud_cspm_cwp",
            tested_decision="cwp_threats_vs_cspm_config",
            batch=b,
        ),
        question_record(
            serial=86,
            leaf="siem_and_soar",
            difficulty="beginner",
            stem_style="direct_concept",
            stem="What is the primary job of a SIEM?",
            choices=[
                ("a", "Collect and correlate security logs and alerts for detection and investigation"),
                ("b", "Issue FIDO2 credentials"),
                ("c", "Declare items as records"),
                ("d", "Assign Entra roles"),
            ],
            correct="a",
            explanation="SIEM is about log correlation and investigation. Credentials, records, and Entra roles are other domains.",
            source_id="module-describe-security-capabilities-of-azure-sentinel",
            semantic_family_id="sentinel_siem_soar_automation",
            tested_decision="siem_correlates_logs",
            batch=b,
        ),
        question_record(
            serial=87,
            leaf="siem_and_soar",
            difficulty="beginner",
            stem_style="direct_concept",
            stem="What is the primary job of SOAR?",
            choices=[
                ("a", "Orchestrate and automate response actions such as playbooks"),
                ("b", "Segment Azure subnets"),
                ("c", "Publish Microsoft privacy principles"),
                ("d", "Score Compliance Manager improvement actions"),
            ],
            correct="a",
            explanation="SOAR automates response. Segmentation, privacy principles, and compliance score are not SOAR.",
            source_id="module-describe-security-capabilities-of-azure-sentinel",
            semantic_family_id="sentinel_siem_soar_automation",
            tested_decision="soar_automates_response",
            batch=b,
        ),
        question_record(
            serial=88,
            leaf="sentinel_threat_detection_mitigation",
            difficulty="beginner",
            stem_style="capability_selection",
            stem="Which Microsoft service is the cloud-native SIEM and SOAR platform?",
            choices=[
                ("a", "Microsoft Sentinel"),
                ("b", "Azure Key Vault"),
                ("c", "Microsoft Entra Password Protection"),
                ("d", "Purview Content explorer"),
            ],
            correct="a",
            explanation="Sentinel is the SIEM/SOAR service. Key Vault, password protection, and Content explorer are not.",
            source_id="doc-sentinel",
            semantic_family_id="sentinel_siem_soar_automation",
            tested_decision="sentinel_is_cloud_siem_soar",
            batch=b,
        ),
        question_record(
            serial=89,
            leaf="defender_xdr_services",
            difficulty="beginner",
            stem_style="direct_concept",
            stem="What does Microsoft Defender XDR provide?",
            choices=[
                ("a", "Correlated detection and response across multiple Microsoft Defender workloads"),
                ("b", "Only Azure VM public IPs"),
                ("c", "Only Service Trust Portal documents"),
                ("d", "Only NSG flow logs"),
            ],
            correct="a",
            explanation="Defender XDR correlates signals across endpoints, identities, email, and cloud apps.",
            source_id="doc-defender-xdr",
            semantic_family_id="defender_xdr_workload_suite",
            tested_decision="xdr_correlates_across_workloads",
            batch=b,
        ),
        question_record(
            serial=90,
            leaf="defender_for_office_365",
            difficulty="beginner",
            stem_style="service_selection",
            stem="Which Defender service is designed to protect email, links, and collaboration content from phishing and malware?",
            choices=[
                ("a", "Microsoft Defender for Office 365"),
                ("b", "Azure Bastion"),
                ("c", "Azure Key Vault"),
                ("d", "Network security groups"),
            ],
            correct="a",
            explanation="Defender for Office 365 is the email and collaboration threat-protection workload.",
            source_id="doc-defender-office",
            semantic_family_id="defender_xdr_workload_suite",
            tested_decision="mdo_protects_email_collab",
            batch=b,
        ),
        question_record(
            serial=91,
            leaf="defender_for_endpoint",
            difficulty="beginner",
            stem_style="short_scenario",
            stem="Security wants behavioral detection and response on employee laptops. Which Defender workload is designed for that?",
            choices=[
                ("a", "Microsoft Defender for Endpoint"),
                ("b", "Microsoft Entra access reviews"),
                ("c", "Azure DDoS Protection"),
                ("d", "Purview records management"),
            ],
            correct="a",
            explanation="Defender for Endpoint is EDR/device protection. Reviews, DDoS, and records management are different jobs.",
            source_id="doc-defender-endpoint",
            semantic_family_id="defender_xdr_workload_suite",
            tested_decision="mde_for_laptop_edr",
            batch=b,
        ),
        question_record(
            serial=92,
            leaf="defender_for_cloud_apps",
            difficulty="beginner",
            stem_style="short_scenario",
            stem="The CISO wants to discover unsanctioned SaaS apps in use and apply controls to them. Which Defender service is the cloud access security broker for that?",
            choices=[
                ("a", "Microsoft Defender for Cloud Apps"),
                ("b", "Azure Firewall only"),
                ("c", "Temporary Access Pass"),
                ("d", "Compliance score"),
            ],
            correct="a",
            explanation="Defender for Cloud Apps (CASB) discovers and protects SaaS app usage, including shadow IT.",
            source_id="doc-defender-cloud-apps",
            semantic_family_id="defender_xdr_workload_suite",
            tested_decision="mcas_casb_shadow_it",
            batch=b,
        ),
        question_record(
            serial=93,
            leaf="defender_for_identity",
            difficulty="beginner",
            stem_style="capability_selection",
            stem="Which Defender service analyzes Active Directory signals for identity attacks such as reconnaissance and lateral movement?",
            choices=[
                ("a", "Microsoft Defender for Identity"),
                ("b", "Azure WAF"),
                ("c", "Purview DLP"),
                ("d", "Azure Bastion"),
            ],
            correct="a",
            explanation="Defender for Identity is the AD-focused identity threat detection workload.",
            source_id="doc-defender-identity",
            semantic_family_id="defender_xdr_workload_suite",
            tested_decision="mdi_ad_lateral_movement",
            batch=b,
        ),
        question_record(
            serial=94,
            leaf="defender_vulnerability_management",
            difficulty="beginner",
            stem_style="direct_concept",
            stem="Which capability discovers and helps prioritize software and configuration vulnerabilities?",
            choices=[
                ("a", "Microsoft Defender Vulnerability Management"),
                ("b", "Lifecycle Workflows"),
                ("c", "Service Trust Portal"),
                ("d", "Azure Bastion"),
            ],
            correct="a",
            explanation="Defender Vulnerability Management is the vulnerability discovery and prioritization capability.",
            source_id="doc-defender-vulnerability-management",
            semantic_family_id="defender_xdr_workload_suite",
            tested_decision="mdvm_prioritizes_weaknesses",
            batch=b,
        ),
        question_record(
            serial=95,
            leaf="defender_threat_intelligence",
            difficulty="beginner",
            stem_style="current_topic",
            stem="Which Microsoft capability provides threat-actor, infrastructure, and indicator intelligence to support investigations?",
            choices=[
                ("a", "Microsoft Defender Threat Intelligence"),
                ("b", "Retention labels"),
                ("c", "Entra Password Protection"),
                ("d", "Azure NSGs"),
            ],
            correct="a",
            explanation="Defender TI supplies intelligence context. Retention, password bans, and NSGs do not profile threat actors.",
            source_id="doc-defender-ti",
            semantic_family_id="defender_xdr_workload_suite",
            tested_decision="defender_ti_actor_infrastructure_intel",
            batch=b,
        ),
        question_record(
            serial=96,
            leaf="defender_portal",
            difficulty="beginner",
            stem_style="current_topic",
            stem="Where do security teams investigate unified Defender XDR incidents across endpoints, email, identities, and apps?",
            choices=[
                ("a", "The Microsoft Defender portal"),
                ("b", "Azure Key Vault"),
                ("c", "The Service Trust Portal only"),
                ("d", "Content explorer only"),
            ],
            correct="a",
            explanation="The Microsoft Defender portal is the unified XDR operations console. STP and Content explorer serve trust and classification viewing.",
            source_id="doc-defender-portal",
            semantic_family_id="defender_xdr_workload_suite",
            tested_decision="defender_portal_unified_incidents",
            batch=b,
        ),
        question_record(
            serial=97,
            leaf="azure_firewall",
            difficulty="intermediate",
            stem_style="concept_distinction",
            stem="Which comparison between Azure Firewall and NSGs is accurate?",
            choices=[
                (
                    "a",
                    "Azure Firewall is a centralized stateful network firewall; NSGs are distributed subnet/NIC filters",
                ),
                ("b", "NSGs inspect SQL injection in HTTP bodies"),
                ("c", "Azure Firewall recertifies Entra group membership"),
                ("d", "They are both Purview audit searches"),
            ],
            correct="a",
            explanation="Firewall is centralized/stateful; NSGs attach to subnets/NICs. WAF, not NSGs, inspects HTTP exploits.",
            source_id="module-describe-basic-security-capabilities-azure",
            semantic_family_id="azure_nsg_firewall_waf_ddos",
            tested_decision="firewall_central_nsg_distributed",
            batch=b,
        ),
        question_record(
            serial=98,
            leaf="azure_key_vault",
            difficulty="intermediate",
            stem_style="short_scenario",
            stem="An app needs a TLS certificate and a database connection string retrieved at runtime with access control. Which Azure service is designed for that?",
            choices=[
                ("a", "Azure Key Vault"),
                ("b", "Microsoft Defender for Identity"),
                ("c", "Azure DDoS Protection"),
                ("d", "Access reviews"),
            ],
            correct="a",
            explanation="Key Vault stores certificates and secrets with access control. The other services do not provide secret storage.",
            source_id="doc-key-vault",
            semantic_family_id="azure_key_vault",
            tested_decision="key_vault_certs_and_connection_strings",
            batch=b,
        ),
        question_record(
            serial=99,
            leaf="security_policies_standards_recommendations",
            difficulty="beginner",
            stem_style="direct_concept",
            stem="In Defender for Cloud, what do security policies and standards provide?",
            choices=[
                ("a", "The desired configuration baseline used to generate recommendations"),
                ("b", "A FIDO2 credential"),
                ("c", "A legal hold"),
                ("d", "A Bastion shareable link"),
            ],
            correct="a",
            explanation="Policies/standards define the posture baseline. Recommendations then show deviations from that baseline.",
            source_id="module-describe-security-management-capabilities-of-azure",
            semantic_family_id="defender_for_cloud_cspm_cwp",
            tested_decision="standards_drive_recommendations",
            batch=b,
        ),
        question_record(
            serial=100,
            leaf="sentinel_threat_detection_mitigation",
            difficulty="intermediate",
            stem_style="short_scenario",
            stem="Analysts want analytics rules to create incidents and playbooks to isolate a user automatically. Which service combines those SIEM and SOAR capabilities?",
            choices=[
                ("a", "Microsoft Sentinel"),
                ("b", "Azure WAF"),
                ("c", "Temporary Access Pass"),
                ("d", "Records management"),
            ],
            correct="a",
            explanation="Sentinel analytics rules detect and playbooks automate response. WAF, TAP, and records management do not provide that SIEM/SOAR pairing.",
            source_id="module-describe-security-capabilities-of-azure-sentinel",
            semantic_family_id="sentinel_siem_soar_automation",
            tested_decision="sentinel_rules_and_playbooks",
            batch=b,
        ),
    ]
