from __future__ import annotations

from tools.sc900_microsoft_corpus_qemit import question_record


def batch_05() -> list[dict]:
    b = "mlc-batch-05"
    return [
        question_record(
            serial=101,
            leaf="azure_ddos_protection",
            difficulty="intermediate",
            stem_style="concept_distinction",
            stem="A site is slow because of a UDP flood against its public IP, not because of malicious HTTP payloads. Which control is aimed at that class of attack?",
            choices=[
                ("a", "Azure DDoS Protection"),
                ("b", "Azure Web Application Firewall"),
                ("c", "Microsoft Entra ID Governance"),
                ("d", "Purview audit"),
            ],
            correct="a",
            explanation="Volumetric UDP floods are a DDoS Protection problem. WAF inspects HTTP application attacks, not L3/L4 floods.",
            source_id="module-describe-basic-security-capabilities-azure",
            semantic_family_id="azure_nsg_firewall_waf_ddos",
            tested_decision="ddos_not_waf_for_udp_flood",
            batch=b,
        ),
        question_record(
            serial=102,
            leaf="azure_web_application_firewall",
            difficulty="intermediate",
            stem_style="concept_distinction",
            stem="Why is Azure WAF not a substitute for Azure DDoS Protection?",
            choices=[
                ("a", "WAF inspects HTTP application attacks; DDoS Protection mitigates volumetric network floods"),
                ("b", "WAF recertifies Entra roles"),
                ("c", "DDoS Protection classifies documents"),
                ("d", "Both only store secrets"),
            ],
            correct="a",
            explanation="They operate at different layers and against different attack types.",
            source_id="doc-waf",
            semantic_family_id="azure_nsg_firewall_waf_ddos",
            tested_decision="waf_layer7_vs_ddos_layer34",
            batch=b,
        ),
        question_record(
            serial=103,
            leaf="network_security_groups",
            difficulty="intermediate",
            stem_style="short_scenario",
            stem="A subnet should allow 443 from a known prefix and deny other inbound traffic. Which control is the usual first filter at that subnet?",
            choices=[
                ("a", "A network security group"),
                ("b", "A sensitivity label"),
                ("c", "An access review"),
                ("d", "Defender TI"),
            ],
            correct="a",
            explanation="NSGs are the subnet/NIC allow-deny filter. Labels, reviews, and threat intel do not filter subnet packets.",
            source_id="module-describe-basic-security-capabilities-azure",
            semantic_family_id="azure_nsg_firewall_waf_ddos",
            tested_decision="nsg_allow_443_deny_rest",
            batch=b,
        ),
        question_record(
            serial=104,
            leaf="azure_virtual_network_segmentation",
            difficulty="intermediate",
            stem_style="short_scenario",
            stem="A payment app and a marketing website should not freely route to each other. Which Azure construct is used to isolate those workloads?",
            choices=[
                ("a", "Separate virtual networks or subnets with controlled connectivity"),
                ("b", "A single shared public IP for both"),
                ("c", "A Temporary Access Pass"),
                ("d", "A compliance score"),
            ],
            correct="a",
            explanation="VNet/subnet segmentation limits east-west communication. Shared public IPs, TAP, and compliance score do not isolate networks.",
            source_id="module-describe-basic-security-capabilities-azure",
            semantic_family_id="azure_virtual_network_segmentation",
            tested_decision="isolate_workloads_with_vnets",
            batch=b,
        ),
        question_record(
            serial=105,
            leaf="azure_bastion",
            difficulty="intermediate",
            stem_style="misconception_correction",
            stem="Which statement about Azure Bastion is correct?",
            choices=[
                ("a", "It provides secure VM management without opening public RDP/SSH ports on the target VMs"),
                ("b", "It is a SIEM"),
                ("c", "It is a DLP location"),
                ("d", "It replaces Entra ID"),
            ],
            correct="a",
            explanation="Bastion is a jump-host service. It is not SIEM, DLP, or an identity provider.",
            source_id="doc-bastion",
            semantic_family_id="azure_bastion",
            tested_decision="bastion_not_siem_or_idp",
            batch=b,
        ),
        question_record(
            serial=106,
            leaf="azure_key_vault",
            difficulty="beginner",
            stem_style="misconception_correction",
            stem="Which statement about Azure Key Vault is correct?",
            choices=[
                ("a", "It controls access to secrets, keys, and certificates"),
                ("b", "It is Microsoft's email anti-phishing service"),
                ("c", "It recertifies guest access"),
                ("d", "It publishes SOC reports"),
            ],
            correct="a",
            explanation="Key Vault is secrets/keys/certificates. Email phishing, guest recertification, and SOC reports are other products.",
            source_id="doc-key-vault",
            semantic_family_id="azure_key_vault",
            tested_decision="key_vault_not_email_security",
            batch=b,
        ),
        question_record(
            serial=107,
            leaf="microsoft_defender_for_cloud",
            difficulty="intermediate",
            stem_style="short_scenario",
            stem="A connected AWS account should appear in the same cloud security posture view as Azure. Which Microsoft service is designed to assess those connected clouds?",
            choices=[
                ("a", "Microsoft Defender for Cloud"),
                ("b", "Microsoft Entra Temporary Access Pass"),
                ("c", "Purview records management"),
                ("d", "Azure Bastion"),
            ],
            correct="a",
            explanation="Defender for Cloud can assess Azure and connected multicloud resources for posture.",
            source_id="doc-defender-for-cloud",
            semantic_family_id="defender_for_cloud_cspm_cwp",
            tested_decision="dfc_multicloud_posture",
            batch=b,
        ),
        question_record(
            serial=108,
            leaf="cloud_security_posture_management",
            difficulty="intermediate",
            stem_style="short_scenario",
            stem="Secure score dropped after several storage accounts were left public. Which capability class produced that posture finding?",
            choices=[
                ("a", "Cloud Security Posture Management"),
                ("b", "Just-in-time Entra PIM"),
                ("c", "Mailbox safe links"),
                ("d", "eDiscovery holds"),
            ],
            correct="a",
            explanation="Public storage is a configuration/posture issue, which is CSPM territory in Defender for Cloud.",
            source_id="doc-cspm",
            semantic_family_id="defender_for_cloud_cspm_cwp",
            tested_decision="public_storage_is_cspm_finding",
            batch=b,
        ),
        question_record(
            serial=109,
            leaf="security_policies_standards_recommendations",
            difficulty="intermediate",
            stem_style="short_scenario",
            stem="An administrator assigns a regulatory standard in Defender for Cloud and then sees a list of failing resources. What produced that list?",
            choices=[
                ("a", "Recommendations generated from the assigned standard"),
                ("b", "A FIDO2 registration"),
                ("c", "A Sentinel hunting bookmark only"),
                ("d", "A Bastion session recording"),
            ],
            correct="a",
            explanation="Assigned standards/policies create recommendations for resources that do not meet the baseline.",
            source_id="module-describe-security-management-capabilities-of-azure",
            semantic_family_id="defender_for_cloud_cspm_cwp",
            tested_decision="assigned_standard_creates_recommendations",
            batch=b,
        ),
        question_record(
            serial=110,
            leaf="cloud_workload_protection",
            difficulty="beginner",
            stem_style="short_scenario",
            stem="The team enabled an enhanced plan so Azure servers get malware and threat detection beyond configuration scoring. Which capability is that?",
            choices=[
                ("a", "Cloud workload protection"),
                ("b", "Access reviews"),
                ("c", "Service Trust Portal"),
                ("d", "Temporary Access Pass"),
            ],
            correct="a",
            explanation="Enhanced workload protection plans add threat detection for running servers and similar workloads.",
            source_id="module-describe-security-management-capabilities-of-azure",
            semantic_family_id="defender_for_cloud_cspm_cwp",
            tested_decision="cwp_plan_for_server_threats",
            batch=b,
        ),
        question_record(
            serial=111,
            leaf="siem_and_soar",
            difficulty="intermediate",
            stem_style="concept_distinction",
            stem="Which SIEM and SOAR pairing is accurate?",
            choices=[
                ("a", "SIEM detects and investigates; SOAR automates response"),
                ("b", "SIEM issues certificates; SOAR hashes disks"),
                ("c", "SIEM is only DLP; SOAR is only WAF"),
                ("d", "SIEM replaces Entra ID"),
            ],
            correct="a",
            explanation="That is the fundamentals SIEM versus SOAR distinction taught with Sentinel.",
            source_id="module-describe-security-capabilities-of-azure-sentinel",
            semantic_family_id="sentinel_siem_soar_automation",
            tested_decision="siem_detect_soar_respond",
            batch=b,
        ),
        question_record(
            serial=112,
            leaf="sentinel_threat_detection_mitigation",
            difficulty="beginner",
            stem_style="direct_concept",
            stem="Which Sentinel capability lets analysts search data proactively for threats that did not raise an incident?",
            choices=[
                ("a", "Hunting"),
                ("b", "Temporary Access Pass"),
                ("c", "Sensitivity label headers"),
                ("d", "Azure Bastion"),
            ],
            correct="a",
            explanation="Hunting is proactive threat search in Sentinel. The other options are authentication, labeling, or VM access.",
            source_id="doc-sentinel",
            semantic_family_id="sentinel_siem_soar_automation",
            tested_decision="sentinel_hunting_proactive",
            batch=b,
        ),
        question_record(
            serial=113,
            leaf="defender_xdr_services",
            difficulty="intermediate",
            stem_style="short_scenario",
            stem="An attack used a phishing email, then a compromised endpoint, then stolen AD credentials. Why does Microsoft position Defender XDR for this?",
            choices=[
                ("a", "It correlates those workload signals into a unified incident"),
                ("b", "It is the only way to create VNets"),
                ("c", "It replaces Key Vault"),
                ("d", "It is a retention label publisher"),
            ],
            correct="a",
            explanation="XDR is valuable because one incident can span email, endpoint, and identity workloads.",
            source_id="module-describe-threat-protection-with-microsoft-365-defender",
            semantic_family_id="defender_xdr_workload_suite",
            tested_decision="xdr_spans_email_endpoint_identity",
            batch=b,
        ),
        question_record(
            serial=114,
            leaf="defender_for_office_365",
            difficulty="intermediate",
            stem_style="concept_distinction",
            stem="Safe Links and Safe Attachments are associated with which Defender workload?",
            choices=[
                ("a", "Microsoft Defender for Office 365"),
                ("b", "Azure DDoS Protection"),
                ("c", "Microsoft Entra PIM"),
                ("d", "Azure Key Vault"),
            ],
            correct="a",
            explanation="Time-of-click link checking and attachment detonation are Defender for Office 365 features, not DDoS, PIM, or Key Vault.",
            source_id="module-describe-threat-protection-with-microsoft-365-defender",
            semantic_family_id="defender_xdr_workload_suite",
            tested_decision="safe_links_attachments_are_mdo",
            batch=b,
        ),
        question_record(
            serial=115,
            leaf="defender_for_endpoint",
            difficulty="intermediate",
            stem_style="concept_distinction",
            stem="Which statement correctly distinguishes Defender for Endpoint from Defender for Office 365?",
            choices=[
                ("a", "Endpoint protects devices with EDR; Office 365 protects email and collaboration content"),
                ("b", "They are both Azure Firewall SKUs"),
                ("c", "Endpoint recertifies guests"),
                ("d", "Office 365 stores VM secrets"),
            ],
            correct="a",
            explanation="The workloads protect different surfaces: devices versus email/collaboration.",
            source_id="doc-defender-endpoint",
            semantic_family_id="defender_xdr_workload_suite",
            tested_decision="mde_devices_vs_mdo_email",
            batch=b,
        ),
        question_record(
            serial=116,
            leaf="defender_for_cloud_apps",
            difficulty="intermediate",
            stem_style="concept_distinction",
            stem="How does Defender for Cloud Apps differ from Defender for Cloud?",
            choices=[
                (
                    "a",
                    "Cloud Apps is a CASB for SaaS usage; Defender for Cloud is cloud security posture and workload protection for cloud resources",
                ),
                ("b", "They are the same product"),
                ("c", "Cloud Apps is only DDoS mitigation"),
                ("d", "Defender for Cloud issues TAP codes"),
            ],
            correct="a",
            explanation="One is SaaS CASB; the other is CSPM/CWP for cloud infrastructure and workloads.",
            source_id="doc-defender-cloud-apps",
            semantic_family_id="defender_xdr_workload_suite",
            tested_decision="casb_vs_defender_for_cloud",
            batch=b,
        ),
        question_record(
            serial=117,
            leaf="defender_for_identity",
            difficulty="intermediate",
            stem_style="short_scenario",
            stem="Sensors report Kerberos Golden Ticket-style activity against on-premises Active Directory. Which Defender workload is designed for that signal source?",
            choices=[
                ("a", "Microsoft Defender for Identity"),
                ("b", "Azure WAF"),
                ("c", "Purview Content explorer"),
                ("d", "Azure Bastion"),
            ],
            correct="a",
            explanation="Defender for Identity is built around AD DS identity-attack detection.",
            source_id="doc-defender-identity",
            semantic_family_id="defender_xdr_workload_suite",
            tested_decision="mdi_for_ad_ticket_attacks",
            batch=b,
        ),
        question_record(
            serial=118,
            leaf="defender_vulnerability_management",
            difficulty="intermediate",
            stem_style="short_scenario",
            stem="Leadership wants a prioritized list of exposed software weaknesses on endpoints, not a SIEM correlation timeline. Which capability fits?",
            choices=[
                ("a", "Microsoft Defender Vulnerability Management"),
                ("b", "Microsoft Sentinel hunting"),
                ("c", "Lifecycle Workflows"),
                ("d", "Azure DDoS Protection"),
            ],
            correct="a",
            explanation="Vulnerability management prioritizes weaknesses. Hunting is SIEM investigation; the others are identity lifecycle or network floods.",
            source_id="doc-defender-vulnerability-management",
            semantic_family_id="defender_xdr_workload_suite",
            tested_decision="mdvm_not_siem_timeline",
            batch=b,
        ),
        question_record(
            serial=119,
            leaf="defender_threat_intelligence",
            difficulty="intermediate",
            stem_style="short_scenario",
            stem="An analyst has a suspicious domain and wants known campaign context before responding. Which current Defender capability is intended for that intel lookup?",
            choices=[
                ("a", "Microsoft Defender Threat Intelligence"),
                ("b", "Temporary Access Pass"),
                ("c", "NSG service tags"),
                ("d", "Retention labels"),
            ],
            correct="a",
            explanation="Defender TI is the intelligence lookup for indicators and campaigns.",
            source_id="module-describe-threat-protection-with-microsoft-365-defender",
            semantic_family_id="defender_xdr_workload_suite",
            tested_decision="ti_lookup_suspicious_domain",
            batch=b,
        ),
        question_record(
            serial=120,
            leaf="defender_portal",
            difficulty="intermediate",
            stem_style="short_scenario",
            stem="Instead of opening separate consoles for email, device, and identity alerts, analysts want one incident queue. Which portal is that?",
            choices=[
                ("a", "Microsoft Defender portal"),
                ("b", "Service Trust Portal"),
                ("c", "Azure Key Vault"),
                ("d", "Purview Content explorer"),
            ],
            correct="a",
            explanation="The Defender portal unifies XDR incident queues. STP, Key Vault, and Content explorer are not that operations console.",
            source_id="module-describe-threat-protection-with-microsoft-365-defender",
            semantic_family_id="defender_xdr_workload_suite",
            tested_decision="one_queue_in_defender_portal",
            batch=b,
        ),
        question_record(
            serial=121,
            leaf="azure_firewall",
            difficulty="beginner",
            stem_style="short_scenario",
            stem="Outbound traffic from several VNets should be filtered with centrally managed network and application rules. Which service is designed for that?",
            choices=[
                ("a", "Azure Firewall"),
                ("b", "Microsoft Entra ID Protection"),
                ("c", "Purview Insider Risk Management"),
                ("d", "Defender for Office 365"),
            ],
            correct="a",
            explanation="Azure Firewall provides centralized network and application rule filtering across VNets, often via hub-and-spoke.",
            source_id="doc-azure-firewall",
            semantic_family_id="azure_nsg_firewall_waf_ddos",
            tested_decision="firewall_central_outbound_filter",
            batch=b,
        ),
        question_record(
            serial=122,
            leaf="azure_ddos_protection",
            difficulty="beginner",
            stem_style="misconception_correction",
            stem="Which statement about Azure DDoS Protection is correct?",
            choices=[
                ("a", "It helps protect public Azure resources from volumetric denial-of-service attacks"),
                ("b", "It is an email Safe Attachments feature"),
                ("c", "It recertifies privileged roles"),
                ("d", "It is Content explorer"),
            ],
            correct="a",
            explanation="DDoS Protection is volumetric network protection for public Azure resources.",
            source_id="doc-ddos",
            semantic_family_id="azure_nsg_firewall_waf_ddos",
            tested_decision="ddos_not_safe_attachments",
            batch=b,
        ),
        question_record(
            serial=123,
            leaf="network_security_groups",
            difficulty="beginner",
            stem_style="misconception_correction",
            stem="Which statement about NSGs is correct?",
            choices=[
                ("a", "They filter traffic to subnets or NICs using allow and deny rules"),
                ("b", "They issue Entra tokens"),
                ("c", "They hold email for lawsuits"),
                ("d", "They store TLS private keys as their primary purpose"),
            ],
            correct="a",
            explanation="NSGs are packet filters. Tokens, eDiscovery, and Key Vault are other services.",
            source_id="doc-nsg",
            semantic_family_id="azure_nsg_firewall_waf_ddos",
            tested_decision="nsg_not_token_issuer",
            batch=b,
        ),
        question_record(
            serial=124,
            leaf="azure_key_vault",
            difficulty="intermediate",
            stem_style="concept_distinction",
            stem="Why is Key Vault a better place for a database password than an application configuration file in source control?",
            choices=[
                ("a", "Key Vault provides access-controlled secret storage instead of exposing secrets in code"),
                ("b", "Key Vault is a WAF"),
                ("c", "Source control cannot store text files"),
                ("d", "Key Vault recertifies guests"),
            ],
            correct="a",
            explanation="The fundamentals reason is access-controlled secret storage rather than secrets in code.",
            source_id="doc-key-vault",
            semantic_family_id="azure_key_vault",
            tested_decision="secrets_out_of_source_control",
            batch=b,
        ),
        question_record(
            serial=125,
            leaf="microsoft_defender_for_cloud",
            difficulty="beginner",
            stem_style="misconception_correction",
            stem="Which statement about Microsoft Defender for Cloud is correct?",
            choices=[
                ("a", "It helps improve cloud security posture and can add workload threat protection"),
                ("b", "It is the Entra passwordless TAP service"),
                ("c", "It is only a records repository"),
                ("d", "It replaces virtual networks"),
            ],
            correct="a",
            explanation="Defender for Cloud combines posture management with optional workload protection plans.",
            source_id="doc-defender-for-cloud",
            semantic_family_id="defender_for_cloud_cspm_cwp",
            tested_decision="dfc_posture_plus_optional_cwp",
            batch=b,
        ),
    ]
