from __future__ import annotations

from tools.sc900_microsoft_corpus_qemit import question_record


def batch_08() -> list[dict]:
    b = "mlc-batch-08"
    return [
        question_record(
            serial=176,
            leaf="shared_responsibility_model",
            difficulty="beginner",
            stem_style="short_scenario",
            stem="In a PaaS web app, who is typically responsible for patching the application code and managing the app's identities and data?",
            choices=[
                ("a", "The customer"),
                ("b", "Only the regional utility company"),
                ("c", "A random internet stranger"),
                ("d", "The hardware vendor of Microsoft's racks exclusively, with no customer duties"),
            ],
            correct="a",
            explanation="Even in PaaS, customers remain responsible for their application, identities, and data. Microsoft manages more of the platform underneath.",
            source_id="doc-shared-responsibility",
            semantic_family_id="shared_responsibility_model",
            tested_decision="paas_customer_still_owns_app_data",
            batch=b,
        ),
        question_record(
            serial=177,
            leaf="encryption_and_hashing",
            difficulty="intermediate",
            stem_style="concept_distinction",
            stem="Digital signing is closest to which security goal?",
            choices=[
                (
                    "a",
                    "Integrity and authenticity of data, using cryptography rather than reversible confidentiality alone",
                ),
                ("b", "Opening RDP to the internet"),
                ("c", "Recertifying guest users"),
                ("d", "Mitigating UDP floods"),
            ],
            correct="a",
            explanation="Signing supports integrity/authenticity. The SC-900 encryption-and-hashing lesson groups encryption, hashing, and signing as complementary cryptographic protections.",
            source_id="module-describe-security-concepts-methodologies",
            semantic_family_id="encryption_and_hashing",
            tested_decision="signing_integrity_authenticity",
            batch=b,
        ),
        question_record(
            serial=178,
            leaf="identity_providers",
            difficulty="intermediate",
            stem_style="short_scenario",
            stem="Users sign in once to Microsoft Entra ID and then open several SaaS apps without storing passwords in each app. Which identity-provider benefit is that?",
            choices=[
                ("a", "Single sign-on"),
                ("b", "DDoS mitigation"),
                ("c", "Records declaration"),
                ("d", "NSG filtering"),
            ],
            correct="a",
            explanation="A shared identity provider enables SSO so apps trust issued tokens instead of local passwords.",
            source_id="module-describe-identity-principles-concepts",
            semantic_family_id="federation_and_identity_providers",
            tested_decision="idp_enables_sso",
            batch=b,
        ),
        question_record(
            serial=179,
            leaf="directory_services_active_directory",
            difficulty="intermediate",
            stem_style="concept_distinction",
            stem="Which statement correctly distinguishes AD DS from Microsoft Entra ID?",
            choices=[
                ("a", "AD DS is the traditional on-premises directory; Entra ID is Microsoft's cloud identity service"),
                ("b", "They are both Azure WAF policies"),
                ("c", "AD DS is eDiscovery"),
                ("d", "Entra ID is only DDoS Protection"),
            ],
            correct="a",
            explanation="AD DS is on-premises directory services. Entra ID is the cloud IAM directory. Hybrid identity can connect them.",
            source_id="module-describe-identity-principles-concepts",
            semantic_family_id="entra_hybrid_identity_and_ad",
            tested_decision="ad_ds_onprem_entra_cloud",
            batch=b,
        ),
        question_record(
            serial=180,
            leaf="compliance_score",
            difficulty="beginner",
            stem_style="direct_concept",
            stem="What does a higher compliance score indicate in Compliance Manager?",
            choices=[
                ("a", "More of the recommended improvement actions are implemented"),
                ("b", "A larger DDoS attack was absorbed"),
                ("c", "More public IPs were assigned"),
                ("d", "MFA was disabled"),
            ],
            correct="a",
            explanation="Compliance score estimates progress implementing recommended controls/improvement actions.",
            source_id="doc-compliance-score",
            semantic_family_id="service_trust_privacy_compliance_manager",
            tested_decision="higher_score_more_actions_done",
            batch=b,
        ),
        question_record(
            serial=181,
            leaf="microsoft_privacy_principles",
            difficulty="intermediate",
            stem_style="misconception_correction",
            stem="Which statement about Microsoft privacy principles is correct?",
            choices=[
                ("a", "They include commitments such as transparency and protection of customer data"),
                ("b", "They require customers to publish all passwords"),
                ("c", "They replace the shared responsibility model"),
                ("d", "They are Azure Firewall SKUs"),
            ],
            correct="a",
            explanation="Privacy principles cover how Microsoft handles data, including transparency and protection, and do not replace shared responsibility or firewalls.",
            source_id="module-describe-compliance-management-capabilities-microsoft",
            semantic_family_id="service_trust_privacy_compliance_manager",
            tested_decision="privacy_transparency_and_protection",
            batch=b,
        ),
        question_record(
            serial=182,
            leaf="purview_portal",
            difficulty="beginner",
            stem_style="misconception_correction",
            stem="Which statement about the Microsoft Purview portal is correct?",
            choices=[
                ("a", "It is the workspace for Purview compliance and data-governance tools"),
                ("b", "It is Azure DDoS Protection"),
                ("c", "It is Temporary Access Pass"),
                ("d", "It is Key Vault"),
            ],
            correct="a",
            explanation="The Purview portal is the compliance/data-governance console, not a network or secret store.",
            source_id="doc-purview-portal",
            semantic_family_id="purview_portal",
            tested_decision="purview_portal_not_key_vault",
            batch=b,
        ),
        question_record(
            serial=183,
            leaf="compliance_manager",
            difficulty="beginner",
            stem_style="misconception_correction",
            stem="Which statement about Compliance Manager is correct?",
            choices=[
                ("a", "It helps the customer manage their own compliance assessments and improvement actions"),
                ("b", "It is Microsoft's DDoS scrubbing network"),
                ("c", "It is Defender for Endpoint"),
                ("d", "It is Azure Bastion"),
            ],
            correct="a",
            explanation="Compliance Manager is the customer's assessment tool, not XDR, DDoS, or Bastion.",
            source_id="doc-compliance-manager",
            semantic_family_id="service_trust_privacy_compliance_manager",
            tested_decision="cm_not_ddos",
            batch=b,
        ),
        question_record(
            serial=184,
            leaf="data_classification",
            difficulty="beginner",
            stem_style="misconception_correction",
            stem="Which statement about Purview data classification is correct?",
            choices=[
                ("a", "It helps the organization understand what sensitive data it has and where it lives"),
                ("b", "It is a VPN replacement"),
                ("c", "It issues Entra roles"),
                ("d", "It is Azure Firewall"),
            ],
            correct="a",
            explanation="Classification is discovery and categorization of sensitive items.",
            source_id="doc-data-classification",
            semantic_family_id="purview_information_protection_lifecycle",
            tested_decision="classification_not_vpn",
            batch=b,
        ),
        question_record(
            serial=185,
            leaf="content_and_activity_explorer",
            difficulty="beginner",
            stem_style="short_scenario",
            stem="An admin wants to see which files in SharePoint currently have a Highly Confidential label. Which explorer is designed to show that inventory?",
            choices=[
                ("a", "Content explorer"),
                ("b", "Azure Bastion"),
                ("c", "DDoS Protection metrics"),
                ("d", "PIM activations"),
            ],
            correct="a",
            explanation="Content explorer shows where labeled/classified items are stored.",
            source_id="doc-content-explorer",
            semantic_family_id="purview_information_protection_lifecycle",
            tested_decision="content_explorer_labeled_file_inventory",
            batch=b,
        ),
        question_record(
            serial=186,
            leaf="content_and_activity_explorer",
            difficulty="intermediate",
            stem_style="short_scenario",
            stem="An admin wants to see whether users are downgrading labels or triggering DLP matches over time. Which explorer is designed for those events?",
            choices=[("a", "Activity explorer"), ("b", "Azure Firewall"), ("c", "Key Vault"), ("d", "Azure Bastion")],
            correct="a",
            explanation="Activity explorer shows labeling, sharing, and DLP-related activities on classified content.",
            source_id="doc-activity-explorer",
            semantic_family_id="purview_information_protection_lifecycle",
            tested_decision="activity_explorer_label_and_dlp_events",
            batch=b,
        ),
        question_record(
            serial=187,
            leaf="sensitivity_labels_and_policies",
            difficulty="beginner",
            stem_style="misconception_correction",
            stem="Which statement about sensitivity labels is correct?",
            choices=[
                ("a", "They can persist with content and apply protection such as encryption or markings"),
                ("b", "They are NSG 5-tuple rules"),
                ("c", "They are Sentinel playbooks"),
                ("d", "They are TAP codes"),
            ],
            correct="a",
            explanation="Labels travel with content and can enforce protection. They are not network rules, playbooks, or TAP.",
            source_id="doc-sensitivity-labels",
            semantic_family_id="purview_information_protection_lifecycle",
            tested_decision="labels_persist_with_content",
            batch=b,
        ),
        question_record(
            serial=188,
            leaf="data_loss_prevention",
            difficulty="beginner",
            stem_style="misconception_correction",
            stem="Which statement about DLP is correct?",
            choices=[
                ("a", "DLP helps prevent sensitive information from being shared inappropriately"),
                ("b", "DLP is Azure DDoS Protection"),
                ("c", "DLP is Privileged Identity Management"),
                ("d", "DLP is Key Vault"),
            ],
            correct="a",
            explanation="DLP is a sharing/exfiltration control, not DDoS, PIM, or secret storage.",
            source_id="doc-dlp",
            semantic_family_id="purview_information_protection_lifecycle",
            tested_decision="dlp_not_pim",
            batch=b,
        ),
        question_record(
            serial=189,
            leaf="retention_policies_labels",
            difficulty="beginner",
            stem_style="short_scenario",
            stem="Email in all mailboxes must be kept for seven years. Which Purview construct is designed to apply that keep requirement broadly to the Exchange location?",
            choices=[("a", "A retention policy"), ("b", "Azure Bastion"), ("c", "An NSG"), ("d", "A FIDO2 key")],
            correct="a",
            explanation="Retention policies apply keep/delete settings to locations such as Exchange.",
            source_id="doc-retention",
            semantic_family_id="purview_information_protection_lifecycle",
            tested_decision="retention_policy_for_all_mailboxes",
            batch=b,
        ),
        question_record(
            serial=190,
            leaf="records_management",
            difficulty="beginner",
            stem_style="short_scenario",
            stem="Contracts must be declared as records so staff cannot edit them while they are retained. Which Purview capability is that?",
            choices=[
                ("a", "Records management"),
                ("b", "Azure WAF"),
                ("c", "Defender TI"),
                ("d", "Temporary Access Pass"),
            ],
            correct="a",
            explanation="Records management declares items as records with restrictive retention behavior.",
            source_id="module-describe-purview-risk-compliance-governance",
            semantic_family_id="purview_information_protection_lifecycle",
            tested_decision="contracts_declared_as_records",
            batch=b,
        ),
        question_record(
            serial=191,
            leaf="insider_risk_management",
            difficulty="beginner",
            stem_style="misconception_correction",
            stem="Which statement about Insider Risk Management is correct?",
            choices=[
                (
                    "a",
                    "It is designed to identify potentially risky internal user activities with privacy-aware investigation",
                ),
                ("b", "It is Azure Firewall"),
                ("c", "It is DDoS Protection"),
                ("d", "It is Key Vault"),
            ],
            correct="a",
            explanation="Insider Risk Management is an internal-risk compliance solution, not a network or secret store.",
            source_id="doc-insider-risk",
            semantic_family_id="purview_audit_ediscovery_insider_risk",
            tested_decision="irm_not_firewall",
            batch=b,
        ),
        question_record(
            serial=192,
            leaf="ediscovery",
            difficulty="beginner",
            stem_style="misconception_correction",
            stem="Which statement about Purview eDiscovery is correct?",
            choices=[
                ("a", "It helps find, hold, and export content for investigations and legal matters"),
                ("b", "It is Conditional Access"),
                ("c", "It is Azure Bastion"),
                ("d", "It is Password Protection"),
            ],
            correct="a",
            explanation="eDiscovery is legal/investigative collection, not access policy, jump-hosts, or password bans.",
            source_id="doc-ediscovery",
            semantic_family_id="purview_audit_ediscovery_insider_risk",
            tested_decision="ediscovery_not_conditional_access",
            batch=b,
        ),
        question_record(
            serial=193,
            leaf="audit",
            difficulty="beginner",
            stem_style="short_scenario",
            stem="Someone changed a sharing policy yesterday and leadership wants the admin activity trail. Which Purview solution is designed for that search?",
            choices=[("a", "Audit"), ("b", "Azure DDoS Protection"), ("c", "Windows Hello"), ("d", "Azure WAF")],
            correct="a",
            explanation="Audit searches recorded admin and user activities.",
            source_id="module-describe-purview-risk-compliance-governance",
            semantic_family_id="purview_audit_ediscovery_insider_risk",
            tested_decision="audit_admin_activity_trail",
            batch=b,
        ),
        question_record(
            serial=194,
            leaf="service_trust_portal_offerings",
            difficulty="beginner",
            stem_style="misconception_correction",
            stem="Which statement about the Service Trust Portal is correct?",
            choices=[
                ("a", "Customers use it to review Microsoft trust and compliance documentation"),
                ("b", "It is Defender for Endpoint"),
                ("c", "It is an NSG"),
                ("d", "It is PIM"),
            ],
            correct="a",
            explanation="STP is Microsoft's trust documentation portal, not XDR, NSGs, or PIM.",
            source_id="doc-service-trust-portal",
            semantic_family_id="service_trust_privacy_compliance_manager",
            tested_decision="stp_not_defender_endpoint",
            batch=b,
        ),
        question_record(
            serial=195,
            leaf="compliance_score",
            difficulty="beginner",
            stem_style="misconception_correction",
            stem="Which statement about compliance score is correct?",
            choices=[
                ("a", "It helps prioritize remaining Compliance Manager improvement actions"),
                ("b", "It is Azure DDoS Protection capacity"),
                ("c", "It is a Key Vault SKU"),
                ("d", "It is Bastion throughput"),
            ],
            correct="a",
            explanation="Compliance score is a Compliance Manager progress metric, not a network or Key Vault SKU.",
            source_id="doc-compliance-score",
            semantic_family_id="service_trust_privacy_compliance_manager",
            tested_decision="score_prioritizes_remaining_actions",
            batch=b,
        ),
        question_record(
            serial=196,
            leaf="data_loss_prevention",
            difficulty="intermediate",
            stem_style="short_scenario",
            stem="Teams chat should warn users before they paste a government ID number. Which Purview capability is designed for that sharing control?",
            choices=[
                ("a", "Data loss prevention"),
                ("b", "Azure Bastion"),
                ("c", "DDoS Protection"),
                ("d", "Access reviews"),
            ],
            correct="a",
            explanation="DLP can monitor and constrain sharing of sensitive information in collaboration locations such as Teams.",
            source_id="module-describe-purview-data-solutions",
            semantic_family_id="purview_information_protection_lifecycle",
            tested_decision="dlp_in_teams_chat",
            batch=b,
        ),
        question_record(
            serial=197,
            leaf="sensitivity_labels_and_policies",
            difficulty="intermediate",
            stem_style="concept_distinction",
            stem="How do sensitivity labels differ from retention labels?",
            choices=[
                (
                    "a",
                    "Sensitivity labels classify/protect content; retention labels control how long content is kept or deleted",
                ),
                ("b", "They are identical"),
                ("c", "Retention labels mitigate DDoS"),
                ("d", "Sensitivity labels assign Entra Global Administrator"),
            ],
            correct="a",
            explanation="Sensitivity is classification/protection. Retention is keep/delete lifecycle. They can coexist on an item.",
            source_id="doc-sensitivity-labels",
            semantic_family_id="purview_information_protection_lifecycle",
            tested_decision="sensitivity_vs_retention_labels",
            batch=b,
        ),
        question_record(
            serial=198,
            leaf="insider_risk_management",
            difficulty="intermediate",
            stem_style="short_scenario",
            stem="HR suspects departing employees are uploading source code to personal cloud storage. Which Purview solution is designed for that internal-risk scenario?",
            choices=[
                ("a", "Insider Risk Management"),
                ("b", "Azure WAF"),
                ("c", "Azure DDoS Protection"),
                ("d", "Temporary Access Pass"),
            ],
            correct="a",
            explanation="Potential data theft by departing insiders is an Insider Risk Management scenario, not WAF, DDoS, or TAP.",
            source_id="doc-insider-risk",
            semantic_family_id="purview_audit_ediscovery_insider_risk",
            tested_decision="departing_employee_exfil_irm",
            batch=b,
        ),
        question_record(
            serial=199,
            leaf="ediscovery",
            difficulty="beginner",
            stem_style="direct_concept",
            stem="What can Purview eDiscovery do with content in a legal matter?",
            choices=[
                ("a", "Search, hold, review, and export it"),
                ("b", "Assign Azure Firewall rules"),
                ("c", "Issue FIDO2 credentials"),
                ("d", "Create NSGs"),
            ],
            correct="a",
            explanation="eDiscovery workflows search, preserve, review, and export. They do not manage firewalls, FIDO2, or NSGs.",
            source_id="doc-ediscovery",
            semantic_family_id="purview_audit_ediscovery_insider_risk",
            tested_decision="ediscovery_search_hold_export",
            batch=b,
        ),
        question_record(
            serial=200,
            leaf="audit",
            difficulty="intermediate",
            stem_style="short_scenario",
            stem="After a DLP policy change, investigators need to confirm which admin changed it and when. Which capability provides that trail?",
            choices=[
                ("a", "Microsoft Purview audit"),
                ("b", "Azure DDoS Protection"),
                ("c", "Windows Hello"),
                ("d", "Azure Bastion"),
            ],
            correct="a",
            explanation="Audit records administrative configuration changes. DDoS, Windows Hello, and Bastion do not provide that compliance trail.",
            source_id="doc-audit",
            semantic_family_id="purview_audit_ediscovery_insider_risk",
            tested_decision="audit_tracks_dlp_policy_changes",
            batch=b,
        ),
    ]
