from __future__ import annotations

from tools.sc900_microsoft_corpus_qemit import question_record


def batch_11() -> list[dict]:
    b = "mlc-batch-11"
    return [
        question_record(
            serial=251,
            leaf="azure_web_application_firewall",
            difficulty="intermediate",
            stem_style="capability_selection",
            stem="A company publishes an Azure web app and wants managed rules that catch common OWASP web attacks. Which service is the fundamentals fit?",
            choices=[
                ("a", "Azure Web Application Firewall associated with the published web front end"),
                ("b", "Microsoft Entra access reviews"),
                ("c", "Privileged Identity Management"),
                ("d", "Microsoft Purview records management"),
            ],
            correct="a",
            explanation="WAF managed rules protect published web applications from common HTTP attacks. Access reviews, PIM, and records management do not inspect web requests.",
            source_id="doc-waf",
            semantic_family_id="azure_nsg_firewall_waf_ddos",
            tested_decision="waf_managed_rules_for_published_web_apps",
            batch=b,
        ),
        question_record(
            serial=252,
            leaf="microsoft_defender_for_cloud",
            difficulty="intermediate",
            stem_style="short_scenario",
            stem="An Azure subscription already has posture recommendations. Security also wants Microsoft 365 email, device, and identity incidents in one XDR queue. Why is Defender for Cloud not that XDR queue?",
            choices=[
                (
                    "a",
                    "Defender for Cloud is cloud-security posture and workload protection; Microsoft Defender XDR unifies Microsoft 365 Defender workload incidents",
                ),
                ("b", "Defender for Cloud is the Microsoft Defender portal incident queue"),
                ("c", "Defender for Cloud replaces Defender for Office 365 Safe Links"),
                ("d", "Defender for Cloud is Microsoft Entra ID"),
            ],
            correct="a",
            explanation="Defender for Cloud is Azure/multicloud posture and workload protection. The Microsoft 365 Defender XDR family and Defender portal incident queue are a different control plane.",
            source_id="doc-defender-for-cloud",
            semantic_family_id="defender_for_cloud_cspm_cwp",
            tested_decision="dfc_is_not_m365_defender_xdr_queue",
            batch=b,
        ),
        question_record(
            serial=253,
            leaf="cloud_security_posture_management",
            difficulty="intermediate",
            stem_style="concept_distinction",
            stem="CSPM reports a SQL database with public exposure. Separately, EDR shows a malicious process on a VM. Which statement keeps those findings in the right capability class?",
            choices=[
                (
                    "a",
                    "The public-exposure finding is posture/misconfiguration; the malicious process is runtime threat detection",
                ),
                ("b", "Both findings are Privileged Identity Management activations"),
                ("c", "Both findings are retention-label events"),
                ("d", "CSPM is the only Microsoft EDR sensor"),
            ],
            correct="a",
            explanation="Public exposure is a CSPM posture issue. A malicious process is runtime detection such as workload protection or EDR. Mixing those classes hides the right control.",
            source_id="doc-cspm",
            semantic_family_id="defender_for_cloud_cspm_cwp",
            tested_decision="posture_finding_vs_runtime_process_detection",
            batch=b,
        ),
        question_record(
            serial=254,
            leaf="cloud_workload_protection",
            difficulty="intermediate",
            stem_style="short_scenario",
            stem="A Linux server in Azure needs Defender for Cloud workload protection. A user laptop needs Microsoft Defender for Endpoint. Which statement is accurate?",
            choices=[
                (
                    "a",
                    "Defender for Servers is a cloud workload protection plan; Defender for Endpoint is the Microsoft 365 device EDR workload",
                ),
                ("b", "They are the same SKU and the same portal queue"),
                ("c", "Defender for Endpoint is only for Azure SQL databases"),
                ("d", "Defender for Servers replaces Microsoft Entra ID Protection"),
            ],
            correct="a",
            explanation="Cloud workload protection plans such as Defender for Servers protect cloud/server workloads in Defender for Cloud. Defender for Endpoint is the Microsoft 365 XDR device workload. Learners should not collapse them into one product.",
            source_id="doc-cwp",
            semantic_family_id="defender_for_cloud_cspm_cwp",
            tested_decision="defender_for_servers_cwp_not_m365_mde",
            batch=b,
        ),
        question_record(
            serial=255,
            leaf="security_policies_standards_recommendations",
            difficulty="intermediate",
            stem_style="short_scenario",
            stem="Assigning a security standard in Defender for Cloud created recommendations. A learner says those recommendations are Microsoft Purview improvement actions. What is wrong?",
            choices=[
                (
                    "a",
                    "Defender for Cloud recommendations close Azure/multicloud posture gaps; Compliance Manager improvement actions track customer compliance controls",
                ),
                ("b", "Purview improvement actions are the only way to encrypt Azure disks"),
                ("c", "Defender for Cloud recommendations recertify Entra guest groups"),
                ("d", "They are the same because both are Azure Bastion logs"),
            ],
            correct="a",
            explanation="Standards-driven recommendations in Defender for Cloud are cloud-posture work. Compliance Manager improvement actions are a Purview compliance-management concept.",
            source_id="module-describe-security-management-capabilities-of-azure",
            semantic_family_id="defender_for_cloud_cspm_cwp",
            tested_decision="dfc_recommendations_not_compliance_manager_actions",
            batch=b,
        ),
        question_record(
            serial=256,
            leaf="siem_and_soar",
            difficulty="intermediate",
            stem_style="multi_select",
            stem="A SOC deploys Microsoft Sentinel and correlates alerts well but still handles every response by hand. Which gap is that?",
            choices=[
                ("a", "SIEM detection without SOAR automation leaves repeatable response steps manual"),
                ("b", "Sentinel cannot be a SIEM unless Azure Bastion is enabled"),
                ("c", "Manual response means hashing has replaced SOAR"),
                ("d", "The SOC must switch to records management to automate containment"),
            ],
            correct="a",
            explanation="A SIEM can detect and investigate without automatically responding. SOAR/playbooks are what automate repeatable response. Detection alone is not full SOAR.",
            source_id="module-describe-security-capabilities-of-azure-sentinel",
            semantic_family_id="sentinel_siem_soar_automation",
            tested_decision="siem_without_soar_keeps_response_manual",
            qtype="multiple_choice",
            batch=b,
        ),
        question_record(
            serial=257,
            leaf="sentinel_threat_detection_mitigation",
            difficulty="intermediate",
            stem_style="short_scenario",
            stem="A company wants one SIEM to ingest Microsoft 365, Azure, and third-party firewall logs. Why is Microsoft Defender XDR not a complete substitute?",
            choices=[
                (
                    "a",
                    "Defender XDR correlates Microsoft workload signals; Sentinel is the cloud SIEM that is designed to ingest a broad set of sources including non-Microsoft logs",
                ),
                ("b", "Defender XDR is the only Microsoft service that can store firewall syslog"),
                ("c", "Sentinel cannot ingest Microsoft 365 logs"),
                ("d", "Third-party firewall logs can be ingested only by Azure Bastion"),
            ],
            correct="a",
            explanation="XDR is optimized around Microsoft Defender workloads. Sentinel is the SIEM that can connect many data sources, including non-Microsoft logs.",
            source_id="doc-sentinel",
            semantic_family_id="sentinel_siem_soar_automation",
            tested_decision="sentinel_ingests_third_party_logs_xdr_does_not_replace",
            batch=b,
        ),
        question_record(
            serial=258,
            leaf="sentinel_threat_detection_mitigation",
            difficulty="intermediate",
            stem_style="concept_distinction",
            stem="Leadership asks whether Microsoft Sentinel and Microsoft Defender XDR are the same product. Which distinction is accurate?",
            choices=[
                (
                    "a",
                    "Sentinel is a cloud SIEM/SOAR that can ingest many sources; Defender XDR correlates Microsoft workload signals into a unified incident view",
                ),
                ("b", "Defender XDR is the only Microsoft SIEM, and Sentinel is only a WAF"),
                ("c", "Sentinel replaces Entra ID, and Defender XDR replaces Azure virtual networks"),
                ("d", "They are identical names for Compliance Manager"),
            ],
            correct="a",
            explanation="Sentinel is SIEM/SOAR across diverse logs. Defender XDR natively correlates Microsoft 365 Defender workloads. They integrate but are not the same control.",
            source_id="doc-sentinel",
            semantic_family_id="sentinel_siem_soar_automation",
            tested_decision="sentinel_siem_vs_defender_xdr_workload_correlation",
            misconception_target="sentinel_equals_defender_xdr",
            batch=b,
        ),
        question_record(
            serial=259,
            leaf="defender_xdr_services",
            difficulty="intermediate",
            stem_style="short_scenario",
            stem="Which service is not a Microsoft Defender XDR workload in current SC-900 training?",
            choices=[
                ("a", "Azure Firewall"),
                ("b", "Microsoft Defender for Endpoint"),
                ("c", "Microsoft Defender for Office 365"),
                ("d", "Microsoft Defender for Identity"),
            ],
            correct="a",
            explanation="Defender for Endpoint, Office 365, and Identity are XDR workloads. Azure Firewall is an Azure network control, not a Defender XDR workload.",
            source_id="doc-defender-xdr",
            semantic_family_id="defender_xdr_workload_suite",
            tested_decision="azure_firewall_is_not_an_xdr_workload",
            batch=b,
        ),
        question_record(
            serial=260,
            leaf="defender_for_office_365",
            difficulty="intermediate",
            stem_style="capability_selection",
            stem="Safe Attachments detonates email files in a sandbox. Safe Links checks URLs when users click them. Which statement is accurate?",
            choices=[
                ("a", "They are complementary Defender for Office 365 controls for files versus URLs"),
                ("b", "Safe Links replaces Safe Attachments, so file detonation is never needed"),
                ("c", "Both features are Azure Firewall DNAT rules"),
                ("d", "Safe Attachments is a Conditional Access named location"),
            ],
            correct="a",
            explanation="Safe Attachments and Safe Links address different email/collaboration objects: files and URLs. Current SC-900 training treats both as Defender for Office 365 capabilities.",
            source_id="doc-defender-office",
            semantic_family_id="defender_xdr_workload_suite",
            tested_decision="mdo_safe_attachments_files_vs_safe_links_urls",
            batch=b,
        ),
        question_record(
            serial=261,
            leaf="defender_for_endpoint",
            difficulty="intermediate",
            stem_style="concept_distinction",
            stem="A workstation needs behavioral blocking and forensic investigation of a running process. A domain controller needs detections for ticket theft. Which pairing is accurate?",
            choices=[
                (
                    "a",
                    "Defender for Endpoint for the workstation EDR; Defender for Identity for Active Directory identity attacks",
                ),
                ("b", "Defender for Identity is the laptop EDR agent"),
                (
                    "c",
                    "Defender for Endpoint analyzes Kerberos ticket attacks on domain controllers as its primary job",
                ),
                ("d", "Both needs are met only by Azure WAF"),
            ],
            correct="a",
            explanation="Endpoint EDR and Active Directory identity threat detection are different Defender workloads. Mixing them is a common SC-900 error.",
            source_id="doc-defender-endpoint",
            semantic_family_id="defender_xdr_workload_suite",
            tested_decision="mde_device_edr_vs_mdi_directory_attacks",
            batch=b,
        ),
        question_record(
            serial=262,
            leaf="defender_for_cloud_apps",
            difficulty="intermediate",
            stem_style="short_scenario",
            stem="Unsanctioned SaaS discovery is in scope. Phishing in Exchange Online is in scope. Which pairing is accurate?",
            choices=[
                (
                    "a",
                    "Defender for Cloud Apps for the CASB/SaaS problem; Defender for Office 365 for email and collaboration threats",
                ),
                ("b", "Defender for Office 365 is the CASB that inventories unsanctioned SaaS"),
                ("c", "Defender for Cloud Apps detonates mailbox attachments as Safe Attachments"),
                ("d", "Both problems are solved only by Azure Key Vault"),
            ],
            correct="a",
            explanation="CASB and email protection are different Defender workloads. Cloud Apps is not Safe Attachments, and Defender for Office 365 is not the shadow-IT inventory.",
            source_id="doc-defender-cloud-apps",
            semantic_family_id="defender_xdr_workload_suite",
            tested_decision="mcas_casb_not_mdo_email_protection",
            batch=b,
        ),
        question_record(
            serial=263,
            leaf="defender_for_identity",
            difficulty="intermediate",
            stem_style="concept_distinction",
            stem="A learner says Microsoft Defender for Identity is the tool that synchronizes on-premises users into Entra ID. What is the accurate correction?",
            choices=[
                (
                    "a",
                    "Hybrid identity sync is Entra Connect (or related sync); Defender for Identity detects identity attacks in Active Directory",
                ),
                ("b", "Defender for Identity is the only supported hybrid sync engine"),
                ("c", "Entra Connect is an XDR email workload"),
                ("d", "Pass-the-ticket detections require password hash synchronization to be disabled"),
            ],
            correct="a",
            explanation="Entra Connect (and related hybrid identity tooling) synchronizes identities. Defender for Identity is a threat-detection workload for Active Directory, not the sync engine.",
            source_id="doc-defender-identity",
            semantic_family_id="defender_xdr_workload_suite",
            tested_decision="mdi_is_not_entra_connect_sync",
            misconception_target="mdi_syncs_hybrid_identity",
            batch=b,
        ),
        question_record(
            serial=264,
            leaf="defender_vulnerability_management",
            difficulty="intermediate",
            stem_style="concept_distinction",
            stem="A device has an unpatched browser CVE. A mailbox has a malware attachment. Which pairing is accurate?",
            choices=[
                (
                    "a",
                    "Defender Vulnerability Management ranks the software weakness; Defender for Office 365 handles the email malware",
                ),
                ("b", "Vulnerability Management detonates mailbox attachments"),
                ("c", "Safe Attachments closes CVEs on endpoints"),
                ("d", "Both needs are met only by Azure DDoS Protection"),
            ],
            correct="a",
            explanation="Vulnerability management is exposure and weakness prioritization. Email malware is Defender for Office 365. They are not interchangeable.",
            source_id="doc-defender-vulnerability-management",
            semantic_family_id="defender_xdr_workload_suite",
            tested_decision="mdvm_cve_not_mdo_email_malware",
            batch=b,
        ),
        question_record(
            serial=265,
            leaf="defender_threat_intelligence",
            difficulty="intermediate",
            stem_style="concept_distinction",
            stem="An analyst has a suspicious domain and wants actor, infrastructure, and intel-article context from Microsoft. How does Defender Threat Intelligence differ from Sentinel hunting?",
            choices=[
                (
                    "a",
                    "Defender TI provides threat-actor and infrastructure intelligence; Sentinel hunting queries the organization's own log data",
                ),
                ("b", "Sentinel hunting is Microsoft's public actor encyclopedia, and Defender TI is only NSG logging"),
                ("c", "Defender TI recertifies guest users"),
                ("d", "They are both sensitivity-label templates"),
            ],
            correct="a",
            explanation="Defender TI is threat-intelligence context. Sentinel hunting searches collected tenant telemetry. They are complementary, not interchangeable.",
            source_id="doc-defender-ti",
            semantic_family_id="defender_xdr_workload_suite",
            tested_decision="defender_ti_intel_vs_sentinel_tenant_hunting",
            batch=b,
        ),
        question_record(
            serial=266,
            leaf="defender_portal",
            difficulty="intermediate",
            stem_style="concept_distinction",
            stem="SOC analysts want one console for Defender XDR incidents. Compliance analysts want Purview solutions. Cloud operators want Azure resource security. Which mapping is accurate?",
            choices=[
                (
                    "a",
                    "Microsoft Defender portal for XDR operations, Purview portal for compliance, Azure portal for Azure resource security",
                ),
                ("b", "The Defender portal is the only place to declare records and manage Azure VMs"),
                ("c", "The Purview portal investigates endpoint process trees"),
                ("d", "The Azure portal is Microsoft's only eDiscovery console"),
            ],
            correct="a",
            explanation="Those portals align to different jobs: XDR operations, compliance/data governance, and Azure resource management. They should not be treated as one interchangeable console.",
            source_id="doc-defender-portal",
            semantic_family_id="defender_xdr_workload_suite",
            tested_decision="defender_portal_vs_purview_portal_vs_azure_portal",
            batch=b,
        ),
        question_record(
            serial=267,
            leaf="cloud_security_posture_management",
            difficulty="intermediate",
            stem_style="misconception_correction",
            stem="A manager says CSPM will detect a running malware process on a VM the same way EDR does. What is the accurate correction?",
            choices=[
                (
                    "a",
                    "CSPM assesses configuration posture; detecting running threats on a workload is cloud workload protection or endpoint detection",
                ),
                ("b", "CSPM is Microsoft's EDR agent and replaces Defender for Endpoint"),
                ("c", "CSPM is only a retention label"),
                ("d", "CSPM issues FIDO2 keys to virtual machines"),
            ],
            correct="a",
            explanation="CSPM is misconfiguration and standards posture. Runtime threat detection belongs to workload protection or EDR, not to CSPM alone.",
            source_id="doc-cspm",
            semantic_family_id="defender_for_cloud_cspm_cwp",
            tested_decision="cspm_is_not_runtime_edr",
            misconception_target="cspm_equals_malware_detection",
            batch=b,
        ),
        question_record(
            serial=268,
            leaf="siem_and_soar",
            difficulty="intermediate",
            stem_style="short_scenario",
            stem="In Microsoft Sentinel, analytics rules raise incidents from correlated data, while playbooks then run automated actions. Which mapping is accurate?",
            choices=[
                ("a", "Analytics rules are SIEM detection; playbooks are SOAR automation"),
                ("b", "Playbooks correlate logs, and analytics rules physically isolate racks"),
                ("c", "Both features are sensitivity labels"),
                ("d", "Analytics rules are Azure Bastion sessions"),
            ],
            correct="a",
            explanation="Sentinel uses analytics for detection (SIEM) and playbooks for automated response (SOAR). Learners should not reverse those jobs.",
            source_id="module-describe-security-capabilities-of-azure-sentinel",
            semantic_family_id="sentinel_siem_soar_automation",
            tested_decision="sentinel_rules_are_siem_playbooks_are_soar",
            batch=b,
        ),
        question_record(
            serial=269,
            leaf="defender_xdr_services",
            difficulty="intermediate",
            stem_style="short_scenario",
            stem="Defender XDR can automatically disrupt an in-progress attack across workloads. How should a learner contrast that with a SIEM that still needs an analyst to run a playbook?",
            choices=[
                (
                    "a",
                    "XDR can take coordinated Microsoft-workload actions; a SIEM still depends on ingested data plus detection and (often) orchestrated response you configure",
                ),
                (
                    "b",
                    "A SIEM always automatically disables Entra users with no configuration, and XDR cannot contain anything",
                ),
                ("c", "XDR is only a WAF, and a SIEM is only a retention label"),
                ("d", "They are the same because both are Azure Key Vault"),
            ],
            correct="a",
            explanation="Defender XDR is built around Microsoft workload correlation and automated disruption. A SIEM such as Sentinel is broader log correlation plus SOAR you design. Neither is WAF, retention, or Key Vault.",
            source_id="doc-defender-xdr",
            semantic_family_id="defender_xdr_workload_suite",
            tested_decision="xdr_automated_disruption_vs_siem_configured_response",
            batch=b,
        ),
        question_record(
            serial=270,
            leaf="defender_for_office_365",
            difficulty="intermediate",
            stem_style="concept_distinction",
            stem="A campaign delivers malware inside email attachments. Why is Defender for Office 365 a better primary control than Azure WAF for that scenario?",
            choices=[
                (
                    "a",
                    "Defender for Office 365 inspects email and collaboration content; WAF inspects HTTP web-app traffic",
                ),
                ("b", "WAF is Microsoft's Safe Attachments engine"),
                ("c", "Defender for Office 365 only protects Azure public IPs"),
                ("d", "Email attachments are filtered only by network security groups"),
            ],
            correct="a",
            explanation="Email malware and phishing are Defender for Office 365. WAF protects web applications. NSGs do not detonate mailbox attachments.",
            source_id="doc-defender-office",
            semantic_family_id="defender_xdr_workload_suite",
            tested_decision="mdo_email_malware_not_waf",
            batch=b,
        ),
        question_record(
            serial=271,
            leaf="defender_for_endpoint",
            difficulty="intermediate",
            stem_style="short_scenario",
            stem="An EDR investigation can isolate a compromised laptop from the network while the incident is handled. Which workload provides that device-response action class?",
            choices=[
                ("a", "Microsoft Defender for Endpoint"),
                ("b", "Microsoft Purview Compliance Manager"),
                ("c", "Azure Web Application Firewall"),
                ("d", "Service Trust Portal"),
            ],
            correct="a",
            explanation="Device isolation and related EDR response actions belong to Defender for Endpoint. Compliance Manager, WAF, and STP do not isolate endpoints.",
            source_id="doc-defender-endpoint",
            semantic_family_id="defender_xdr_workload_suite",
            tested_decision="mde_device_isolation_response_action",
            batch=b,
        ),
        question_record(
            serial=272,
            leaf="defender_for_cloud_apps",
            difficulty="intermediate",
            stem_style="concept_distinction",
            stem="Conditional Access can require a compliant device. Defender for Cloud Apps can also monitor or control a session after the user is in a SaaS app. What is the CASB adding?",
            choices=[
                ("a", "App and session visibility or control inside cloud apps, beyond the initial access decision"),
                ("b", "Replacement of Entra ID as the identity provider"),
                ("c", "Replacement of Azure Key Vault for certificate issuance"),
                ("d", "Replacement of Defender for Endpoint sensors"),
            ],
            correct="a",
            explanation="The CASB adds SaaS app discovery and in-app/session controls. It does not replace Entra ID, Key Vault, or endpoint sensors.",
            source_id="doc-defender-cloud-apps",
            semantic_family_id="defender_xdr_workload_suite",
            tested_decision="mcas_session_control_after_ca_grant",
            batch=b,
        ),
        question_record(
            serial=273,
            leaf="defender_for_identity",
            difficulty="intermediate",
            stem_style="short_scenario",
            stem="The identity team wants detections for reconnaissance and lateral movement that start in on-premises Active Directory. Where do Defender for Identity sensors typically get those signals?",
            choices=[
                (
                    "a",
                    "From Active Directory environment signals, commonly via sensors aligned to domain controllers or AD FS",
                ),
                ("b", "From Azure DDoS Protection metrics only"),
                ("c", "From Purview retention label analytics only"),
                ("d", "From Service Trust Portal audit PDFs only"),
            ],
            correct="a",
            explanation="Defender for Identity is built on Active Directory signals, typically collected with sensors in the AD environment. DDoS metrics, retention analytics, and STP PDFs are not that source.",
            source_id="doc-defender-identity",
            semantic_family_id="defender_xdr_workload_suite",
            tested_decision="mdi_uses_ad_environment_signals",
            batch=b,
        ),
        question_record(
            serial=274,
            leaf="defender_portal",
            difficulty="intermediate",
            stem_style="short_scenario",
            stem="SOC analysts hunt across Defender XDR alerts in one operations console. A compliance officer needs Microsoft audit reports about Microsoft's own services. Which pairing is accurate?",
            choices=[
                (
                    "a",
                    "Microsoft Defender portal for XDR operations; Service Trust Portal for Microsoft's audit and trust documents",
                ),
                ("b", "Service Trust Portal is the XDR incident queue"),
                ("c", "The Defender portal publishes Microsoft's ISO audit PDFs as its primary job"),
                ("d", "Both jobs are done only in Azure Bastion"),
            ],
            correct="a",
            explanation="The Defender portal is for XDR operations. The Service Trust Portal publishes Microsoft's compliance evidence. They are frequently confused because both are 'portals'.",
            source_id="doc-defender-portal",
            semantic_family_id="defender_xdr_workload_suite",
            tested_decision="defender_portal_ops_vs_stp_microsoft_evidence",
            batch=b,
        ),
        question_record(
            serial=275,
            leaf="microsoft_defender_for_cloud",
            difficulty="intermediate",
            stem_style="concept_distinction",
            stem="Defender for Cloud can show regulatory-control status for Azure resources. Compliance Manager assesses the customer's implementation of compliance controls. Why switch products for those jobs?",
            choices=[
                (
                    "a",
                    "Azure/multicloud regulatory posture lives in Defender for Cloud; customer compliance assessments live in Purview Compliance Manager",
                ),
                ("b", "Compliance Manager remediates NSG rules as its primary job"),
                ("c", "Defender for Cloud is the only place to complete GDPR improvement actions for Microsoft 365"),
                ("d", "They are the same score stored in Azure Bastion"),
            ],
            correct="a",
            explanation="A regulatory view of Azure resources is not the same as Compliance Manager's customer-control assessments. SC-900 expects that product split.",
            source_id="doc-defender-for-cloud",
            semantic_family_id="defender_for_cloud_cspm_cwp",
            tested_decision="dfc_azure_regulatory_view_not_compliance_manager",
            batch=b,
        ),
    ]
